pkg/agent/globalstate.go
pkg/agent/run.go
pkg/agent/sched.go
pkg/agent/serve.go
pkg/api/types.go
pkg/informant/agent.go
pkg/plugin/config.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/plugin/trans.go
pkg/util/handle.go
pkg/util/watch.go

Collection of broad changes prompted by review comments on #25. Planning to merge this without squashing.
In future, it'd be nice to have a lint to detect some of these. I don't know if the right lints are already available, but if not, [adding a custom lint to golangci](https://golangci-lint.run/contributing/new-linters/) seems pretty ok.

repo-wide changes from review comments on #25

---

go.mod
go.sum
pkg/agent/entrypoint.go
pkg/agent/globalstate.go
pkg/agent/sched.go

I did some reorganization of this broker whatsis and wrote a boatload
of tests. There are also a number of reasonable options and
possibilities in this version that give us options for dealing with
high-volume publishers without putting backpressure on them.
To be clear, the options we're using are the most strict/synchronous/everything 
blocks everything and never drops anything.

deps: bump fun deps

---

pkg/agent/informant.go
pkg/agent/runner.go
pkg/informant/agent.go
pkg/plugin/plugin.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/plugin/trans.go
pkg/plugin/watch.go

Closes: #45 
Fixing a nit that I left somewhere.

style: function formating

---

go.mod
go.sum
scripts/download-deployments.sh
vm_image/build.sh

Not strictly required, but worth doing this sooner rather than later.

Bump neonvm v0.4.5 -> v0.4.6

---

deploy/autoscaler-agent.yaml
pkg/agent/billing.go
pkg/agent/config.go
pkg/agent/entrypoint.go
pkg/agent/watch.go
pkg/billing/client.go

Haven't tested it, still need to add more comments.

agent: collect + send billing metrics

---

go.mod
go.sum

Fixes an issue causing autoscaler-agents to crash on startup, see: https://github.com/neondatabase/autoscaling/pull/59#issuecomment-1454306986.

Bump tychoish/fun v0.7.0 -> v0.7.1

---

pkg/agent/billing.go
pkg/billing/client.go
pkg/billing/model.go

As a follow up to: https://github.com/neondatabase/autoscaling/pull/49#discussion_r1123623721

billing: change idempotency key

---

cmd/autoscale-scheduler/main.go
pkg/plugin/plugin.go
pkg/plugin/run.go

In persuit of #55, a better solution I hope. I think it's better to
roll these out slowly, more of the goroutines can be serviceified later.

scheduler: service orchestration

---

pkg/plugin/run.go

Pulled out orthogonal change from previous PR.

fixup: use const for constants

---

ARCHITECTURE.md

Forgot about this in the original PR, better late than never :)

Add pkg/billing to ARCHITECTURE.md

---

deploy/autoscale-scheduler.yaml
deploy/autoscaler-agent.yaml
pkg/agent/config.go
pkg/agent/dumpstate.go
pkg/agent/entrypoint.go
pkg/agent/globalstate.go
pkg/agent/runner.go
pkg/plugin/config.go
pkg/plugin/dumpstate.go
pkg/plugin/plugin.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/plugin/trans.go
pkg/util/buildinfo.go

plugin: Rename fields for state dump JSON

---

ARCHITECTURE.md
README.md
neonvm/README.md
neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/config/common/certmanager/certificate.yaml
neonvm/config/common/crd/bases/vm.neon.tech_virtualmachines.yaml
neonvm/config/common/rbac/service_account.yaml
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachine_qmp_queries.go
neonvm/controllers/virtualmachinemigration_controller.go
neonvm/samples/vm-example/init
neonvm/tools/vxlan/controller/main.go
pkg/informant/endpoints.go

- Update remaining references to `neondatabase/neonvm`
- Cherry-pick fixes for typos from https://github.com/neondatabase/neonvm/pull/39

Update outdated docs, fix typos

---

pkg/util/watch.go

Builds on #109, required by #128.

util/watch: add Relist() method

---

Makefile

Extracted from #133, because I needed it while working on #128.

fix GIT_INFO in Makefile

---

deploy/autoscale-scheduler.yaml
pkg/agent/globalstate.go
pkg/agent/runner.go
pkg/agent/watch.go
pkg/api/vminfo.go
pkg/plugin/plugin.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/plugin/trans.go
pkg/plugin/watch.go
tests/e2e/autoscaling/00-create-vm.yaml
vm-deploy.yaml

Part of #115. In progress. Builds on #38 additionally requires requires:

Allow annotation to set/override scaling bounds

---

ARCHITECTURE.md

ref https://github.com/neondatabase/autoscaling/pull/172#discussion_r1167453496

ARCHITECTURE: Update description of pkg/api

---

cmd/autoscale-scheduler/main.go
cmd/autoscaler-agent/main.go
cmd/vm-informant/main.go
go.mod
go.sum

I think I'm mostly done (at least for now, probably most changes will be if only if we/cloud need more/different things).

bump: tychoish/fun

---

.github/workflows/lint.yml
Makefile
build/autoscale-scheduler/Dockerfile
build/autoscaler-agent/Dockerfile
build/vm-informant/Dockerfile
go.mod
neonvm/Dockerfile
neonvm/hack/Dockerfile.generate
neonvm/runner/Dockerfile
neonvm/tools/vxlan/Dockerfile

Use go 1.20

---

neonvm/config/common/crd/bases/vm.neon.tech_virtualmachines.yaml

Realized I never ran `make manifests` during the changes from #140.

Update VM CRD for #140

---

neonvm/config/common/crd/bases/vm.neon.tech_virtualmachinemigrations.yaml
neonvm/config/common/crd/bases/vm.neon.tech_virtualmachines.yaml

Wasn't caught because #187 and #191 weren't merged.

Follow-up to #132: fix manifests

---

pkg/api/vminfo.go

Allows the scaling bounds to be used directly in cloud, instead of duplicating the type, as in https://github.com/neondatabase/cloud/pull/4650.

api: Make scalingBounds public

---

pkg/informant/filecache.go

ref https://neondb.slack.com/archives/C03H1K0PGKH/p1681462163573109?thread_ts=1681459030.472469&cid=C03H1K0PGKH

informant/filecache: Respect max file cache size

---

pkg/informant/endpoints.go

Noticed this while working on #223, ironically forgot to push until a week later.

informant: Finish comment above State.memReservedForFileCache

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/apis/neonvm/v1/virtualmachine_webhook.go
neonvm/apis/neonvm/v1/zz_generated.deepcopy.go
neonvm/config/common/crd/bases/vm.neon.tech_virtualmachines.yaml
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachinemigration_controller.go
neonvm/runner/main.go
pkg/agent/billing.go
pkg/agent/runner.go
pkg/api/VERSIONING.md
pkg/api/types.go
pkg/api/vminfo.go
pkg/api/vminfo_test.go
pkg/plugin/config.go
pkg/plugin/dumpstate.go
pkg/plugin/plugin.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/plugin/trans.go
tests/e2e/autoscaling/01-assert.yaml

Miscellaneous edits in post for #172. Mostly backwards compatibility fixes

Fractional CPU fixups

---

pkg/agent/runner.go

Fixes #219.
What went wrong? When the scheduler plugin returns a response that the agent thinks is invalid, (*Scheduler).handleFatalError() is called while holding s.runner.lock, even though handleFatalError() also acquires the lock.
handleFatalError is sometimes called before the lock has been acquired, so the easiest way to resolve this is to just release the lock before calling handleFatalError.
Note: we don't have to worry about different threads racing to call handleFatalError because the entire operation must take place under the scope of the request lock - the runner lock is just about being able to write to some fields in the Scheduler and Runner.
I was able to reproduce #219 by applying the following patch, which creates an invalid response because the returned resources must be …

agent: Fix deadlock on invalid plugin response

---

deploy/autoscale-scheduler.yaml

Probably worth adding to .git-blame-ignore-revs afterward.

deploy/sched: Fix whitespace typo

---

pkg/agent/globalstate.go

AFAICT these should have been handled by #111.

agent/globalstate: Fix logs for event handling

---

Makefile

I found it hard to understand what was going on, so added some comments to broadly lay out the stages of the process.

make: Add comments to render steps

---

.github/workflows/release.yaml
deploy/autoscale-scheduler.yaml
deploy/autoscaler-agent.yaml

release workflow: Remove unused LOCAL_{AGENT,SCHED}_IMAGE

---

Makefile

make: Remove deploy-controller target

---

pkg/agent/billing.go

Not having this made the cleanup from https://github.com/neondatabase/cloud/issues/5101 harder than it needed to be.
Ordinarily I _would_ be worried about the increase in log volume, but realistically this is two log lines per endpoint each 30s - and we'll have a lot more from the runners themselves.

agent/billing: Log key info about events on append to batch

---

pkg/util/watch.go

This also fixes a possible race on update events, because we weren't locking the store.
The function basically already existed by itself in the body of Watch as an anonymous function. Other than moving the locks, no other changes were made.
I think something very similar was originally implemented in #65, but that PR seems mostly stalled.
This PR is mostly "cleaning things up a little as I'm figuring out where to add metrics".

util/watch: Move event handling into its own function

---

pkg/agent/entrypoint.go
pkg/agent/globalstate.go
pkg/agent/indexedstore.go
pkg/agent/schedwatch/trackcurrent.go
pkg/agent/schedwatch/watch.go
pkg/agent/watch.go
pkg/plugin/plugin.go
pkg/plugin/watch.go
pkg/util/watch/watch.go

Just cleanup. Conflicts with #295, but that's ok — should be easy enough to sort out.
Builds on #296. Do not merge until after that PR.
**NB: This PR should be merged by rebase.**
Both commits should be added to .git-blame-ignore-revs once merged.

util: Move watch.go into a new pkg/util/watch

---

pkg/api/vminfo.go

ExtractVmInfo: change hard error to warn when min !< use or use !< max

---

pkg/informant/agent.go

Suspend old agent then resume new one during switch

---

pkg/agent/billing/billing.go
pkg/agent/billing/indexedstore.go
pkg/agent/config.go
pkg/agent/entrypoint.go

Similar to other recent PRs. Pre-req for #310.
**Note: This PR must be merged by rebase.** (and then the commits added to .git-blame-ignore-revs)

agent: Move billing logic into new pkg/agent/billing

---

pkg/plugin/state.go

Report over budget nodes instead of erroring

---

.git-blame-ignore-revs

Wanted to do this before I forget, but maybe worth waiting for #317 to avoid spamming.

.git-blame-ignore-revs: Add commits from #309, #317

---

pkg/informant/agent.go

Also removes the reimplementation of the deadlock checker, which we already have implemented for ChanMutex in a more efficient manner.

informant: Switch AgentSet.lock to util.ChanMutex

---

neonvm/controllers/virtualmachine_controller.go

ref https://github.com/neondatabase/cloud/pull/5196#discussion_r1206722452
Maybe the one-line implementation is a little too weird. Happy to change.

neonvm/runner: Set AutomountServiceAccountToken = false

---

neonvm/tools/vm-builder-generic/main.go
neonvm/tools/vm-builder/main.go

Found myself wanting this while working on #263 - seems to work ok :)

neonvm/builder: Make output prettier

---

pkg/plugin/plugin.go
pkg/plugin/watch.go

With adding new callbacks, it was becoming unwieldy without *some* kind of grouping.
~~**NB:** This PR builds on #323, and must not be merged before it.~~

plugin: Group watch callbacks into structs

---

.github/workflows/e2e-test.yaml
Makefile
kind/config.yaml

- `kind` updated to v0.20.0
- kind config updated for 1.25.11 k8s
- `kubectl` updated for 1.25 k8s

kind and kubectl version update for 1.25 k8s

---

pkg/plugin/state.go

Must have missed it as part of #323.

plugin: Fix outdated log line

---

neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachinemigration_controller.go

neonvm/controller: Update runner pod labels/annotations when VM's change

---

pkg/agent/schedwatch/trackcurrent.go

This commit removes the watch.Store from `schedulerWatchState`, also removing the `watch.Store.Stop()` that was spuriously closing scheduler watchers as soon as the first Runner finished.
This fixes a long-standing bug that has been affecting our ability to handle scheduler restarts.

agent/schedwatch: Remove watch.Store field (fix spurious close)

---

pkg/plugin/plugin.go

Just some minor cleanups in preparation for #361.

plugin: Clean up IndexedVMStore usage

---

pkg/util/watch/watch.go

Pre-req for #361, directly copying everything from `NameIndex`.

util/watch: Add FlatNameIndex for non-namespaced objects (e.g. Nodes)

---

pkg/plugin/plugin.go
pkg/plugin/state.go
pkg/plugin/watch.go

This is a pre-req for adding per-node usage metrics, because of what's mentioned in #248:
> Looking at the state for prod-us-east-2-delta, there's currently 107
> nodes that the plugin is still tracking state for that don't exist
Unclear whether this will resolve #248 ("scheduler has a memory leak").
---
A lot of the extra work behind this PR is around using the new watch.Store instead of the preexisting calls to the K8s API when we need to fetch information about a Node. Realistically... this is probably more hassle than it's worth, but it's nice to have the consistency.
**NB: This PR builds on #360, and must not be merged until BOTH #359 and #360 have been.**

plugin: Cleanup state for deleted Nodes

---

pkg/plugin/plugin.go
pkg/plugin/prommetrics.go
pkg/plugin/state.go

**NB: This PR builds on #361, must not be merged until it has been.**

plugin: Add per-node resource level metrics

---

.github/workflows/release.yaml

Should have been handled by #282, but oh well.

release workflow: Add vmscrape.yaml asset

---

cmd/vm-informant/main.go

This was... fascinating to debug. Here's a story:
For the past few days in prod, it's seemed like we've had more "autoscaling stuck" VMs than there should be - even after taking into account that VMs that are part of a pool will always be stuck.
We finally got confirmation of that with the new metrics from v0.12.0, which unlocked *just* looking at the "autoscaling stuck" VMs that aren't in pools, and it turned out there were around 25 — much more than expected.
So, debugging: the autoscaler-agent's "state dump" feature proves useful, showing that these are *mostly* VMs from 2023-07-07 and after, with one from 07-04 and one from 07-05. So maybe a recent release did something? That wouldn't make sense though — we haven't had any major changes to the vm-informant, aside from the connection …

informant: Fix parent process stall when child dies qickly

---

.golangci.yml

lint/exhaustruct: exclude K8s DeleteOptions

---

pkg/plugin/plugin.go

There's some missing logs for alertable metrics (e.g. PostFilter calls, appropriate log levels for Filter rejections).
In general, we'd like to be able to associate any change in a metric with some log line. This should help with that.

plugin: Improve plugin method logs

---

pkg/agent/informant.go
pkg/agent/runner.go
pkg/agent/schedwatch/trackcurrent.go
pkg/informant/agent.go
pkg/util/signal.go
pkg/util/watch/watch.go

agent/informant: make CondChannelSignal generic

---

pkg/util/signal.go

Don't know how that slipped past all the checks . . .

util: format signal.go

---

pkg/plugin/plugin.go

As written, it's currently just noise that basically just informs us that there were some overprovisioning pods on the node. It's better to include that in the message with the final verdict, and not make it a warning — we expect to have a bunch of these, actually.

plugin: make Filter unknownPods logs less verbose

---

neonvm/runner/main.go

ref https://neondb.slack.com/archives/C03TN5G758R/p1691599139129879?thread_ts=1691594517.209849&cid=C03TN5G758R

neonvm/runner: Handle hybrid cgroup v1/v2 systems

---

pkg/util/signal.go

This predates #403. I should've caught it then but didn't - only noticed while debugging for #463.

util/signal: Make Recv() return <-chan

---

pkg/agent/dispatcher.go

agent/dispatcher: Use the lock on waiters in more places

---

vm-examples/pg14-disk-test/Dockerfile.vmdata

Validated locally. Probably leftover from #442?

pg14-disk-test: Fix monitor connection addr

---

pkg/agent/dispatcher.go

Doing this with a deferred function means that we're guaranteed to propagate some kind of response, even if things panic. It makes our jobs a bit easier for the actual message handling later.

agent/dispatcher: Signal and delete waiter on failure

---

pkg/agent/dispatcher.go

May end up conflicting with #497, but oh well.

agent/dispatcher: Fix ignored error during Call

---

deploy/agent/config_map.yaml
pkg/agent/config.go
pkg/agent/dispatcher.go

add timeout for creating new dispatcher

---

pkg/agent/dispatcher.go
pkg/agent/informant.go

This is an initial refactoring that should make some of the metrics parts easier.
Part of #492.

agent: Move awaitMonitorResponse into (*Dispatcher).Call

---

Makefile
build/vm-monitor/Dockerfile

This keeps autoscaling and neon 'N Sync.

pull vm-monitor from neon repository

---

neonvm/runner/main.go

Copy-pasting the added comment:
> cpuLimitOvercommitFactor sets the amount above the VM's
> spec.guest.cpus.use that we set the QEMU cgroup's CPU limit to.
> e.g. if cpuLimitOvercommitFactor = 3 and the VM is using 0.5 CPUs, we
> set the cgroup to limit QEMU+VM to 1.5 CPUs.
>
> This exists because setting the cgroup exactly equal to the VM's CPU
> value is overly pessimistic, results in a lot of unused capacity on
> the host, and particularly impacts operations that parallelize between
> the VM and QEMU, like heavy disk access.
>
> See also: https://neondb.slack.com/archives/C03TN5G758R/p1693462680623239
With the factor at 4x, this _should_ also resolve neondatabase/cloud#6243 as well (given that the slow starts were only happening when the cgroup was moved from 1 CPU to 0.25 CPUs, and …

neonvm/runner: Add overcommit factor for CPU limits

---

pkg/agent/runner.go
pkg/agent/runner_test.go

This fixes #512 (the second test added was failing before the change to DesiredVMState).
The reasoning for the change is given in the added comment.

agent/runner: Fix DesiredVMState incorrect decrease

---

neonvm/runner/main.go

ref https://neondb.slack.com/archives/C03H1K0PGKH/p1693932486942769?thread_ts=1693931140.497809&cid=C03H1K0PGKH

neonvm/runner: Mount EmptyDisk fs with 0777

---

neonvm/runner/main.go

Before this PR, an existing QMP connection, e.g., from neonvm-controller
would cause dial timeout for the runner's SIGTERM handler.
The reason is that a single `-qmp` instance handles connections
sequentially (trivial to test this with one qemu proces and two other
terminals, each connecting to the qmp socket).
The solution in this PR is to add a second `-qmp` instance, just for
the SIGTERM handler, that listens on a UNIX domain socket.
Related PRs:
- neonvm-controller fix to avoid leaking connections:
https://github.com/neondatabase/autoscaling/pull/527
- actually correct handling of the ACPI power button event
that our SIGTERM handler would trigger, were it able to
connect to the QMP socket
https://github.com/neondatabase/autoscaling/pull/525/

runner: separate qmp socket for the SIGTERM handler goroutine

---

pkg/plugin/ARCHITECTURE.md

This was a planned feature that never actually got implemented, and any semblance of preparations for support were fully removed long ago (#87).

plugin/ARCHITECTURE: Remove misleading section on runtime config changes

---

pkg/agent/runner.go

agent/runner: Simplify getMetricsLoop

---

pkg/agent/dispatcher.go

As written in the added comment, there's a size limit for our websocket close frames, and we often exceed that on these "Error handling message" errors. When that happens, the weboscket library emits a non-JSON log that we have no way of specifying an alternate sink for, unfortunately.
So, to resolve all of the above, this commit changes the "reason" for the close frame on those errors to just have the "root" error, rather than the entire thing.
Fixes #568.

agent: Fix oversized websocket close frames

---

pkg/agent/core/state.go

Noticed this while working in the area, not sure if this has occurred yet in prod.

agent/core: Fix never downscaling after single failure

---

deploy/agent/daemonset.yaml
deploy/scheduler/deployment.yaml

ref https://neondb.slack.com/archives/C03TN5G758R/p1698767562305599?thread_ts=1698767357.728689&cid=C03TN5G758R

deploy: Bump resource limits from load testing

---

neonvm/config/default-vxlan/manager_config_patch.yaml
neonvm/config/default-vxlan/vxlan-controller/daemonset.yaml

This PR:
- add more resources (requests and limits) to neonvm-controller
- add more limits to neonvm-vxlan-contrroller
this improve stability and speed when thousands VMs running.

update in resources for neonvm controllers

---

neonvm/controllers/virtualmachinemigration_controller.go

Set migration as failed if underlying VM not found

---

pkg/agent/schedwatch/trackcurrent.go

This was noticed on staging dev-eu-west-1-zeta ([ref](https://neondb.slack.com/archives/C03TN5G758R/p1699208662336279)), and with some digging, realized that the following sequence of events could have caused the observed behavior:
1. Scheduler deploy causes >1 scheduler pod to be present in the cluster
2. New VM with autoscaling enabled appears (either existing or fresh)
3. Initial `agent.Runner` calls `WatchSchedulerUpdates`
4. `WatchSchedulerUpdates` calls `eventBroker.Subscribe()` but exits with error without calling `eventBroker.Unsubscribe()`.
5. When the next scheduler event comes along, the event broker blocks forever on trying to send the event to a channel that no one's listening to.
For now, this issue can be circumvented by restarting all autoscaler-agents after making a …

agent/schedwatch: Fix deadlock

---

.github/workflows/vm-kernel.yaml

WIP: parametrize vm-kernel job for workflow_dispatch

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/apis/neonvm/v1/zz_generated.deepcopy.go
neonvm/config/common/crd/bases/vm.neon.tech_virtualmachines.yaml
neonvm/controllers/virtualmachine_controller.go
neonvm/runner/main.go

neonvm: Add ability to append to kernel command line

---

.github/workflows/release.yaml

release workflow: Use kernel 6.1.63

---

pkg/util/watch/watch.go

- fixing triggered relist case and handle watchers
fixes #631

util/watch: fix triggered relist on watch

---

Makefile
k3d/config.yaml

add username to local cluster name

---

cmd/autoscaler-agent/main.go

ref https://neondb.slack.com/archives/C03H1K0PGKH/p1702048356886819?thread_ts=1701881238.622479
Related to #681.

agent: Log config on startup

---

pkg/plugin/watch.go

Fixes #689. tl;dr: we need to avoid typed nils to not get nil derefs when trying to create a k8s event.
Tested locally with the reproduction steps from #689, and this appears to fix the issue.

plugin: Fix nil deref on failed ExtractVmInfo on VM update

---

pkg/agent/prommetrics.go
pkg/agent/watch.go

Requested here: https://neondb.slack.com/archives/C061BGTBZMG/p1702897129242809

agent: added project ID label to per vm metrics

---

neonvm/runner/main.go

- adds additional `iptables` rules that allow traffic from localhost (in the runner pod) to ports on the VM.
Now possible do `kubectl port-forward vm-runner-pod-name 9100` and then run `curl localhost:9100/metrics`
or just `kubectl exec -it vm-runner-pod-name -- curl localhost:9100/metrics`
These rules will be added for port 9100 as an example
```
iptables -t nat -A OUTPUT -m addrtype --src-type LOCAL --dst-type LOCAL -p tcp --dport 9100 -j DNAT --to-destination 169.254.254.254:9100
iptables -A OUTPUT -s 127.0.0.1 -d 169.254.254.254 -p tcp --dport 9100 -j ACCEPT
```
and this rule for all ports
```
iptables -t nat -A POSTROUTING -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE
```
fixes #692

fix iptables rules for traffic from localhost

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/config/common/crd/bases/vm.neon.tech_virtualmachines.yaml
neonvm/controllers/virtualmachine_controller.go
neonvm/runner/main.go
scripts/qemu-monitor.sh

Introduce another QMP port, and a convenience script to forward it for manual debugging.

qmp: add manual QMP access

---

pkg/agent/core/state.go
pkg/api/types.go

Small improvements I noticed while working in the area.

Miscellaneous comment fixes

---

neonvm/controllers/virtualmachine_controller.go

Fixes https://github.com/neondatabase/autoscaling/issues/453.

neonvm: Update VM resources status after scaling phase is done

---

neonvm/controllers/virtualmachine_controller.go

The previous logic would:
1. Try to update the status
2. If we got a conflict, overwrite the current VirtualMachine object equal to the state on the API server
3. Then, retry with the udpated object (without changing anything!)
This is basically doing extra work for nothing!
We discussed potentially changing this to overwrite the status on conflict, but this could result in issues when operating on stale data (e.g., overwriting .status.podName back to "" after it was already created).
ref https://www.notion.so/neondatabase/Autoscaling-Team-Internal-Sync-179c7d597dbb4fe5b565d9c482d4d166
ref https://neondb.slack.com/archives/C03TN5G758R/p1707414998235459

neonvm-controller: Don't retry update on conflict

---

ARCHITECTURE.md

Finish the sentence that ends prematurely

Clarify Agent-Scheduler protocol in the architecture docs

---

neonvm/config/default-vxlan/manager_config_patch.yaml
neonvm/controllers/config.go
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachine_controller_test.go
neonvm/main.go
neonvm/runner/main.go

Resolves #775, refer there for more information.
Figured out how to implement the thing while writing the issue, figured I might as well open this, if only for discussion.

neonvm: Tune QEMU disk cache settings

---

neonvm/apis/neonvm/v1/virtualmachine_webhook.go
neonvm/apis/neonvm/v1/virtualmachinemigration_webhook.go
neonvm/config/controller/deployment.yaml
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachine_controller_test.go

The only code change here is enabling the seccomp profile for neonvm-controller.
Resolves #778.

neonvm: Remove TODO(user) comments

---

README.md

Add releasing doc to README

---

deploy/scheduler/config_map.yaml

ref https://neondb.slack.com/archives/C03F5SM1N02/p1710953732671389?thread_ts=1710952126.841459

plugin: Increase eventQueueWorkers: 16 -> 64

---

go.mod
neonvm/runner/main.go

Supersedes #790, part of a #711.
Per-commit review can be done. Only the last commit should have functional changes, the rest is ground work.
Motivation: all the tasks in an errgroup include running external commands, so parallelizing it might yield small latency reduction. 
Didn't test this, is our CI sufficient to check such changes?

runner: refactor to make some steps parallel

---

.github/workflows/release.yaml

Forgot to make this change in #857.

Release workflow: add neonvm-runner-image-loader

---

pkg/plugin/state.go

Must have missed it in #653, I think.

plugin: Fix outdated comment about mem slots

---

.github/workflows/lint.yml
.golangci.yml
neonvm/pkg/ipam/ipam.go

Update golangci-lint to v1.58.1

---

neonvm/runner/main.go

Mainly, to have it show up in the shell prompt, when you ssh into a compute VM. Which in turn can help to avoid mistakes like mixing up different computes.

Set hostname in the VM to "vm-<compute name>"

---

pkg/plugin/trans.go
pkg/plugin/trans_test.go

plugin: Fix missing buffer info in handleRequested verdict

---

.github/workflows/build-images.yaml
.github/workflows/build-test-vm.yaml
.github/workflows/check-ca-builds.yaml
.github/workflows/e2e-test.yaml
.github/workflows/lint.yml
.github/workflows/release.yaml
.github/workflows/test.yaml
.github/workflows/vm-example.yaml
.github/workflows/vm-kernel.yaml

- `actions/checkout@v3` -> `actions/checkout@v4`
- `actions/setup-go@v4` -> `actions/setup-go@v5`
- `codespell-project@v2.0` -> `codespell-project/actions-codespell@v2.1`
- `docker/build-push-action@v3` -> `docker/build-push-action@v6`
- `docker/login-action@v2` -> `docker/login-action@v3`
- `docker/setup-buildx-action@v2` -> `docker/setup-buildx-action@v3`
- `docker/setup-qemu-action@v2` -> **Delete**
- `golangci/golangci-lint-action@v3` -> `golangci/golangci-lint-action@v6`
- `reviewdog/action-actionlint@v1.40.0` -> `reviewdog/action-actionlint@v1.54.0`
- `softprops/action-gh-release@v1` -> `softprops/action-gh-release@v2`
- `technote-space/get-diff-action@v6` -> `tj-actions/changed-files@v44.5.7`

CI: update GitHub actions

---

.github/workflows/build-images.yaml
.github/workflows/check-ca-builds.yaml
.github/workflows/vm-kernel.yaml

Use remote docker cache to speed up builds

CI: use docker remote cache

---

neonvm/runner/main.go

I was trying to modify this `createQCOW2` funciton and noticed that I can add comments to explain what individual mkfs options are used for.

Add comments to mkfs options

---

.github/workflows/build-images.yaml

CI: use GitHub OIDC instead of static AWS credentials
>NOTE: merge after https://github.com/neondatabase/infra/pull/1950

Fix ECR access

---

Makefile

Saw this in a couple different PRs that haven't yet been merged (#1111 & #1135), presumably from auto-formatting. Figured I'd open a PR for it so it stops showing up in diffs.

Makefile: Remove trailing whitespace

---

neonvm-runner/cmd/main.go

do not merge: test multi-queue on staging

vm-runner: use multi-queue networking

---

.github/workflows/build-images.yaml
.github/workflows/build-test-vm.yaml
.github/workflows/e2e-test.yaml
.github/workflows/release.yaml

A few different commits, follow-ups to #1138 and #1256, I think.
---
Successful release dry-run with this branch: https://github.com/neondatabase/autoscaling/actions/runs/13293941799?pr=1259

ci: Fix release workflow

---

.github/workflows/release.yaml

Follow-up to #1259 :disappointed:
Previous release workflow attempt failed here: https://github.com/neondatabase/autoscaling/actions/runs/13294819272/job/37125168593

ci/release: Fix vm-builder artifact paths

---

.golangci.yml

Validation was enabled for github action [1], so we have to fix the config.
1: https://github.com/golangci/golangci-lint-action/commit/8d744d5b7f56a6baec6cc8b5f32947e1f52d05fca

golangci-lint: fix config

---

neonvm-controller/cmd/main.go
pkg/neonvm/ipam/demo/ipam.go
pkg/neonvm/ipam/ipam.go
pkg/neonvm/ipam/ipam_test.go
pkg/neonvm/ipam/metrics.go

Two metrics:
- Number of ongoing IPAM operations
- Duration histogram
Part of https://github.com/neondatabase/autoscaling/issues/1294.

neonvm-controller/ipam: add metrics

---

.github/workflows/pr-format-verification.yml

See e.g. #1319 and #1329 for motivation.

CI/pr-format: Allow dependabot + CI run titles

---

UPDATING-K8S.md

`s/made a some/made some/`
Follow-up to #1322.

docs: Fix typo in k8s update guide

---

pkg/plugin/framework_methods.go
pkg/plugin/framework_test.go

There was an issue with incorrect returning of randomized scores. This commit fixes it and adds a test for randomness

scheduler: Fix randomization in NormalizeScores

---

Makefile
README.md

Same as https://github.com/neondatabase/autoscaling/pull/1410, but that one was merged to the wrong branch.

Makefile: fix bugs and add run-e2e target
