.golangci.yml
pkg/agent/globalstate.go
pkg/agent/informant.go
pkg/agent/runner.go
pkg/agent/watch.go
pkg/plugin/plugin.go
pkg/plugin/state.go

I know this is generally unpopular in the go world. I think they're probably right in the general case. For this repo, however, given the prevalence of big state objects (and the number of bugs I've run into where I forgot a field), I feel it's better to have this strict exhaustiveness checking here.
The regexes for types to exclude are intended to be added to whenever necessary.
This already caught a couple things that would have been hard to detect otherwise. Looks like most old, high-usage code (i.e. stuff in `pkg/plugin`) was already fine.
Haven't yet run tests to double-check everything's ok.

Add exhaustruct lint

---

cmd/vm-informant/main.go

There's some benefits to providing this ourselves — mostly that we'll do the cgroup cleanup operations that might be required on failure.

informant: Add auto-restarting capability

---

pkg/billing/model.go

Playground link exhibiting previous behavior: https://go.dev/play/p/uhHOQUssrjv
Didn't actually run into this, but suspected it'd be an issue while taking a deeper look at the code and validated that suspicion with the playground.

billing: Fix infinite recursion in JSON marshaling

---

pkg/agent/runner.go
pkg/api/VERSIONING.md
pkg/api/types.go
pkg/plugin/run.go

Mirrors the versioning for the agent<->informant protocol. Versioning here is required in some form to fix the "allow nil metrics" issue from #27.
Current plan is to release+deploy a new version _just_ with this change (requires autoscaler-agent first, then scheduler), then add the option for nil metrics in a follow-up PR + release.

Add versioning to agent<->plugin protocol

---

pkg/agent/runner.go
pkg/api/VERSIONING.md
pkg/api/types.go
pkg/plugin/run.go
pkg/plugin/state.go

Builds on #50, fixes some annoyances around restart.
Will merge after #50 and its repo version bump.

Allow nil metrics in agent->plugin messages

---

ARCHITECTURE.md
pkg/plugin/ARCHITECTURE.md
pkg/plugin/state.go

Should address the immediate concerns of #64, but I'm not sure it'll actually allow compatibility with cluster-autoscaler.
This PR also happens to remove the majority of log lines we're currently getting on staging.

plugin: Use non-VM pod resource requests, not limits

---

pkg/plugin/state.go

Fixes a panic case from #51 currently affecting staging.

plugin: Handle nil metrics in isBetterMigrationTarget

---

pkg/agent/informant.go
pkg/agent/runner.go
pkg/plugin/plugin.go
pkg/plugin/state.go
pkg/util/chanmutex.go

Also fixes #39, which was occurring because of the change to the plugin's deadlock checker in #32.

Move makeDeadlockChecker to util, use it for plugin

---

pkg/billing/client.go

Missed this before. Currently causing the console to reject/400 our requests.

billing: set content type on requests

---

pkg/agent/billing.go

Panic on staging:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13ba760]
goroutine 28 [running]:
github.com/neondatabase/autoscaling/pkg/agent.(*metricsTimeSlice).Duration(...)
/workspace/pkg/agent/billing.go:50
github.com/neondatabase/autoscaling/pkg/agent.(*billingMetricsState).drainAppendToBatch(0xc000017eb0,
0xc00010f270, 0xc000017f40)
/workspace/pkg/agent/billing.go:243 +0x380
github.com/neondatabase/autoscaling/pkg/agent.RunBillingMetricsCollector({0x1993200,
0xc0004293e0}, 0xc00010f270, {0xc00004800e, 0x28}, 0x0?)
/workspace/pkg/agent/billing.go:100 +0x42c
created by github.com/neondatabase/autoscaling/pkg/agent.MainRunner.Run
/workspace/pkg/agent/entrypoint.go:60 +0x79b
Basically: lastSlice …

agent/billing: fix panic on adding active time event

---

cmd/autoscale-scheduler/main.go
deploy/autoscale-scheduler.yaml
pkg/plugin/config.go
pkg/plugin/plugin.go
pkg/plugin/state.go

This was previously planned, and would have allowed config updates without restart. No work had been done on that for a while, though, so this half-done feature was adding unnecessary tech debt.

plugin: Remove unused config watcher

---

pkg/agent/billing.go

Fixes the issue reported here: https://github.com/neondatabase/cloud/issues/3757#issuecomment-1478374280
The comment added explains why the change is necessary.

agent/billing: fix consumption event duplication

---

deploy/autoscale-scheduler.yaml
deploy/autoscaler-agent.yaml
pkg/agent/config.go
pkg/agent/dumpstate.go
pkg/agent/entrypoint.go
pkg/agent/globalstate.go
pkg/agent/runner.go
pkg/plugin/config.go
pkg/plugin/dumpstate.go
pkg/plugin/plugin.go
pkg/util/buildinfo.go

There was some bulk renaming required in the plugin, so I extracted that into a separate PR (#75) to make reviewing / blame nicer.
I've done a little bit of manual testing for it, seems fine. The JSON output isn't small, so... thorough testing will probably be easier with a dedicated tool to analyze the output.
For now, due to "quirks" of `util.AddHandler`, the body of the request is expected to be "{}". So, example usage would be something like:
```
curl -X GET -d '{}' 'http://localhost:10300/"
```
(for the current default autoscaler-agent port)

agent, plugin: Add "dump state" endpoints

---

pkg/agent/dumpstate.go

Panicked on staging (v0.5.0) with:
```
I0329 08:06:44.830862       1 handle.go:46] dump-state: Received request on / (client = 10.6.30.246:34950) {}
panic: runtime error: index out of range [0] with length 0
goroutine 521 [running]:
github.com/neondatabase/autoscaling/pkg/agent.(*agentState).DumpState.func2()
/workspace/pkg/agent/dumpstate.go:108 +0x190
created by github.com/neondatabase/autoscaling/pkg/agent.(*agentState).DumpState
/workspace/pkg/agent/dumpstate.go:102 +0x1e8
```

agent: Fix dump-state panic

---

pkg/plugin/ARCHITECTURE.md

plugin: Add dumpstate.go to ARCHITECTURE.md

---

pkg/plugin/plugin.go
pkg/plugin/run.go
pkg/plugin/state.go

Per the commit message:
> Ran into this with free tier VMs in production, which are bounded to exactly 1 CPU and 1 GB memory. The autoscaler-agent (validly) sends a resource request to the scheduler plugin which wasn't a multiple of the compute unit (because it can only be 1 CPU + 1 GB).
> 
> This commit allows the plugin to recognize that some requests that aren't a multiple of the compute unit are still valid if it's not possible for the VM's allocation to be a multiple of the compute unit.
> 
> Adds Min and Max fields to podResourceState, to track the information we need to make the determination.
see also: https://neondb.slack.com/archives/C03H1K0PGKH/p1680082384420809?thread_ts=1680080372.280049&cid=C03H1K0PGKH

plugin: Don't reject request if VM is constrained

---

Makefile
pkg/util/buildinfo.go
scripts-common.sh

The number of issues we ran into with the previous approach made it not worthwhile. We may eventually provide more git information at build time, but it's best to keep it simple for the time being.
Resolves #16.

build: Use `git describe` instead of custom git_info

---

pkg/plugin/state.go

This is technically a breaking change to the JSON format exposed by the dump state endpoint, but I'd rather consider this a bugfix and not bump the version from v0.5 -> v0.6 because of it.

plugin: Fix missing podResourceState JSON tags

---

pkg/plugin/watch.go

The context for this error is already provided at the call-site. We don't need to duplicate that in the return itself as well.

plugin/watch: Remove unnecessary error wrap

---

.github/workflows/e2e-test.yaml
Makefile
README.md

AFAICT, some of the e2e flakiness might be partially resulting from system load after cluster start up, due to running vm-builder. I don't _actually_ know, though.
See also:
https://github.com/neondatabase/autoscaling/issues/120#issuecomment-1493405844
**Edit:** At first glance, it seems like this may allow the e2e tests to run faster. More investigation required, probably.

e2e: Build docker images before cluster init

---

pkg/agent/entrypoint.go
pkg/agent/globalstate.go
pkg/agent/runner.go
pkg/agent/watch.go

This change mostly does nothing, but it has a few important impliciations that are worth listing:
1. vmIsOurResponsibility checks vm.Status.Phase == VmRunning, which means that we won't scale VMs that are currently migrating.
2. NeonVM can't do a FieldSelector on Status.NodeName, so we have to do the filtering ourselves. That was already the case with the billing-related code though, so :shrug:
3. A handful of functions deleted, because they aren't necessary if we're watching VMs directly :D
Required by #112.

agent: watch VMs for events, not pods

---

.golangci.yml
pkg/agent/globalstate.go
pkg/agent/runner.go
pkg/plugin/run.go
pkg/plugin/state.go

In order to properly handle migration, agent.Runner now has a way to shut itself down to prevent future requests.

agent, plugin: Re-enable migration under load

---

pkg/util/watch.go

This isn't explicitly required for anything, but it's good to have. In theory, it should provide some efficiency gains when the API server sends us bookmark events instead of saying that the watch is too far out of date.

util/watch: Allow watch bookmarks

---

.github/workflows/e2e-test.yaml

From the commit message:
> This makes some of the handling around the "Get k8s logs and events" step a little more precise. We want to run it on failure-ish so long as the cluster was created.
>
> To do so, this commit makes fetching the logs conditional on cluster creation *not being skipped* (in case cluster creation failed, or was cancelled).
I'm not _actually_ sure that this does what I'm expecting; my knowledge of github workflows is limited :sweat_smile:

e2e: run k8s logs/events step if cluster exists

---

pkg/agent/globalstate.go
pkg/agent/informant.go
pkg/agent/runner.go

This PR also does all the implied simplification from this, mainly:
- Remove vmStateLock
- Merge schedulerInternal into Scheduler (was only used for deadlock
checker, which is no longer needed)
- Hold requestLock for all of updateVMResources
- Simplify internals of updateVMResources in cases where holding
requestLock guarantees the state hasn't changed.
- Remove retries from updateVMResources (no longer used)
- Don't pre-add to Runner's vm.{Cpu,Mem}.Use - no longer required,
because scheduler requests can no longer co-occur with NeonVM requests
**Note:** For ease of review (and maybe future blame?), this PR is split into two commits. The first one _only touches whitespace._ Not yet sure if I should merge without squashing.

agent: Use single request lock for plugin & NeonVM

---

.github/workflows/e2e-test.yaml

Currently it conflicts (ish) with the go tests, so it's hard to tell at a glance in the github UI whether you're looking at e2e tests or unit tests.

rename e2e job: tests -> e2e-tests

---

pkg/agent/informant.go
pkg/agent/runner.go
pkg/informant/consts.go

Without this, it's possible for the informant to allow multiple active agents at the same time - something we generally want to avoid
Note: this builds on #113.

agent/informant: Don't return from /suspend until NeonVM requests finished

---

.github/workflows/e2e-test.yaml

The step fails here for example, because the workflow was cancelled before the cluster was created:
https://github.com/neondatabase/autoscaling/actions/runs/4631573330/jobs/8194589481
Edit: did some futzing around with cancelling, seems to be working as expected.

e2e workflow: Check kind exists before delete cluster

---

pkg/agent/billing.go

This should act as a reasonable-ish fail-safe against the VM store ending early, which would otherwise cause us to continually send the same consumption metrics (and would be incorrect!)
This is an added concern because of #111, which actually does something in the VM store's handlers.

agent/billing: panic if VM store unexpectedly stopped

---

pkg/plugin/state.go

Minor wording changes to bring it in-line with comments on similar fields.

plugin: Fix podResourceState.Buffer comment

---

pkg/util/watch.go

This commit fixes a problem with the relisting code, namely: Because we delete old objects *after* adding new ones, properties that are normally considered unique (e.g. a Pod's name) may be temporarily violated because they are not unique *across time*.
Required for the correctness of the API added in #135.

util/watch: Delete old objects before adding new ones

---

neonvm/apis/neonvm/v1/virtualmachine_webhook.go
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachine_controller_test.go
neonvm/runner/main.go
neonvm/tools/vxlan/controller/main.go

Ref: https://github.com/neondatabase/autoscaling/pull/138#issuecomment-1500676465`
Will add to .git-blame-ignore-revs after merging.

neonvm: use errors.New for unformatted errors

---

pkg/agent/globalstate.go
pkg/agent/runner.go
pkg/agent/sched.go
pkg/api/types.go
pkg/plugin/dumpstate.go
pkg/plugin/plugin.go
pkg/plugin/state.go
pkg/plugin/watch.go
pkg/util/namespacedname.go
pkg/util/namespacedname_test.go

Having an `api.PodName`-equivalent available in util is required for #135. This PR bundles that with some cleanup of the name itself, which I'd been wanting to do for a while.
More justification from the 1st commit message:
> Defining this functionality in pkg/api means it can't be used in pkg/util, because api depends on util. https://github.com/neondatabase/autoscaling/pull/135 requires it in util.
>
> It's also worth making the name more generic, because it's not just pods that we want to handle namespaced names for.
Plan is to add the second commit to .git-blame-ignore-revs after merging.
---
**Suggestion for reviewing**: I'd probably just look at the first commit. The second _does_ have a couple changes that aren't just search-and-replace, but those are the actual deletion of …

Add util.NamespacedName to replace api.PodName

---

pkg/agent/globalstate.go
pkg/api/vminfo.go
pkg/plugin/plugin.go
pkg/plugin/state.go
pkg/plugin/trans.go
pkg/plugin/watch.go
tests/e2e/autoscaling/00-create-vm.yaml
vm-deploy.yaml

Adds the `autoscaling.neon.tech/enabled` label and requires that it's present for the autoscaler-agent to run.

Require label for autoscaling to be enabled

---

.github/workflows/e2e-test.yaml

I suspect `--skip-delete` flag could be the cause of `vm-migration` test flakiness (https://github.com/neondatabase/autoscaling/issues/120).
`--skip-delete` prevents namespaces (with pods) from being deleted after the test, so it means for the second test (`vm-migration`) we have a pod from the first test (`autoscaling`).

e2e tests: do not skip cleanup

---

pkg/agent/globalstate.go

Follow-up from #111 that I missed there, noticed from @tychoish pointing it out in #154.

agent: fix runner log prefix

---

pkg/agent/informant.go
pkg/agent/runner.go
pkg/api/vminfo.go
pkg/api/vminfo_test.go

The reason this is useful is because `VmInfo` contains a k8s `resource.Quantity`, and the default formatting shows all the fields (instead of the more useful pretty-printing that it _could_ do). Basically: it makes the logs cleaner.

api: Use better formatting for VmInfo

---

neonvm/tools/vm-builder-generic/main.go
neonvm/tools/vm-builder/main.go

Initially running vm-builder can take a while, and it's often not clear that it's actually doing anything. Showing output by default should provide more observability there.

neonvm/vm-builder: Add --quiet, default off (now shows build output)

---

pkg/plugin/plugin.go
pkg/plugin/watch.go

ref https://github.com/neondatabase/autoscaling/pull/128#discussion_r1163920964
Been meaning to do this for a while, but hadn't gotten around to it.

plugin: Use event queue for pod/VM events

---

neonvm/apis/neonvm/v1/virtualmachine_webhook.go

Noticed it while opening #146. This makes the PRs conflict, but oh well.

neonvm: deduplicate immutable field checks

---

.github/workflows/e2e-test.yaml

Currently because our git checkout is shallow, running `git describe` fails because there's no tags. It'd be good to have "proper" git info in our e2e builds - this does require a non-shallow clone though, AFAICT.

fix GIT_INFO in CI

---

pkg/api/vminfo.go
vm-deploy.yaml

This commit changes the "enabled" state from
autoscaler/testing-only-always-migrate: "*"
(where '*' stands in for any string, possibly empty) to
autoscaling.neon.tech/testing-only-always-migrate: "true"
This matches the semantics for the "enabled" label, added by https://github.com/neondatabase/autoscaling/pull/38.

api: Update "testing-only-always-migrate" label

---

pkg/agent/watch.go
pkg/api/vminfo.go
pkg/plugin/dumpstate.go
pkg/plugin/plugin.go
pkg/plugin/state.go
pkg/plugin/watch.go
pkg/util/namespacedname.go
pkg/util/namespacedname_test.go
pkg/util/watch.go

Quoting the comment that marked this as a todo:
> K8s uses '/' as its separator. We currently use this for backwards-compatibility, but we should change to '/'. That change will involve fixing the many places where we create strings with %s:%s instead of %s/%s as well; those should just use NamespacedName directly.
So that should hopefully explain why this change is good, and what's actually going on here.
Planning to merge both commits separately, not squash.

Switch to '/' for namespace/name separator, not ':'

---

deploy/autoscaler-agent.yaml
pkg/agent/config.go
pkg/agent/globalstate.go
pkg/agent/informant.go
pkg/agent/prommetrics.go

Builds on #92. Should allow things like this to be detected via metrics: https://neondb.slack.com/archives/C03H1K0PGKH/p1681461362196019?thread_ts=1681459030.472469&cid=C03H1K0PGKH

agent: Add "unhealthy vm-informants" metric

---

neonvm/tools/vm-builder-generic/main.go
neonvm/tools/vm-builder/main.go

This PR fixes #156
tested with different combinations:
```
ENTRYPOINT ["entry1", "entry2", "entry3"]
CMD ["cmd1", "cmd2", "cmd3"]
```
part of generated `vmstart` script:
```bash
if /neonvm/bin/test -f /neonvm/runtime/command.sh; then
/neonvm/bin/cat /neonvm/runtime/command.sh >>/neonvm/bin/vmstarter.sh
else
/neonvm/bin/echo -n 'entry1 entry2 entry3' >>/neonvm/bin/vmstarter.sh
fi
echo -n ' ' >>/neonvm/bin/vmstarter.sh
if /neonvm/bin/test -f /neonvm/runtime/args.sh; then
/neonvm/bin/cat /neonvm/runtime/args.sh >>/neonvm/bin/vmstarter.sh
else
/neonvm/bin/echo 'cmd1 cmd2 cmd3' >>/neonvm/bin/vmstarter.sh
fi
```
```
ENTRYPOINT ["entry1", "entry2", "entry3"]
CMD []
```
part of generated `vmstart` script:
```bash
if /neonvm/bin/test -f /neonvm/runtime/command.sh; then
/neonvm/bin/cat …
```

neonvm: go template fix for ENTRYPOINT and CMD strings

---

pkg/agent/dumpstate.go
pkg/agent/runner.go
pkg/plugin/dumpstate.go
pkg/plugin/watch.go
pkg/util/promserver.go

Noticed an instance in the logs, used ripgrep to locate many occurrences:
rg --multiline '(klog|logger)\.(Info|Warning|Error)f\("[^"]*%w'
Realistically this should also be in CI, but that can be a follow-up.

Fix logs with %w

---

pkg/agent/watch.go

main currently has a bunch of autoscaler-agent errors like "Received updated event for pod example-lngx5 that isn't present". Those happen because watch events from VMs that don't involve the agent's node are still attempted, so this PR should fix that.

agent: Don't handle VM updates if not on its node

---

Makefile

ref https://github.com/neondatabase/autoscaling/pull/172#discussion_r1167967559
I couldn't replicate the issue with `make manifests` not working, so not too sure what's going on.
~~cc @nikitakalyanov would be good to include the error message this fixes into the final commit.~~ Nevermind, re-read the comment.

make: fix manifests paths

---

pkg/api/vminfo.go

This commit does a couple things:
1. Changes api.scalingBounds so that all fields are not pointers
2. Changes the wording on error messages to "must be set to non-zero" to cover both "not set" and "set to zero"
3. Use github.com/tychoish/fun/erc.Collector to allow >1 error
ref https://github.com/neondatabase/autoscaling/pull/181#discussion_r1167624867

api/vminfo: Rework scaling bounds/validation

---

pkg/agent/informant.go
pkg/agent/runner.go

Currently failed requests to the scheduler plugin vs vm-informant have different labels when the (*http.Request).Do() call fails. This change unifies them to the same value: "[error doing request]"
Showcase of current metrics, for comparison:

metrics: unify failed http request label

---

pkg/agent/prommetrics.go
pkg/agent/runner.go

Typically, panics would be visible in other ways, like K8s events. But because the autoscaler-agent isolates panics just to the threads handling a single VM, these can go unnoticed unless we do something about it.

agent: Add runner panics metrics

---

.github/workflows/lint.yml

ref https://github.com/neondatabase/autoscaling/pull/188#issuecomment-1510896020
Expecting this to fail for now, until #188 is merged.

lint: Check that `make manifests` has no changes

---

.github/workflows/lint.yml

There are sometimes non-Go files that affect linting (e.g., changes to the linting workflow itself, as in #201) and realistically the longest CI job is the e2e tests, so being efficient about linting isn't as significant.

lint: Always run golangci-lint

---

.github/workflows/lint.yml

Currently we have ~50k lines of tar extraction errors with "File exists" when the golangi-lint-action runs. There doesn't seem to be a clean way around this, other than disabling its cache.
See also: https://github.com/golangci/golangci-lint-action/issues/244#issuecomment-1052190775
Example of an offending run: https://github.com/neondatabase/autoscaling/actions/runs/4740610494/jobs/8416629913

lint: Don't use golangci cache

---

.github/workflows/e2e-test.yaml

Currently there's no good way to debug a crash if the pod's logs on restart don't show what went wrong. Ran into this while working on #203.

e2e: show previous logs if restarted

---

deploy/autoscale-scheduler.yaml

Removes this comment:
> note: this ConfigMap is not meant to be mounted. For better responsiveness, the scheduler listens for updates on the ConfigMap object directly.
The ConfigMap watcher was removed in #87; currently the plugin *does* actually mount the ConfigMap.

deploy/sched: Remove out-of-date comment

---

.github/workflows/e2e-test.yaml

Instead of supporting a list of paths that could affect autoscaling/neonvm, let's just always run e2e tests on push (merge) to the main

Always run e2e tests on push to the main

---

.github/workflows/e2e-test.yaml
Makefile

Just a quality-of-life improvement. When developing locally, I often only want to rebuild a single image, but changing any file invalidates the docker caches for all images, so `make docker-build` does a lot of work that I don't actually care about.
This PR also changes the `docker-build` target so that it no longer has a dependency on `build`, which *seems* like it's ok, AFAICT.

make: Add targets to build individual docker images

---

ARCHITECTURE.md
cmd/vm-informant/main.go
pkg/agent/informant.go
pkg/api/VERSIONING.md
pkg/api/types.go
pkg/informant/agent.go
pkg/informant/endpoints.go

This should give a somewhat hacky way of getting around the "informant doesn't retry" issues we've had a couple of in production, by offloading the retry logic into making the autoscaler-agent reconnect when the informant no longer recognizes it.
Resolves #163, #200.

agent, informant: Add agent -> informant health checks

---

pkg/agent/informant.go
pkg/agent/runner.go

Correct usage requires accessing a private field, so the method shouldn't be public.
ref https://github.com/neondatabase/autoscaling/pull/203#discussion_r1174293331
Will merge this after #203 to avoid complicating that PR.

agent/informant: Make (*InformantServer).Valid() private

---

pkg/informant/endpoints.go

Without this, got the following in the logs, while doing other cgroup-related testing.
```
I0423 21:58:10.558353     142 main.go:165] Running vm-informant with args [-cgroup neon-test]
I0423 21:58:10.669739    4505 main.go:41] buildInfo.GitInfo:   v0.6.0-30-g3e7297f
I0423 21:58:10.670666    4505 main.go:42] buildInfo.GoVersion: go1.20.3
I0423 21:58:10.671451    4505 main.go:95] Selected cgroup "neon-test", starting handler with config {OOMBufferBytes:209715200 MemoryHighBufferBytes:104857600 MaxUpscaleWaitMillis:20}
I0423 21:58:10.673234    4505 cgroupmanager.go:124] Initial memory.events: {Low:0 High:15140 Max:0 OOM:0 OOMKill:0}
I0423 21:58:10.674406    4505 main.go:111] No postgres file cache selected
I0423 21:58:10.676361    4505 cgroup.go:74] Total memory available for cgroup is …
```

informant: Fix panic on HealthCheck for missing agent

---

Makefile

Currently bin/vm-builder is required instead, but the pg14-disk-test stuff doesn't use that.

make: Require bin/vm-builder-generic for docker-build-pg14-disk-test

---

pkg/agent/informant.go

Without this the autoscaler-agent slowly leaks goroutines each time a new VM is handled.
Fixes #37, fixes #196.

agent/informant: Stop informant server when context canceled

---

pkg/informant/cgroup.go

The comment above OOMBufferBytes wasn't updated when the file cache handling was implemented, back in https://github.com/neondatabase/autoscaling/pull/47.

informant: Fix CgroupConfig.OOMBufferBytes docs

---

.gitattributes

Further reading:
* https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
* https://git-scm.com/docs/gitattributes
Noticed while reviewing #172. With #191, CRDs shouldn't generally need human review, I think. Curious to hear other opinions on this.

Add .gitattributes, mark CRDs as generated

---

pkg/agent/informant.go

Spotted in CI while looking at an unrelated failure. Link:
https://github.com/neondatabase/autoscaling/actions/runs/4801094505/jobs/8544531968#step:16:962

agent/informant: Fix log for /unregister response

---

pkg/agent/informant.go

Spotted in CI while looking at an unrelated failure. Link:
https://github.com/neondatabase/autoscaling/actions/runs/4801094505/jobs/8544531968#step:16:955

agent/informant: Fix inverted 'ErrServerClosed' check

---

pkg/plugin/plugin.go

"The pod will resources" -> "The pod will get resources"

plugin: Fix missing word in Filter comment

---

.github/workflows/e2e-test.yaml

Sometimes it gets stuck, and won't get killed for a very long time.

e2e: use 5m timeout on actions/setup-go

---

neonvm/config/default-vxlan/multus/daemonset_patch.yaml
neonvm/config/default-vxlan/multus/kustomization.yaml

Ran into an issue because of this while deploying to dev-eu-central-1-alpha, because there's currently a graviton node there. Manually fixed it there with `nodeSelector: { "kubernetes.io/arch": "amd64" }` — in this PR, I've instead copied the node affinity rules from the vxlan daemonset.

neonvm/multus: Add node affinity to kube-multus-ds DaemonSet

---

neonvm/Dockerfile
neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachinemigration_controller.go

The annotation is based on the value of Spec.Guest.*.Use, not the status, because that's what the rest of the autoscaling system uses to make decisions with.
To observe this annotation changing live, you can use:
kubectl get pod -w -o jsonpath='{.metadata.name}{": "}{.metadata.annotations.vm\\.neon\\.tech/usage}{"\n"}'
(different shells may handle the backslashes differently; the argument passed to kubectl should have single backslashes, like vm\\.neon\\.tech)
This feature is probably the easiest path towards patching cluster-autoscaler to work with our VMs - it avoids needing to pass through an extra neonvm client everywhere.
~~This PR currently semantically conflicts with #172 and `VirtualMachineUsage.CPU` should be updated after that merges.~~

neonvm: Add current usage annotation to runner Pod

---

deploy/autoscale-scheduler.yaml

Just discovered `priorityClassName: system-cluster-critical` while reading about cluster-autoscaler:
> It is possible to run a customized deployment of Cluster Autoscaler on worker nodes, but extra care needs to be taken to ensure that Cluster Autoscaler remains up and running. Users can put it into kube-system namespace (Cluster Autoscaler doesn't scale down node with non-mirrored kube-system pods running on them) and **set a priorityClassName: system-cluster-critical property on your pod spec (to prevent your pod from being evicted).**
(emphasis added)
AFAIK we haven't yet run into any issues because of this, but maybe worthwhile to have? The scheduler handles restarts just fine, so it may also be ok if evicted, as long as a new pod comes up quickly.

deploy/sched: Mark scheduler as system-cluster-critical

---

.github/workflows/release.yaml
Makefile
deploy/autoscale-scheduler.yaml

Changes from "kube-autoscale-scheduler" to "autoscale-scheduler".
Also updates the container name from "kube-second-scheduler" to "autoscale-scheduler".

change dev scheduler image to match release

---

neonvm/runner/main.go

Fixes an issue that prevents reconciling new VMs (and thus breaks autoscaling) with v0.7.0 and cgroups v1 (whch staging has).
In cgroups v1, the files for each controller are instead under that controller's mount point, rather the "unified" (i.e. v2) model where they're bundled into a single cgroup's files.
As a concrete example, the CPU-related files (like `cpu.cfs_quota_us`) for some cgroup "foobar" would be found under `/sys/fs/cgroup/cpu/foobar` instead of `/sys/fs/cgroup/foobar`.
---
I've already tested this on staging by building + deploying just the NeonVM controller + runner myself (as `sharnoff/neonvm-{controller,runner}:v0.7.1-alpha1`) and it does fix the problem. Going to merge w/o review so that staging doesn't stay broken.
Missed this during review of #172.

neonvm/runner: Fix cgroup v1 path

---

pkg/agent/billing.go
pkg/billing/model.go

This was part of #172 that I'd mistakenly suggested. It turns out the control plane actually cannot accept fractional values for billing values.

billing: Revert value to int, not float

---

cmd/autoscale-scheduler/main.go

Copy-pasting from the added comment:
> Don't output the full usage whenever any error occurs (otherwise, startup errors get drowned out by many pages of scheduler command flags)
Worth noting that `ExecuteContext` will actually always return an error (because the scheduler always returns an error), so this will also happen on a "successful" exit, once those are possible.
Haven't _actually_ tested this (because #55), although it _should_ be possible to observe the change (due to #250).

sched: Don't output command help on error

---

Makefile

Ran into this issue here: https://github.com/neondatabase/neon/actions/runs/4949327913/jobs/8853330006#step:5:11
```
./vm-builder: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./vm-builder)
```
Go is only dynamically linked when cgo is enabled, so we _should_ be able to fix this by disabling cgo :)

make: Build vm-builder w/o cgo - avoid dynamic linking

---

pkg/plugin/watch.go

```diff
diff --git a/pkg/plugin/watch.go b/pkg/plugin/watch.go
index 1813046..d2d517a 100644
--- a/pkg/plugin/watch.go
+++ b/pkg/plugin/watch.go
@@ -19,7 +19,7 @@ import (
)
// watchPodEvents continuously tracks a handful of Pod-related events that we care about. These
-// events are: non-VM pod deletion, VM deletion, and VMs that disable scaling.
+// events are non-VM pod deletion and VM deletion.
//
// This method starts its own goroutine, and guarantees that we have started listening for FUTURE
// events once it returns (unless it returns error).
```
Since #128, VM disabled scaling events are handled by `watchVMEvents`, not `watchPodEvents`.

plugin/watch: Fix comment description of pod events

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/runner/main.go
pkg/agent/billing.go

In general, resource.Quantity's AsApproximateFloat64() method is less precise than if we do the conversion ourselves. This PR adds a new method to do that, and switches to it in all our usage.
---
Originally spotted this in the logs. As a reproduction, take for example, this program:
```go
package main
import (
"fmt"
"k8s.io/apimachinery/pkg/api/resource"
)
func main() {
milli := int64(27278)
q := resource.NewMilliQuantity(milli, resource.BinarySI)
fmt.Println("resource:", q.AsApproximateFloat64())
f := float64(milli) / 1000
fmt.Println("float:", f)
}
```
With current K8s versions, outputs:
```
resource: 27.278000000000002
float: 27.278
```
(Go playground link: https://go.dev/play/p/S7gW9hxgE7C)

neonvm/api: Add (MilliCPU).AsFloat64()

---

neonvm/tools/vm-builder/main.go

Previous to this, there was no way to enable the vm-informant's file cache integration in `vm-builder` (needed to use `vm-builder-generic` instead).
Resolves #264.

neonvm/vm-builder: Add --enable-file-cache flag (default: off)

---

pkg/informant/cgroup.go
pkg/informant/cgroupmanager.go
pkg/informant/consts.go
pkg/informant/endpoints.go

Relevant context:
* https://github.com/neondatabase/autoscaling/issues/44#issuecomment-1522487217
* https://neondb.slack.com/archives/C03TN5G758R/p1682450906524189?thread_ts=1682410239.294789&cid=C03TN5G758R
Fixes #44 - tested locally with `allocate-loop`.
Bikeshed-able parameters are here:
https://github.com/neondatabase/autoscaling/blob/26e424006172167948ff6244bf60622b59bbb3c1/pkg/informant/consts.go#L30-L39

informant: Try to avoid cgroup memory.high throttling

---

pkg/plugin/run.go
pkg/plugin/state.go

Currently, all of the extension point handlers (e.g. Filter, Score, etc) already print the node on every log line. This allows us to use regex text filtering after-the-fact to restrict logs to a single node, while still including resource handlers.
(in particular, this fixes the "node" selector not fully working [here](https://neonprod.grafana.net/d/cc4f137c-f2fd-4e18-a00a-c92234e3b33a/neon-logs-autoscaling?orgId=1))

plugin: Print node when handling resource request

---

pkg/agent/entrypoint.go

Maybe not *strictly* a typo. Should have been changed in #111 (along with the rest of the change from podEvents -> vmEvents), but oh well.

agent: Fix stale comment: podEvents -> vmEvents

---

pkg/agent/runner.go

Without this, we get log messages on Runner startup like:
Got initial scheduler pod kube-system/autoscale-scheduler-5989d49744-g7tb6 ...
...
Updating scheduler to pod kube-system/autoscale-scheduler-5989d49744-g7tb6 ...
This can be confusing! Let's be less confusing.

agent/runner: Deduplicate initial scheduler info logs 

---

pkg/plugin/watch.go
pkg/util/k8s.go

Should fix an issue that @cicdteam ran into while testing migrations, where old runner pods were marked as "completed" but not deleted, and eventually took up all resources in the scheduler.

plugin: Handle completed pods as if deleted

---

pkg/agent/globalstate.go
pkg/agent/prommetrics.go
pkg/agent/runner.go

This doesn't directly fix any individual bug, but it should lessen the impact of some behaviors we're currently seeing.
The bulk of this PR is adding a new function, `(*agentState).TriggerRestartIfNecessary`. It is called each time the Runner exits, and queues restarting the Runner if it failed (from panic or other fatal error). If the Runner was long-running, it's immediately restarted. If it has not been up for long, it is restarted after a random delay of 5-10s.
This PR also:
* Changes `podStatusDump` to have a record of previous "end states" (time, error, why it exited)
* Adds a metric `autoscaling_agent_runner_starts`
* Adds a metric `autoscaling_agent_runner_restarts`

agent: Restart panicked/errored runners (+metrics)

---

pkg/agent/globalstate.go
pkg/agent/prommetrics.go
pkg/agent/runner.go

Builds on #273. This PR adds two new metrics:
1. `autoscaling_agent_runner_fatal_errors_total`
2. `autoscaling_errored_vms_runners_current`
We already have metrics for tracking when Runners panic, or the current number of Runners that are stopped because they panicked. These two do the same, but for cases where the Runner fails because of a fatal error during startup, rather than panicking.

agent/metrics: Track Runner fatal errors

---

deploy/autoscale-scheduler.yaml
deploy/autoscaler-agent.yaml
deploy/vmscrape.yaml

This is what we already have deployed in staging + production, taken from the `staging` and `prod` branches.
Edit: Merging this to accurately reflect the current state. Happy to discuss changes in a follow-up (e.g. maybe we should scrape every 30s or 1min, not 10s)

deploy: Add ports, VMPodScrape for metrics

---

neonvm/tools/vm-builder-generic/main.go
neonvm/tools/vm-builder/main.go

Supersedes #258. This should offer a more complete solution, hopefully should ease some concerns.
Ran into an issue on this PR: https://github.com/neondatabase/neon/pull/4155
[The logs](https://github.com/neondatabase/cloud/actions/runs/4961923787/jobs/8879661707#step:45:754) had things like this:
```
/neonvm/bin/vmstarter.sh: line 6: /usr/local/bin/compute_ctl-D: not found
```
This is because the control plane's first argument to compute_ctl is '-D ', and it was getting merged with the path to the binary.
(sources: [setting args](https://github.com/neondatabase/cloud/blob/3800327f76870b21f1fa2e7e8a6f66ab359d9be0/goapp/internal/operationsv2/provisioner_k8s.go#L478), [generating args](https://github.com/neondatabase/cloud/blob/3800327f76870b21f1fa2e7e8a6f66ab359d9be0/goapp/internal/operatio …

neonvm/vm-builder: Fix/improve command passthrough

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
pkg/agent/billing.go
pkg/agent/globalstate.go

To do this, adds the `(VirtualMachineStatus).IsAlive()` method, so that the autoscaler-agent doesn't need to be kept up-to-date with changes in NeonVM.
Also adds a call to IsAlive() in the agent's `vmIsOurResponsibility` check, so that future changes to NeonVM don't require modification there.
This requires updating #256 after merging, but should mean that changes are localized to `IsAlive`, instead of updating the autoscaler-agent as well.

agent/billing: Don't count VMs that aren't running

---

pkg/agent/schedwatch/event.go
pkg/agent/schedwatch/watch.go

I couldn't get the "agents not picking up on a new scheduler" issue to reproduce locally, and we didn't have good enough logs to tell what was happening. So this PR aims to fix those logs.
There's also some improved handling relating to checking whether pods have IP addresses (honestly don't know whether it's possible for a pod to be "ready" without an IP address, but it's reasonable enough to have those checks there). And the check for whether the pod's name changed is removed — there's no reasonable circumstance where that matters.
Commit messages should probably be improved before merging. I'll probably merge with rebase, because the commits here are kind of separate.
**NB: This PR builds on #289 and must not be merged before that**

agent/schedwatch: Improve the logging situtation

---

neonvm/tools/vm-builder/main.go

Moves the 'cgexec ...' entrypoint into TemplatesContext, so that it actually gets called.
~~NB: As written, this currently doesn't work with vm-postgres:15-bullseye. More work necessary to fix that.~~
Have tested, issue is fixed.
Extracted from #263, to not block that.

neonvm/vm-builder: Fix cgexec being ignored

---

neonvm/controllers/virtualmachine_controller.go

Currently "runner" makes it hard to understand the log output of other systems (e.g. k8s events) interacting with NeonVM. IMO renaming should help make things more understandable to others.
NB: this may require updating some Grafana dashboards.

neonvm: Rename 'runner' container to 'neonvm-runner'

---

.github/workflows/release.yaml

Should have been included in #285, but missed it there.
Realistically we should be using `make render-release` here, but getting the environment variables right is hard.

release workflow: Fix kustomize render step

---

pkg/util/time.go
pkg/util/watch.go

Precursor to #297. Should also set up (finally) resolving #35 nicely.

util: Move TimeRange into its own time.go

---

deploy/agent/config_map.yaml

Without using '|', the data in the string will be collapsed and line-wrapped by kustomize, making it very difficult to make changes to the ConfigMap in the final manifest(s).
This PR also includes an intermediate commit to handle the indenting, so that it can be put in .git-blame-ignore-revs. (**This PR must be merged via rebase.**)

deploy/agent: use '|' for configmap data, not single-quote

---

pkg/agent/informant.go

This commit contains both (a) a fix so that we're not logging %!s(\<nil\>) and (b) minor formatting improvements. The end result is that our logs should go from:
Informant server exiting with retry: false, err: %!s(<nil>)
to:
Informant server exiting with: retry=false, err=nil

agent/informant: Fix informant server exit logs

---

pkg/agent/watch.go

Noticed in the logs here: https://github.com/neondatabase/autoscaling/actions/runs/5126882656/jobs/9221907427?pr=306#step:16:552

agent: Fix vmEvent formatting typo

---

pkg/agent/entrypoint.go
pkg/agent/watch.go

Pre-req of a later fix in util/watch (#305). This change is similar in spirit to #160 (using a queue in the plugin), arising from a similar need: It's hard to avoid deadlocks without using a queue.

agent: Use queue for global vmEvents, not channel

---

pkg/util/watch/watch.go

Not 100% sure, but this *may* be the cause of an issue affecting prod that causes preexisting VMs to be ignored by pkg/agent/billing until there's an event for them. (the theory is that the index is added before the deferred adds are processed)
**Edit:** After thinking about it some more, realized that actually the issue is _guaranteed_ to happen because of this, without #304
**Builds on #304, must not be merged before that PR.**
We may also just want to get rid of `InitModeDefer` — it's nice in theory, but the autoscaler-agent's global VM event watching is the only place that uses it, and after #304 it's not _actually_ necessary. `InitModeDefer` sounds like good flexibility in theory, but in practice it's probably a code smell.

util/watch: Fix racy behavior with InitModeDefer

---

pkg/agent/runner.go

Without this, future event publishing blocks, leaving *all* Runners stuck on an old scheduler (i.e. unable to connect to a new one).
AFAICT this commit fixes the "failure on scheduler restart" bug currently affecting prod.

agent: Stop SchedulerWatch when Runner finishes

---

pkg/agent/entrypoint.go
pkg/agent/schedwatch/watch.go
pkg/agent/watch.go
pkg/plugin/plugin.go
pkg/plugin/watch.go
pkg/util/watch/metrics.go
pkg/util/watch/watch.go

Adds metrics to `util/watch.Watch` calls, for better observability on deeply internal systems. These are aggregated per _binary_, so the new metrics are:
* `$PREFIX_client_calls_total`
* `$PREFIX_relist_requests_total`
* `$PREFIX_events_total`
* `$PREFIX_errors_total`
* `$PREFIX_alive_current`
* `$PREFIX_failing_current`
where `$PREFIX` is either `autoscaling_agent_watchers` or `autoscaling_plugin_watchers`.
A fuller description of each metric can be found in `pkg/util/watch/metrics.go`.
All metrics have the `watcher_instance` label, which associates the metrics with an individual call to `watch.Watch` .

util/watch: Add metrics

---

pkg/plugin/plugin.go

Previous to this commit, we wouldn't actually unreserve any VM pods.
An intermediate commit for indenting is split out from the main change, so that we can preserve some of the original blame with .git-blame-ignore-revs.
**NB: This PR should be merged by rebase, with the first commit added to .git-blame-ignore-revs**

plugin: Fix Unreserve condition

---

deploy/vmscrape.yaml

10 seconds is too often, for little gain, at the expense of shoving a bunch more data through VictoriaMetrics.
Realistically it's not *that* bad, but still worth changing.

deploy: Change metrics scrape interval 10s -> 60s

---

pkg/util/watch/metrics.go

Without this, we'll get "no data" in grafana until something starts failing. It's better to have "yes data, and nothing's failing".

util/watch: Set failingCurrent to zero so it shows up

---

ARCHITECTURE.md
cmd/vm-informant/main.go
pkg/agent/informant.go
pkg/api/VERSIONING.md
pkg/api/types.go
pkg/informant/agent.go
pkg/informant/endpoints.go

Not sure if this is the exact right way to do it. It seems protocol version agnostic.

Include AgentID in /downscale and /upscale responses

---

pkg/agent/billing/billing.go

AFAICT the status should be more accurate, because the fields in .spec are more like the "desired" state, whereas the status is more like the "actual" state.
I don't _think_ we've had any issues because of this, but it'd be good to fix it before it becomes an issue.

agent/billing: Use NeonVM .status.cpus, not .spec.guest.cpus.use

---

build/autoscale-scheduler/Dockerfile
build/autoscaler-agent/Dockerfile
build/vm-informant/Dockerfile

The general idea of the change here is that instead of just blanket including `pkg/` and `cmd/`, we should only copy over the specific packages that are actually being used.
This will let us do a better job using the docker cache. Without it, changes in e.g. cmd/autoscale-scheduler/main.go will cause the cache for the autoscaler-agent to be invalidated, meaning `make docker-build` will recompile it unnecessarily.

build: Be more precise about COPYing go files

---

pkg/plugin/state.go

This should have been handled in #260, but it was missed there.
~~**NB:** This PR builds on #323, and must not be merged before it.~~

plugin: Fix readClusterState handling of completed pods

---

neonvm/controllers/virtualmachinemigration_controller.go

Part of #333, adds an owner reference for the migration to the _source_ runner pod, so that it's possible to check whether a pod is involved in a migration just by checking it (without e.g. cross-referencing with the VM phase).
**NB:** This PR builds on #256, and must not be merged before it.

neonvm/controller: Set migration source ownerref

---

pkg/plugin/run.go

Currently preventing any `agent-handler` logs from appearing on staging, with the logs ending a few hours after it was released at ~150kb / line.
Requires a backport onto v0.10.0 to hotfix before it gets to prod

plugin: Fix agent-handler log keys explosion

---

neonvm/config/common/controller/manager.yaml

To avoid OOM and execution slowdown when reconcile thousands of VMs

VM controller resource request updated to support thousands of VMs

---

pkg/plugin/state.go

ref https://neondb.slack.com/archives/C03F5SM1N02/p1687222026730729?thread_ts=1687205072.505319&cid=C03F5SM1N02
Kind of a silly bug, that really could have been caught by tests, but oh well.
Given it's currently impacting prod, I'll backport this onto v0.10.1, so that (a) we're not waiting on cutting tomorrow's release to fix it, and (b) we're not tying other things into this.

plugin: Fix missing `continue` when skipping completed pods

---

pkg/agent/informant.go

The health checks are meant to serve as a means of restablishing connections if something goes wrong, so that we can have naive "all errors are fatal" approach in the informant (which allows it to be simpler - a good thing).
However, in prod I saw a new VM (so: recent informant, that supports health checks) stop communicating, and narrowed it down to a failure to "/resume" the autoscaler-agent. When that happened, neither component sent any more requests because it was waiting for the other. [In the agent's logs](https://neonprod.grafana.net/explore?left=%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bcontainer%3D%5C%22autoscaler-agent%5C%22,%20cluster …

agent/informant: Do health checks even when suspended

---

pkg/plugin/plugin.go

This lets us match the actual names of the Go methods, which will help for things like PostFilter.
**NB: Pre-req for #346.**

plugin: Capitalize pluginCalls metric labels

---

pkg/plugin/plugin.go
pkg/plugin/prommetrics.go

This should allow us to add alerts for cases where the scheduler plugin is misbehaving, allowing us to detect issues before they escalate into a larger outage.
This adds two new metrics to the scheduler:
* `autoscaling_plugin_filter_cycle_successes_total`
* `autoscaling_plugin_filter_cycle_rejections_total`
**NB: Builds on #345, pre-req for #347**

plugin: Add PostFilter-based "filter cycle" metrics

---

pkg/plugin/plugin.go
pkg/plugin/prommetrics.go

Should allow us to proactively catch e.g. Reserve failures and turn them into alerts before they become a bigger issue.
This adds one new metric to the scheduler:
* `autoscaling_plugin_extension_call_fails_total`
**NB: Builds on #346**

plugin: Add plugin-point method failure metrics

---

.github/workflows/release.yaml

Noticed that whereabouts.yaml was missing while working on releasing v0.11.0 — AFAICT it was extracted from multus-eks.yaml and never added to the release workflow?
Not immediately blocking the release (I just used `make render-release` and took the yaml from there), but would be good to fix.

release workflow: Add whereabouts.yaml asset

---

neonvm/controllers/virtualmachine_controller.go

In particular, we don't want to propagate the annotation kubectl.kubernetes.io/last-applied-configuration to the runner pod, but the preexisting code also modified the VM's labels/annotations, which maybe is not what's desired.
This PR is split off from some commits in #279, because it's actually not related. ref https://github.com/neondatabase/autoscaling/pull/279#issuecomment-1597844234

neonvm/controller: Better label/annotation propagation

---

pkg/agent/prommetrics.go
pkg/agent/runner.go
pkg/api/types.go
pkg/util/arith.go

Broadly, this PR primarily adds metrics that focus on the change in resources -- both "requested" changes (to: scheduler, informant, NeonVM) and "approved" changes (from: scheduler, informant).
The CPU and memory changes are separate metrics. Memory is in units of Mibibytes. Upscaling vs downscaling is represented by the "direction" label, which is either "up" or "down".
There's also the addition of NeonVM request counts and the associated result.
In total, the new metrics are:
* `autoscaling_agent_scheduler_plugin_{requested,approved}_{cpu,mem}_change_total`
* `autoscaling_agent_informant_{requested,approved}_{cpu,mem}_change_total`
* `autoscaling_agent_neonvm_requested_{cpu,mem}_change_total`
* `autoscaling_agent_neonvm_outbound_requests_total`
So, 11 new metrics in total.
---
This PR …

agent: Add scaling metrics

---

pkg/agent/globalstate.go
pkg/agent/prommetrics.go
pkg/agent/watch.go

With upcoming compute pool changes, we're going to end up with a lot of VMs where the informant is unable to start up - because the initial file cache connection will fail until postgres is alive, which only happens once the pooled VM is bound to a particular endpoint.
So on staging, we currently report a lot of "autoscaling stuck" VMs, when in reality these are just part of the pool. Having a separate value for the number of these stuck VMs that are actually running something will ensure our metrics continue to be useful.
And also, in passing this through so that we can make a metric out of it, it's worth storing & logging the endpoint ID, so that the information is more easily available (without having to cross-reference the console DB)

agent: Record endpoints for `Runner`s

---

pkg/plugin/watch.go

This is already being handled by the caller, here:
https://github.com/neondatabase/autoscaling/blob/d574fbbb05d6f949510c70009ae7bfd3f83d73a5/pkg/plugin/plugin.go#L152

plugin/watch: Remove redundant error wrapping

---

pkg/plugin/plugin.go

plugin: Fix comments about where .metrics field is set

---

pkg/informant/filecache.go

Realistically a better solution _should_ be to just connect at startup and keep the connection open, but that's a larger change, and this is at least clearly correct.
ref https://neondb.slack.com/archives/C03H1K0PGKH/p1688139786575229
IMO this should be backported + hotfix released as a single-commit change, so that we can get it out sooner.

informant/filecache: Close DB connections

---

.github/workflows/e2e-test.yaml

We have various sources of flakiness (some avoidable, after fixing bugs, and some unavoidable), and given the success rate of e2e tests, I suspect the default fail-fast behavior is probably using our CI runners less efficiently than if we turned it off.

e2e: Set strategy.fail-fast: false (keep running if other fails)

---

pkg/agent/billing/billing.go
pkg/billing/client.go
pkg/billing/model.go

In order to make this work on the agent's side, idempotency key generation needed to be *somewhat* exposed, so this PR adds the `Enrich` function, which handles the common "filling out the other fields" tasks for each event.
By abstracting this interface, we also remove the need for separate `(*Batch).AddAbsoluteEvent` vs `(*Batch).AddIncrementalEvent` methods, so now we just have a single `(*Batch).Add` method that just calls `Enrich`.

billing, agent/billing: Log IdempotencyKey of events

---

pkg/agent/informant.go
pkg/agent/prommetrics.go

We have it for informant → agent metrics, but not the other way around.

agent/metrics: Add "endpoint" for agent→informant request metrics

---

pkg/agent/runner.go

Basically, because we were recording the change from 'downscaled' to 'target', rather than 'current' to 'target', any time we sent a NeonVM request to downscale, we'd record the change as doing nothing.
**NB: This may be worth backporting?** It's a pretty simple fix, and it's maybe worth it to not have our metrics broken.

agent: Fix NeonVM downscaling not showing up in metrics

---

pkg/plugin/config.go
pkg/plugin/dumpstate.go
pkg/plugin/prommetrics.go
pkg/plugin/state.go

One of the features we're actually sorely missing with our current node-level resource usage metrics is the ability to aggregate them by node group.
Per-node group information, rather than per-cluster is more likely to be a useful signal (because various node groups being over/under provisioned typically won't affect the others).
This PR adds a new config field to set the node group label: `k8sNodeGroupLabel`. For EKS, this label is `eks.amazonaws.com/nodegroup`.

plugin: Include node group in node resource metrics

---

.golangci.yml
deploy/scheduler/config_map.yaml
pkg/plugin/config.go
pkg/plugin/dumpstate.go
pkg/plugin/plugin.go
pkg/plugin/prommetrics.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/plugin/watch.go
pkg/util/buildinfo.go

Like all good things, this PR comes in three parts:
1. If the plugin decides to trigger a migration, it no longer returns a non-nil `PluginResponse.Migrate` if the VirtualMachineMigration already existed.
- This had the potential to cause spurious failures where the autoscaler-agent permanently shuts off communication because _it_ was told that the scheduler is going to migrate it, but actually the migration had already completed.
2. The plugin now automatically cleans up completed migrations.
- To make this work, all migrations now have the `autoscaling.neon.tech/created-by-scheduler` label.
3. The plugin now exposes metrics about migration creation and deletion. These are:
- `autoscaling_plugin_migrations_created_total`
- `autoscaling_plugin_migrations_deleted_total`
- …

plugin: Migration handling reliability improvements

---

pkg/agent/runner.go

Fixes #234. This affects pools, and *should* be fine without it, because the Runner will auto-restart and *should* be ok after that, but it's worth fixing anyways.
~~(In the meantime, I'll validate that #234 will self-resolve after restart; otherwise this fix will block our VM pool improvements)~~
#234 _does_ self-resolve after restart; we should be ok.

agent: Fix Runner panic when scaling bounds decrease

---

deploy/scheduler/config_map.yaml
pkg/plugin/config.go
pkg/plugin/plugin.go
pkg/plugin/state.go
pkg/plugin/trans.go
pkg/plugin/watch.go

Resolves #384. Pre-req ish for #397.
Not yet sure whether this should be merged via rebase, or squashed. These changes all _basically_ need to be grouped together because they're mutually dependent, even though they're logically separate.

plugin: Track all pods, remove 'System' resources, ignore overprovisioning pods

---

neonvm/runner/main.go

I got a "File not found" error when fiddling around, and it was hard
to tell which command it came from. This should make it easier to
pinpoint failures in the future.
In the passing, standardize existing log.Printf() messages to not
include newline at the end. Printf() adds a newline implicitly if you
omit it.

neonvm/runner: Print error messages where errors happen.

---

pkg/plugin/plugin.go

Fixes #409, validated locally, etc. Turns out `pubsub.Queue[...].Iterator()` doesn't actually consume the queue, it just visits everything in it.
Bug was originally introduced by #160, commit 2795b50ab7582dff2fa24442e24db41a01e47d14, but we didn't notice before because of (a) other memory leakage (see #248) and (b) the size of the items in the queue were all small before #399, which started passing through whole K8s `Pod` objects.
**NB: This should be backported onto v0.13.0, or released alongside recent commits as v0.13.1**

plugin: Fix leak by actually consuming queue

---

pkg/plugin/state.go

Noticed this while hunting down #409.

plugin: Fix missing node metrics update during initial load

---

pkg/plugin/plugin.go
pkg/plugin/watch.go

This should make observability for invalid autoscaling annotations / labels much better; previously, this information was only really visible in the logs.
Tested this locally by modifying `vm-deploy.yaml` and it seems to work as expected.
cc @cicdteam for any advice on events here.

plugin: Emit k8s Event on failed ExtractVmInfo

---

pkg/plugin/plugin.go

In combination with #416, it *may* be necessary to have the overprovisioning pods go through our scheduler as well in order to stay evicted. If that's the case, they'll need to go through the normal Filter flow as well so they can be rejected (so cluster-autoscaler can do its thing).

plugin: Handle Filter request in ignored namespaces

---

pkg/plugin/plugin.go
pkg/plugin/prommetrics.go

Without this, our alerting could get messed up by the overprovisioning pods, which are expected to frequently fail certain methods, like Filter.

plugin: Expose "ignored_namespace" label for method call metrics

---

pkg/plugin/state.go
pkg/plugin/trans.go

ref https://neondb.slack.com/archives/C03F5SM1N02/p1689711148704229
This PR should be merged via rebase _and_ backported onto v0.12.2, so that we can try it out in isolation from the changes by #423.

plugin: Fix buffer underflow, include Buffer in more logs

---

pkg/plugin/plugin.go

PR #416 introduced a regression around our handling of completed pods, namely that during Filter calls if we process *all* pods, then we'll still count Failed/Succeeded pods into the node's usage, rather than ignoring them like we do elsewhere.

plugin: Ignore completed pods in Filter

---

pkg/plugin/state.go

Earlier in its life, the plugin used to assume that `Reserved` was always less than or equal to the `Total` resources; this is... no longer true, and hasn't been for a while - although I suspect it hasn't impacted things very much.

plugin: Calculate "remaining reservable" resources via SaturatingSub

---

pkg/plugin/plugin.go

Noticed because of state inconsistencies in prod; `Wait()` also pulls from the queue.
**NB: This should be backported / hotfixed onto v0.13.5.**

plugin: Fix queue event skips

---

pkg/plugin/plugin.go

Some ongoing issues on staging due to inconsistencies between the Filter and Reserve steps are proving hard to debug because there's just a bit too little information available. For example, the Filter step shows the node totals, whereas a failed Reserve step shows the incremental change.

plugin: Standardize+improve plugin method logging

---

pkg/plugin/trans.go

Noticed this because 'Buffer' was high in prod-eu-central-1-gamma after the scheduler restarted, realized it was because a VM was deleted before the autoscaler-agent checked in about it, and the VM's Buffer wasn't appropriately removed from the Node's total.
AFAICT this wasn't actually affecting any scheduling decisions (because Buffer is included in Reserved, and Reserved *is* appropriately unset when a VM is deleted), but it's worth fixing anyways so that our monitoring is cleaner.

plugin: Handle VM 'Buffer' on delete

---

pkg/agent/globalstate.go
pkg/agent/prommetrics.go

With the way that the informant currently works, all pooled VMs are marked as "autoscaling stuck". Because of that, there's the occasional VM that is detected as "autoscaling stuck" *after* it's assigned an endpoint, but before the agent has tried to reconnect to its informant.
If we track the "billed autoscaling stuck" metric with a grace period extending from the time at which the VM was assigned the endpoint, we should have enough wiggle room to make the metrics more consistent.

agent: Improve "billed stuck" metric

---

pkg/agent/billing/billing.go
pkg/util/watch/watch.go

On the `util/watch` side: This adds a new Failing() method that complements the existing Stopped() method, similarly matching the metrics we expose.
On the `agent/billing` side: If the watch is failing, we just pretend that there's no VMs, and log a suitable error.
Realized this needed to be implemented because today we had a [k8s API server switchover](https://neondb.slack.com/archives/C039YKBRZB4/p1690313460648149) in prod-us-west-2-eta, and all the Watch instances separately failed for 1s at different times. If it had been longer (or if relisting took a long time), and we had VMs there, we would have used stale data for our billing events.

util/watch, agent/billing: Don't record events if VM watch is failing

---

neonvm/controllers/virtualmachine_controller.go
neonvm/runner/main.go

This should improve a handful of things. It should fix the cAdvisor metrics issue, because now QEMU will actually be running as part of the container's cgroup (so its CPU/memory usage should be reported correctly), AND it should help with cgroup cleanup, because containerd will take care of that too! :D
Fixes #375, fixes #440.

neonvm/runner: Create QEMU cgroup inside current one

---

.github/ISSUE_TEMPLATE/bug-template.md
.github/ISSUE_TEMPLATE/epic-template.md
.github/ISSUE_TEMPLATE/feature-request-template.md

Noticed we didn't have any, figured we should.
~~Not quite done yet:~~
Requested review from anyone I thought might care about these. Feel free to comment as much or as little as you'd like.
Broadly the templates are adapted from the cloud repo, with some minor rearrangements to structure.

Add github issue templates

---

neonvm/runner/main.go

From linux kernel docs:
```
panic=          [KNL] Kernel behaviour on panic: delay <timeout>
timeout > 0: seconds before rebooting
timeout = 0: wait forever
timeout < 0: reboot immediately
Format: <timeout>
```
adding `panic=-1` to kernel command line should prevent  VM from freezing when the kernel receives a panic event.
resolve #446

add panic=-1 to kernel command line

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/apis/neonvm/v1/zz_generated.deepcopy.go
neonvm/config/common/crd/bases/vm.neon.tech_virtualmachines.yaml
neonvm/controllers/virtualmachine_controller.go

To do this, we add a new field to the VM spec, `ExtraInitContainers`.
In order to make this fully backwards- and forwards-compatible with existing objects (so we don't end up performing a bunch of writes immediately after deploying), the field is set to "omitempty" so that existing VMs will be unchanged.
part of #413, related to https://github.com/neondatabase/cloud/pull/5890. cc @hlinnaka
We won't be able to enable this in the control plane until we release this & bump the control plane's Go dependency, which itself requires bumping all its k8s deps to 1.25. But actually using this is also waiting on removing the VM -> agent connections that @fprasx is working on, so the timing will _probably_ work out so things go through at about the same time.

neonvm: Add user-defined additional InitContainers

---

.github/workflows/e2e-test.yaml

My PR got stuck on the "make deploy" step, and kept running for hours until it was cancelled. That was surely a bug in my PR, but if such bugs happen, there's no need to wait for so long. All these steps finish in < 5 minutes on the CI currently, so these timeouts are quite conservative.

Add timeouts on a few CI workflow steps.

---

go.mod

I'm not sure why making manual changes to "// indirect" dependencies wouldn't be erased by `go mod tidy`, but I guess this works? It's... a little weird TBH, maybe something to do with the replace directives?
cc @bayandin / @tychoish if you have ideas

downgrade k8s.io/apiextensions-apiserver to match others

---

pkg/agent/globalstate.go
pkg/agent/informant.go
pkg/agent/prommetrics.go
pkg/agent/runner.go

... instead of the previous method of calculating them as needed at scrape time.
There's some ongoing issues with metrics collection on staging, maybe this will help with it.
Resolves #198.
~~Haven't tested it or anything, still need to self-review.~~
All the following metrics are removed:
- `autoscaling_errored_vm_runners_current`
- `autoscaling_panicked_vm_runners_current`
- `autoscaling_agent_tracked_vms_current`
- `autoscaling_vms_unsuccessful_communication_with_informant_current`
- `autoscaling_billed_vms_unsuccessful_communication_with_informant_current`
... replaced by:
- `autoscaling_agent_runners_current`
with the previous metrics replaced with combinations of labels on the new one.

agent: Track runner state metrics as it goes

---

pkg/agent/globalstate.go

For some reason, had this in my shell history from 2023-07-26 but nowhere to be found in any local branches. Oof.
This, in combination with some new usage from #459 was causing crash-looping on staging.

agent: Fix endpointAssignedAt for VMs added with endpoint

---

pkg/agent/prommetrics.go

For some of these (e.g. "errored" or "panicked" states), we're not expecting to have many of them, so it's better to explicitly have zero, rather than "no data".

agent/metrics: Initialize runnersCount label pairings to 0

---

neonvm/tools/vm-builder/main.go

The informant did not need these fields because they were assumed by default by the pq go sql driver.
https://neondb.slack.com/archives/C03TN5G758R/p1691694313375769

vm-builder: add additional fields to vm-monitor conn str

---

pkg/agent/globalstate.go

Honestly not sure whether this will fix #470, but hopefully it should.
At the very least, without this PR, we'd definitely have incorrect behavior if a Runner ended with fatal error / panic, but was deleted before restarting. Beyond that, I don't know.

agent/metrics: Fix runner state metrics deletion handling

---

Makefile
neonvm/tools/vm-builder/main.go

This change enables more flexibility rolling out the monitor. We can keep using the monitor during `e2e` tests, while not enabling it for release builds.
This PR also removes cgexec. This functionality will be delegated to `compute_ctl`.

vm-builder: add flag to enable informant/monitor at VM startup and remove cgexec

---

deploy/scheduler/config_map.yaml
pkg/plugin/config.go
pkg/plugin/plugin.go

us-west-2 is currently at ~30-35% cluster-wide utilization, so I'm figuring that #411 should be handled sooner rather than later.
Implemented this after some brainstorming with @fprasx in a call earlier today.
Should resolve #411.

plugin: Penalize underfull nodes during Score

---

deploy/scheduler/config_map.yaml
pkg/plugin/config.go

Missed this while working on #476.

plugin: Fix nodeConfig.ScorePeak JSON name (was scoreMidpoint)

---

pkg/plugin/plugin.go

`scale` is a value between 0 and 1, so we want to multiply by it, instead of dividing by it - otherwise we can end up with scores outside the required bounds.
Logs from staging during the failed deploy earlier:
```
{"level":"info","ts":1692211124.9558136,"logger":"autoscale-scheduler.plugin","caller":"plugin/plugin.go:739","msg":"Scored pod placement for node","method":"Score","node":"ip-10-6-26-248.us-east-2.compute.internal","pod":{"namespace":"default","name":"compute-little-river-47144208-7cffdcb994-s4zp6"},"score":802,"verdict":{"cpu":"5.845 remaining reservable of 7.91 total => fraction=0.26106194690265494, scale=0.08266276517922458 => score=(8.022520361813768 :: 802)","mem":"18 remaining reservable of 29 total => fraction=0.3793103448275862, scale=0.07859078590785908 => …
```

plugin: Fix Score scale usage: mul, not div

---

neonvm/tools/vm-builder/main.go

This may fix a bug where the `postgres` user running compute_ctl cannot start postgres in the neon-postgres cgroup, due to inadequate permissions

vm-builder: add flag to configure uid of neon-postgres cgroup

---

pkg/plugin/config.go
pkg/plugin/dumpstate.go
pkg/plugin/prommetrics.go
pkg/plugin/state.go

It'd be useful for the "node resource usage" dashboard here: https://neonprod.grafana.net/d/c3799a0a-78e2-4cee-90d7-aef35f52858b
(Specifically, I'd like to be able to just look at a particular availability zone, or even just see which AZ each node belongs to, without having to cross-reference k8s.)

plugin/metrics: Add availability zone label to node metrics

---

pkg/agent/dispatcher.go
pkg/agent/informant.go

This addresses a few possible race conditions in the dispatcher. One is related to a read-modify-write operation not being done atomically, and another is related to unsynchronized access to a hash map. See individual commits for more details.

agent: harden dispatcher concurrency

---

pkg/agent/informant.go

The caller of `MonitorHealthCheck` in runner.go was already holding the lock (as the function docs indicated it should), while the function would still attempt to acquire the lock.

agent: remove reentrant attempt to acquire requestLock

---

pkg/agent/informant.go

This should fix false positives for the "stuck VMs" alert on staging. Validated the old & new (fixed) behavior locally.

agent/informant: Update lastSuccessfulInformantComm for monitor comms

---

neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachine_qmp_queries.go
neonvm/controllers/virtualmachinemigration_controller.go

The general idea here is to make all of the functions take only the information they need - so if they only need the address to connect to, don't give them the whole VirtualMachine object. This allows us to remove some functions that had duplicated logic depending on whether there was a VM as input or the IP + port.
To compensate and provide *some* remaining ease of use, there's a new QmpAddr function that gets the address of a VM's QMP listener. Because of how go handles returning multiple values (and passing that along into another function), we can just directly call functions with the output of QmpAddr, like:
```go
QmpQueryMemoryDevices(QmpAddr(vm))
```
even though QmpAddr returns (string, int32) as the (IP, port) combo.

neonvm/controller: Deduplicate QMP query logic

---

pkg/agent/dispatcher.go
pkg/agent/informant.go

This should ensure that if the outer context is cancelled (for example, the informant server shutting down), we (the goroutine doing `disp.run(ctx)`) also shut down.
Not having this previously caused an error where the informant server would shut down, close the websocket, and then because the `disp.run` goroutine was not hooked into the context, it wouldn't be shut down and would try to read from the closed connection.

propagate informant server contexts to dispatcher

---

pkg/agent/dispatcher.go

This also should fix a bug in the handling of InvalidMessage messages from the monitor.
Found while working on part of #492.

agent/dispatcher: Deduplicate unmarshaling

---

deploy/scheduler/config_map.yaml
pkg/plugin/config.go
pkg/plugin/plugin.go

Randomizes scores in the range `[minScore + 1, trueScore]` to "soften" scaling decisions and make the system less fragile. Resolves #412.

plugin: randomize plugin scores

---

pkg/agent/dispatcher.go
pkg/agent/informant.go

Builds on #499. Two parts to this PR:

agent/dispatcher: Add request(ish) message metrics

---

neonvm/tools/vm-builder-generic/main.go
neonvm/tools/vm-builder/main.go

The relevant information is in the comments added, but to replicate it here for completeness:
> Allow all users to move processes to/from the root cgroup.
>
> This is required in order to be able to 'cgexec' anything, if the entrypoint is not being run as root, because moving tasks betweeen one cgroup and another *requires write access to the cgroup.procs file of the common ancestor*, and because the entrypoint isn't already in a cgroup, any new tasks are automatically placed in the top-level cgroup.
>
> This *would* be bad for security, if we relied on cgroups for security; but instead because they are just used for cooperative signaling, this should be mostly ok.
In debugging this, I found portions of this answer very helpful: https://unix.stackexchange.com/a/741631
We don't have …

neonvm/builder: Allow any user to cgexec out of top-level cgroup

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/config/common/crd/bases/vm.neon.tech_virtualmachines.yaml
neonvm/runner/main.go

It enables the "discard" mount option, which can be used instead of fstrim to propagate hole punches down to the backing file (I think).
See also:
- https://chrisirwin.ca/posts/discard-with-kvm-2020/
- https://serverfault.com/questions/896448/qemu-trim-and-discard-on-a-physical-ssd-device

neonvm: Add EmptyDisk.Discard option

---

pkg/agent/dispatcher.go

Maybe the cause of memory leaks? And maybe also the cause of the issues where the vm-monitor times out trying to read the version information off the protocol.

agent/dispatcher: Close websocket if NewDispatcher fails

---

neonvm/runner/main.go

Not sure why this happens here, and not for tmpfs, but oh well. Validated locally that this fixes the problem.

neonvm/runner: Fix EmptyDisk chmod getting overwritten

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/config/common/crd/bases/vm.neon.tech_virtualmachines.yaml
neonvm/controllers/virtualmachine_controller.go

1. first there was this - https://github.com/neondatabase/neonvm/pull/12
2. then was this - https://github.com/neondatabase/autoscaling/pull/140
and now we need serviceAccount again to have ability use IRSA and let applications inside VM have access to AWS resources (s3)

add serviceAccountName field

---

neonvm/tools/vm-builder/main.go

One possible explanation for our high ESTABLISHED connection count
between computes and pageserver's page_service.rs is that we kill the
VMs before the FIN/RST packets from the `pg_ctl -m stop` leave the VM's
kernel.
The sleep added in this PR would give them a good chance.
Roll this out and observe.
Context: https://neondb.slack.com/archives/C036U0GRMRB/p1694427077510779?thread_ts=1694425364.531029&cid=C036U0GRMRB

speculative workaround for high unclosed connection count between compute smgr & pageserver

---

doc/vm-builder/README.md
doc/vm-builder/shutdown/shutdown.tla
neonvm/tools/vm-builder-generic/main.go
neonvm/tools/vm-builder/main.go

We're seeing unclosed connections from VM-based computes to pageservers.
They are reproducibly due to `suspend_compute` actions in console.
An earlier attempt to mitigate this was made in
https://github.com/neondatabase/autoscaling/pull/523
but it didn't show any effect.
See the `README.md` added in this PR for details.

acpi shutdown: correct and robust graceful shutdown

---

neonvm/tools/vm-builder-generic/main.go
neonvm/tools/vm-builder/main.go

After rolling out #525 to prod, we noticed that when the postmaster process gets OOM killed, it fails to restart.
The `init` would try to respawn `vmstart` but it would get stuck trying to `flock` the file, before starting `vmstarter.sh` / the new postgres processes.
Investigation showed that we were inherting the file descriptor and flock for `vmstart.lock`  to the child process tree.
Including the `postgres: Local free space monitor`  process, which fails to stop when postmaster gets killed.
Once we'd manually kill it, the respawned `vmstart`'s blocked `flock` would get unblocked.
We never intended to inherit the vmstart.lock file descriptor or flock, so, this PR disables that behavior.
That makes the restart-after-OOM-kill work again.
But, reviewing the file cache code, there's …

fixup #525: handle SIGKILLED postmaster process correctly

---

.golangci.yml
pkg/plugin/config.go
pkg/util/watch/watch.go

Noticed while working on #371, but it appears that golangci-lint will sometimes hide errors that it *should* be showing if compiling succeeds. So if, hypothetically, you're impacted by golang/go#58218 and normally you're able to get by with `go build -buildvcs=false ./...` but golangci-lint doesn't have that functionality, then this is able to reproduce on main.

Fix some exhaustruct lints

---

ARCHITECTURE.md

It's been a while since we moved the vm-monitor from its own repo into neondatabase/neon (see: neondatabase/neon#4946) - must have forgotten to update the architecture doc here.

ARCHITECTURE: update vm-monitor link

---

.github/workflows/lint.yml

Maybe there's reasons to keep these as a single job (or at least some of them), not entirely sure though.

lint workflow: Split into separate jobs

---

.github/workflows/lint.yml

Hit this working on #542 because its base branch isn't main.

lint workflow: Run on any PR, not just → main

---

.git-blame-ignore-revs
.github/workflows/lint.yml
ARCHITECTURE.md
cluster-autoscaler/Dockerfile
cluster-autoscaler/README.md
k3d/cilium.yaml
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachine_qmp_queries.go
neonvm/controllers/virtualmachinemigration_controller.go
neonvm/pkg/README.md
neonvm/pkg/ipam/ipam.go
neonvm/tools/vm-builder-generic/main.go
neonvm/tools/vm-builder/main.go
pkg/agent/dispatcher.go
pkg/agent/globalstate.go
pkg/agent/runner.go
pkg/api/types.go
pkg/plugin/plugin.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/util/watch/watch.go

Builds on #541, based on neondatabase/neon#5450.
Maybe worthwhile to merge via rebase, so that the spelling fixes can be added to .git-blame-ignore-revs.

lint workflow: Add codespell checks (spellchecking)

---

go.mod
pkg/agent/billing/billing.go
pkg/billing/client.go

Quoting a conversation about the current format:
> It’s quite big but mostly used only for deduplication purposes so that
> it can be any unique value.
And
> Pageservers use
> ```
> <timestamp with milliseconds>-<pageserver_id>-<number of event in the batch>
> ```
So the new format is
```
<RFC3339 timestamp with microseconds>-<pod name>-<number in batch>/<total batch size>
```

billing: Change idempotency key format

---

pkg/agent/dispatcher.go
pkg/agent/runner.go

Hopefully should help with debugging https://github.com/neondatabase/autoscaling/issues/503.

agent/runner: Add temporary monitor state dump for len(waiters)

---

pkg/agent/execbridge.go

After deploying v0.18.0, NeonVM metrics continued to be present, but the metrics for approved resources for the plugin and vm-monitor weren't, even though the *requested* resources were.
Turns out the "if err != nil" guarding updating the metrics should have been swapped. Original code was introduced in #371.

agent/execbridge: Fix zero approved change metrics

---

pkg/agent/runner.go

Introduced by #506, noticed after deploying v0.18.0 on staging.
Basically, we just never set the start time, so "time since last start" was always equal to "time since unix epoch", which means we'd always think that the connection was running long enough to immediately retry.
---
[Some logs demonstrating this](https://neonprod.grafana.net/goto/jPrH3FGIg?orgId=1):
```
2023-10-09 02:26:35.942	{"level":"error","ts":1696818395.9423525,"logger":"autoscaler-agent.runner.vm-monitor","caller":"agent/runner.go:518","msg":"Failed to connect to vm-monitor","virtualmachine":{"namespace":"default","name":"compute-white-salad-01036121"},"pod":{"namespace":"default","name":"compute-white-salad-01036121-tfdnr"},"taskName":"vm-monitor reconnection loop","addr":"ws://10.6.28.2:10301/monitor","error":"error …
```

agent/runner: Fix vm-monitor reconnect busyloop

---

pkg/agent/executor/exec_sleeper.go

Introduced by #371. Classic case of blocking on <-timer.C after !timer.Stop() not always being sound if you've already received from timer.C
Example stack trace:
```
goroutine 281014 [chan receive, 33 minutes]:
runtime.gopark(0x1?, 0x2?, 0x0?, 0x0?, 0xc00007c000?)
/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0017b0cf0 sp=0xc0017b0cd0 pc=0x43d7d6
runtime.chanrecv(0xc001702840, 0x0, 0x1)
/usr/local/go/src/runtime/chan.go:583 +0x49d fp=0xc0017b0d80 sp=0xc0017b0cf0 pc=0x408a7d
runtime.chanrecv1(0xc001034340?, 0xc0017b0ddc?)
/usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc0017b0da8 sp=0xc0017b0d80 pc=0x408578
github.com/neondatabase/autoscaling/pkg/agent/executor.(*ExecutorCore).DoSleeper(0xc001034340, {0x1b971b0, 0xc00149a1e0}, 0x0?)
/workspace/pkg/agent/executor/exec_sleeper.go:23 …
```

agent/executor: Fix DoSleeper deadlock/goroutine leak

---

pkg/agent/execbridge.go

Part of #550; we had some [executor panics](https://neonprod.grafana.net/goto/uBtSXoGSg?orgId=1) because the (*Dispatcher).Exited() is not synchronized with changes the executor state. See added comment for more details.

agent/execbridge: Don't check monitor (*Dispatcher).Exited()

---

deploy/agent/config_map.yaml
pkg/agent/config.go
pkg/agent/core/dumpstate.go
pkg/agent/core/state.go
pkg/agent/core/state_test.go
pkg/agent/runner.go

Without this, we can end up spamming the scheduler plugin or NeonVM API if there's transient request failures (e.g. if the autoscaler-agent has information about a VM for slightly longer than the plugin or NeonVM controller).
Part of #550.

agent/core: Add retry rate limits for plugin & NeonVM requests

---

pkg/agent/core/state.go
pkg/agent/core/state_test.go

Found on staging after v0.18.0-patch1 because of "response validation" failures in the logs. The issue occurs under specific conditions of multiple actions happening at the same time.
The added test case replicates the original sequence; refer there for more detail on what went wrong. See also, the [original logs](https://neonprod.grafana.net/goto/V3j8haGIg?orgId=1).
Part of #550.

agent/core: Fix invalid plugin request on limited downscale

---

Makefile

The idea is that we *really* don't want people to accidentally `make deploy` to prod (or even staging), and the best way to do that is to check the context in `make deploy` et al itself.
Implemented as its own target so we don't have to copy-paste. Not sure if I missed any (reviewers: please check!)
Resolves #319.

Makefile: Check kubectl context before applying

---

.github/workflows/lint.yml

~~Not sure if it'll work because the makefile target requires docker, but we can see :)~~
Seems to work ok :)

lint workflow: Add job to check generated go code

---

build/vm-monitor/Dockerfile

A build of `vm-monitor` started to fail with
```
#10 14.74 error: failed to run custom build command for `openssl-sys v0.9.90`
...
```
Ref: https://github.com/neondatabase/autoscaling/actions/runs/6537120014/job/17750853127?pr=569
This PR adds `openssl-dev` package to make `cargo build` happy. Also, it updates the base rust image to 1.72 to match the rust version that is used in `neondatabase/neon` repo.

Fix vm-monitor build

---

neonvm/tools/vm-builder/main.go

- update `pgbouncer` to [1.21.0](https://github.com/pgbouncer/pgbouncer/releases/tag/pgbouncer_1_21_0)
- enable prepared statements support (https://www.pgbouncer.org/config.html#max_prepared_statements)
See also https://github.com/neondatabase/cloud/pull/7381

Update pgbouncer to 1.21.0 + support prepared statements

---

neonvm/tools/vm-builder/main.go

It causes exporter connection to every database in the Postgres and it was disabled for pods a while ago, but I forgot that VMs have a different build path.
See this for details:
https://github.com/neondatabase/cloud/commit/0a60057f3380e570b540cc823975e07400cd640c
Also remove `--exclude-databases` it seems to be bogus as well, see:
https://github.com/prometheus-community/postgres_exporter/issues/588

vm-builder: Turn off --auto-discover-databases

---

deploy/agent/config_map.yaml
pkg/agent/config.go
pkg/agent/core/state.go
pkg/agent/core/state_test.go
pkg/agent/runner.go

Fixes #572; bulk of the diff is just slightly tweaking the test for denied downscaling.

agent/core: Add rate limit for vm-monitor downscale

---

pkg/agent/globalstate.go

Currently we don't, so it can be hard to piece together when the autoscaler-agent knew what.
May upgrade this from debug -> info, or move into the VM watcher itself. We'll see — just want _something_ for now.

agent: Log when handling VM events

---

pkg/plugin/watch.go

In short: after #563, deleting a migration before completion has caused the scheduler plugin to incorrectly interpret the deletion event for the source (or target? not entirely sure) pod as referring to a pod (rather than a VM), because all pods related to a VM will have the vm.neon.tech/name label, but only the pod currently _running_ the VM will be marked as "owned" by the VM; the other will be owned by the migration.

plugin: Fix migration source deletion event kind

---

neonvm/tools/vm-builder/main.go

See https://neondb.slack.com/archives/C026T7K2YP9/p1697815383381269?thread_ts=1697643821.075019&cid=C026T7K2YP9

vm-builder: Set pgboucer auth_dbname=postgres to fix database dropping issue

---

neonvm/tools/vm-builder/main.go

Disable prepared statement support for pgbouncer by setting `max_prepared_statements=0`.
It was initially enabled in https://github.com/neondatabase/autoscaling/pull/566, but we encountered some problems with them. And we can't just revert that PR (to pgbouncer 1.18) because we started to use `auth_dbname`, which is added in pgbouncer 1.19.
Ref https://neondb.slack.com/archives/C063B6SCHDX

vm-builder: disable prepared statements support for pgbouncer

---

neonvm/controllers/virtualmachine_qmp_queries.go

Reverts neondatabase/autoscaling#527.
Seems to be causing migration e2e tests to fail consistently. Not sure why, tbh. An example here: https://github.com/neondatabase/autoscaling/actions/runs/6722147149

Revert "neonvm/controller: Close QMP connection if Connect() fails"

---

neonvm/controllers/virtualmachine_controller.go
neonvm/pkg/ipam/ipam.go

This PR:
- avoid situation when `ipam.AcquireIP` return `<nil>` as result and `<nil>` as error to prevent controller crash.

ip acquirization fix

---

pkg/agent/executor/exec_monitor.go

Because of this issue, if the scheduler restarted while an upscale request was ongoing, the agent would incorrectly believe that this upscale request was permanently ongoing and never try to make another upscale or downscale request to the vm-monitor.

agent/executor: Fix use of plugin in DoMonitorUpscales

---

neonvm/apis/neonvm/v1/virtualmachine_webhook.go

Noticed this while debugging something unrelated. It doesn't even include the VM name. For example, I saw log lines like this:
```
{"level":"info","ts":"2023-11-04T00:48:59.556Z","logger":"virtualmachine-resource","msg":"validate port ","name":""}
{"level":"info","ts":"2023-11-04T00:48:59.556Z","logger":"virtualmachine-resource","msg":"validate port ","name":""}
{"level":"info","ts":"2023-11-04T00:48:59.556Z","logger":"virtualmachine-resource","msg":"validate port ","name":""}
{"level":"info","ts":"2023-11-04T00:48:59.556Z","logger":"virtualmachine-resource","msg":"validate port ","name":""}
```
---
Todo before merging:

neonvm/controller: Remove noisy webhook validation log lines

---

go.mod
go.sum
neonvm/tools/vm-builder/main.go

We've periodically opened PRs to slightly improve the output of vm-builder by handling more message types (#280, #599). But the actual implementation that `docker build` uses is available for us, so we might as well use that instead.
In the future, it'd be cool to use buildkit here to mimic the better styling from `docker buildx build`, but its source code is much harder to navigate.
---
Tested locally and validated that this works as expected under normal circumstances - greatly improves output, particularly while building vm-monitor.
TODO:
---
**This PR builds on #600 and must not be merged before it.**

vm-builder: Use same output format as `docker build`

---

cluster-autoscaler/Dockerfile
neonvm/tools/vm-builder/files/Dockerfile.img
vm-examples/pg14-disk-test/image-spec.yaml

Got some complaints from the arnica bot while moving things around (https://github.com/neondatabase/autoscaling/pull/603#discussion_r1379479661), figured I'd resolve it repo-wide.
IIUC the short explanation for "why COPY instead of ADD" is that COPY can only ever copy files on the system, whereas ADD can fetch from URLs, so it's fundamentally less secure.
**This PR builds on #603 and must not be merged before it.**

Replace ADD with COPY where possible

---

.github/workflows/vm-kernel.yaml

Testing this in manually-triggered run https://github.com/neondatabase/autoscaling/actions/runs/6870946818
Doesn't work because of credential error.

CI: run vm-kernel pipeline on bigger GitHub-hosted runner

---

tests/e2e/image-spec.yaml
vm-examples/pg14-disk-test/image-spec.yaml

Right now, this is only used to build vm-builder from `neondatabase/neon`, for the testing images.
I don't _think_ there's ordering requirements here with neondatabase/build#73 or neondatabase/neon#5873 (seems like no backwards-incompatible changes), but cc @arpad-m just in case.

Update to Rust 1.74

---

.github/workflows/vm-example.yaml

Fix `vm-example` job that has leftovers usages of `vm-builder-generic`
A CI run of fixed workflow: https://github.com/neondatabase/autoscaling/actions/runs/6947480644

CI: fix vm-example job

---

.github/workflows/e2e-test.yaml
.github/workflows/vm-kernel.yaml

- Build VM Kernel for e2e tests (the naive approach without caches takes ~3m)
- Make `vm-kernel` job to trigger e2e with this freshly built kernel
- Allow to trigger e2e tests with specified kernel
Things to improve (in the future PRs):
- `e2e-tests:` Use cached kernel version if it has no changes
- `vm-kernel`: Do not push kernel image if e2e tests with it fails

CI: Use the latest kernel in e2e tests

---

pkg/agent/execbridge.go

In short: Regardless what the response was, we recorded metrics as if the plugin had approved everything up to the target, which was not necessarily true. It's more correct to use the actual response.

agent/execbridge: Fix plugin approved resource metrics

---

pkg/plugin/plugin.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/plugin/trans.go

- Rename `ResourceTransition` into `ResourceTransitioner` because it's not an object that represents a transition, but actually it performs transitions on a resource state.
- Now it's safe to call handle functions multiple times on `ResourceTransitioner`. We got this by removing `oldPod` and `oldNode` fields from the transitioner.

plugin: refactor resource transition

---

.github/workflows/e2e-test.yaml

This PR attaches logs from `neonvm-system` and `kuttl-test-*` namespaces to GitHub Step Summary. 
Here's an example: https://github.com/neondatabase/autoscaling/actions/runs/6960120849?pr=597#summary-18938907450
GitHub Step Summary is limited by 1Mb, so if we have more logs then we won't be able to display it. I guess we can truncate it by 1MB, but it can be done later, for `neonvm-system` and `kuttl-test-*` namespaces 1MB is enough.
All the information is still available in the regular job output (in addition to logs and events from other namespaces)
Note that currently `kuttl-test-*` namespace got deleted automatically by `kuttl`, this will be changed in https://github.com/neondatabase/autoscaling/pull/635

CI: add k8s logs from e2e-tests to GitHub Summary

---

.github/workflows/e2e-test.yaml
.github/workflows/lint.yml
.github/workflows/release.yaml
.github/workflows/vm-example.yaml

Sometimes 5 minutes is insufficient for `actions/setup-go` to finish. Increase timeout to 10 minutes.
An example: https://github.com/neondatabase/autoscaling/actions/runs/6947476796/job/18901335316?pr=641
On self-hosted runners, `actions/setup-go` doesn't play nice with cache, so the action takes ~1.5m, due to a lot of errors from `/usr/bin/tar`. Disable cache for self-hosted runners to avoid these warnings and speed up the action call on self-hosted runners (with disabled cache it takes less than 10s).
An example: https://github.com/neondatabase/autoscaling/actions/runs/7070592454/job/19247430600
Part of https://github.com/neondatabase/autoscaling/issues/660

CI: increase timeout and disable cache for actions/setup-go

---

pkg/plugin/dumpstate.go
pkg/plugin/plugin.go
pkg/plugin/state.go

Since #399, "total reservable CPU/memory" has just been equal to the value of nodeResourceState.Total, so these methods haven't been doing anything.
Split out from #653.

plugin: Remove `(*nodeState).totalReservable{CPU,MemSlots}`

---

deploy/scheduler/config_map.yaml
pkg/plugin/config.go
pkg/plugin/run.go
pkg/plugin/state.go

Another change split out from #653.
In short: More cleanup of something that was unnecessarily configurable.
**NB: This PR builds on #654 and must not be merged before it.**

plugin: Make compute unit config global

---

pkg/plugin/state.go

The fact that we treat the config as immutable (and so, it can be accessed without locking) wasn't written down anywhere, which can make reviewing PRs needlessly hard (see e.g. #657).

plugin: Add comment about locking of `pluginState.conf`

---

pkg/plugin/plugin.go

I _think_ this was a holdover from when we still had live config reloading, which was removed in #87.
Split off from #653.

plugin: Move `(*AutoscaleEnforcer).checkSchedulerName()` outside of locks

---

.github/workflows/e2e-test.yaml
Makefile
neonvm/Dockerfile
neonvm/controllers/buildtag/nodelete_false.go
neonvm/controllers/buildtag/nodelete_true.go
neonvm/controllers/buildtag/tagnames.go
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachinemigration_controller.go

This is implemented by adding a build tag 'nodelete', which disables deletion of VM runner pods - at least, while the VM or VMM object exists.
We *could* have actually kept the runner pods around even if the VM/VMM is deleted, but there's already ways to keep the objects around after e2e tests end (see #635), and this way the results would be a little less catastrophic if we accidentally released it.
The 'nodelete' tag is enabled by the Makefile based on the `E2E` env var.
Part of #634.
---
Note for review: I was going to use the `CI` env var like #635, but it's set on all workflows and the point is to build images with different config for e2e tests only. I'm not sure that the new `E2E` env var is the right name; open to suggestions there or alternate solutions (maybe something to do …

neonvm/controller: Don't delete runner pods in CI

---

dev-eu-west-1-zeta/autoscaler-agent.yaml
patches.json

This configures autoscaler to send consumption to cplane instead of directly to console in staging region eu-west-1.
https://github.com/neondatabase/cloud/issues/7144

[Autoscaler] autoscaler consumption to staging cplane in eu-west-1

---

.github/workflows/vm-kernel.yaml

Switch from GitHub's `gha-ubuntu-22.04-64cores` runner to self-hosted `large` runner (32 cores / RAM 128 GiB).
- Before: 2m 21s total (1m 38s 'build-linux kernel' step) [a link](https://github.com/neondatabase/autoscaling/actions/runs/7014316396/job/19081849534)
- After: 1m 85s total (1m 43s 'build-linux kernel' step) [a link](https://github.com/neondatabase/autoscaling/actions/runs/7072729343/job/19251884151)
Also, fix `env. VM_KERNEL_VERSION` usage, because we don't have this variable anymore, get it from parsing `neonvm/hack/linux-config-*` (maybe we should get it from another place?)
Part of https://github.com/neondatabase/autoscaling/issues/660

CI: use self-hosted runner for vm-kernel workflow

---

.github/workflows/e2e-test.yaml

Since we started to run e2e tests using both `kind` and `k3d` (https://github.com/neondatabase/autoscaling/pull/340), I can't recall a case when tests failed only on one cluster (due to app changes and not a cluster configuration).
After switching to `large` self-hosted runners (in https://github.com/neondatabase/autoscaling/pull/661), there's a chance that e2e tests could fight for resources with other projects that use such runners. To make the build faster by using fewer runners. Given the message above, let's run the test only on a single cluster configuration but keep an alternative way (for those who are used to it).
It is still possible to trigger e2e tests on `kind` cluster manually ([an example](https://github.com/neondatabase/autoscaling/actions/runs/7131694851)): …

CI: run e2e tests only using k3d cluster

---

.github/workflows/vm-kernel.yaml
Makefile
neonvm/README.md
neonvm/hack/Dockerfile.kernel-builder

Copying the method used from #662.
Also, remove the default value of the ARG from the top of the Dockerfile, so that the `linux-config-*` filename is the authoritative source for the kernel version we're using.
See also #652, which this PR _partially_ reverts in order to move the source of the kernel version back out of the Dockerfile.
---
Note for review: Not entirely sure that this is the right way to do it, but after seeing the technique in #662, I figured it might make sense to go all-in on that way. At some point in the future, we _might_ want to switch from `${linux_config##*-}` to `${linux_config#*linux-config-}`, but it probably doesn't matter _too_ too much.

Makefile: Set KERNEL_VERSION from linux-config filename

---

neonvm/runner/main.go

The NeonVM k8s nodes are currently write-IOPS-bottlenecked.
We can mitigate that by using cheaper & faster storage than EBS.
But, also, we can avoid most synchronous writes by ignoring
fua/flush/sync requests. That's what `cache=unsafe` does.

neonvm/runner: treat guest-side disk flush requests as no-ops

---

pkg/agent/billing/send.go
pkg/billing/client.go

ref https://neondb.slack.com/archives/C03H1K0PGKH/p1702049320084879?thread_ts=1701881238.622479
To do this accurately, this commit renames `billing.Client.{BaseURL => URL}` and adds the `usage_events` suffix to `URL`, rather than during `billing.Send`.
This commit also reorders some of the log fields in the sending code (mostly just moving traceID), so that smaller items are at the start and similar items are grouped together.

agent/billing: Log URL on billing requests

---

neonvm/config/default-vxlan/whereabouts/daemonset_patch.yaml
neonvm/config/default-vxlan/whereabouts/kustomization.yaml

The upgrade from whereabouts v0.6.1 -> v0.6.2 removed the node affinity that prevented the daemonset from trying to run on ARM nodes.
During deploy of v0.20.0 (which contained this upgrade, via #636), we hit issues in one staging region which had an ARM node and had to rollback whereabouts.
ref https://neondb.slack.com/archives/C039YKBRZB4/p1702083096619049
---
Notes for review: I basically just copied the multus patch we have. The diff is as expected:
```diff
220a221,233
>       affinity:
>         nodeAffinity:
>           requiredDuringSchedulingIgnoredDuringExecution:
>             nodeSelectorTerms:
>             - matchExpressions:
>               - key: kubernetes.io/arch
>                 operator: In
>                 values:
>                 - amd64
>               - key: …
```

neonvm/whereabouts: Require amd64 to fix issues with ARM nodes

---

neonvm/tools/vm-builder/files/vector.yaml

Per the comment: The [default interval is every 15s](https://vector.dev/docs/reference/configuration/sources/host_metrics/#scrape_interval_secs), but we fetch these every 5s from the autoscaler-agent.
This should have the net effect of making the scaling algorithm more responsive, because we should stop getting (as many) sequential responses that are exactly the same.
Unfortunately, load average is only recalculated every 5 seconds anyways, so we may still get repeated values there, but this should at least be an improvement.
---
Requested review because I'm not sure if there's something I'm missing that may make this a bad idea. Maybe we want to prune the list of exposed metrics, in case the scraping actually becomes intensive?

vm-builder: Set vector scrape interval from 15s to 1s

---

pkg/agent/dispatcher.go

Noticed while debugging neondatabase/cloud#8602 that failed health checks were unexpectedly logged as a warning — and then the errors about "no record of previous message" made it harder to realize that the actual issue was timeouts.

agent/dispatcher: Clarify some logs about monitor requests

---

neonvm/runner/main.go

Reverts neondatabase/autoscaling#628.
`cache=unsafe` means that we rely on the kernel page cache more, which increases IO speed _most of the time_, but can have catastrophic results if the node's free memory runs out with all of it taken up by page cache.
ref https://neondb.slack.com/archives/C03TN5G758R/p1702585801270379?thread_ts=1702577770.752879
ref https://neondb.slack.com/archives/C03F5SM1N02/p1702571133926869?thread_ts=1702558673.445669

Revert "neonvm/runner: treat guest-side disk flush requests as no-ops"

---

pkg/agent/prommetrics.go
pkg/agent/watch.go

Following common prometheus-style metric conventions [1]:
* a metric "should represent the same logical thing-being-measured across all label dimensions"
* It is also helpful to suffix the metric name with a unit type hint where applicable. Here memory has unit type bytes, while cpu has number of cores.
Therefore I think it's better to have separate metrics for different resource types.
[1] https://prometheus.io/docs/practices/naming/

agent: Separate memory and cpu metrics

---

pkg/agent/core/dumpstate.go
pkg/agent/core/state.go

This PR comes in two parts, intended to be merged via rebase so we can add the first to `.git-blame-ignore-revs`.
Basically, we currently have a bunch of duplicated fields between `State` and `StateDump` in order to implement JSON-serializable deep copying without exposing those from `State` itself.
This is _kind of silly_; we can just add a layer of indirection in `State` so that the JSON-serializable contents aren't visible, and then share them. So that's what this PR does.
---
Notes for review: I'd recommend looking at the two commits separately. The first is just a bunch of renames (done via LSP), and the second is the actual meat of the simplification. 
Because we're now using the same types in both places, the copying code can actually be much simpler — various pointer-to-structs …

agent/core: Deduplicate `State` and `StateDump` fields by sharing them

---

README.md

This is a restriction that we don't make clear anywhere, but should.
For info on the markdown syntax, refer to the [github markdown docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).
Closes #473.

README: Add note about supported OS/arch

---

neonvm/controllers/virtualmachine_controller.go

Move cgroup updates to VmScaling phase. Rewrote updating CPU status in VmRunning phase based on the values from cgroups and qemu.
Fixes https://github.com/neondatabase/autoscaling/issues/462

neonvm: Refactor runner pod cgroup cpu scaling

---

deploy/agent/config_map.yaml
pkg/agent/config.go
pkg/agent/core/dumpstate.go
pkg/agent/core/state.go
pkg/agent/core/state_test.go
pkg/agent/runner.go
pkg/api/VERSIONING.md
pkg/api/types.go
pkg/plugin/run.go

Instead, define it in the autoscaler-agent config.
This change starts the removal process of ComputeUnit from PluginResponse, so that the new protocol version expects that it won't be set - but to preserve backwards-compatibility during the upgrade, we need to keep the old behavior for now (hence the field is `omitempty`).
A follow-up change will update the plugin so that it *never* sends ComputeUnit, removing the field and the plugin's config along with it.
Part of #706.
---
Notes for review: This overlaps _a little_ with #653 — I think it's _probably_ easier to merge this first, release, and then merge that one.
~~Marking as a draft for now, until I've tested that e2e tests pass with old agent + new scheduler.~~ Tested locally and it appears to work.

agent,plugin: Don't send ComputeUnit from plugin

---

pkg/agent/watch.go

This shows up when I run golangci-lint locally. I guess it doesn't show up in CI because we're running '--fix' there?.
See also #718.
Edit: Didn't realize this was already included in #718, oops. Happy to merge either one.

lint: Fix import ordering in pkg/agent/watch.go

---

.github/workflows/lint.yml

--fix is not supposed to be used in CI.
It just silently fixes the issue and doesn't commit it.

lint: delete --fix from golangci-lint

---

.github/workflows/e2e-test.yaml
.github/workflows/release.yaml
.github/workflows/vm-kernel.yaml

Make `vm-kernel` a reusable workflow and call it from `e2e-test` and `release` workflows.
Other changes:
- add `kernel-image-tag-override` to `vm-kernel` to make it possible reuse previously built kernel.
- do not trigger `e2e-test` from `vm-kernel`: since now it happens the other way around
Caching kernel image is going to be the next PR.
The PR supersedes #651.

CI: call vm-kernel from release and e2e-test workflows

---

.github/workflows/release.yaml

In #662 we found a way to make self-hosted runners play nicely with `docker/login-action` action (by using a custom `DOCKER_CONFIG` directory). Now we can switch release workflow to self-hosted runners as well.

release: switch workflow to large self-hosted runners

---

neonvm/main.go

I must've missed this one during review, oops :sweat_smile:

neonvm-controller: Fix pprof server name (remove "scheduler")

---

deploy/agent/config_map.yaml
pkg/agent/config.go
pkg/agent/core/state.go
pkg/agent/core/state_test.go
pkg/agent/runner.go
pkg/api/types.go

Before, we would request the "full" downscaling or upscaling that we desired - for downscaling, we'd retry with a higher amount if the initial request was denied.
To reduce load, it's better to only request decreasing by 1 CU at a time. Also, bounding the size of changes from vm-monitor requests will also help with managing uncertainty (see #680).
Fixes #615, building towards #350.
~~**NB: This PR builds on #707 and must not be merged before it.**~~

agent/core: Send monitor requests in 1 CU increments

---

Makefile

It is convenient to run when developing locally.

lint: add lint to Makefile

---

go.mod
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachine_qmp_queries.go
neonvm/controllers/vm_qmp_test.go

The new implementation has several advantages over the previous one:
1. It handles the case, when there are leftover memory backends from
previous incomplete unplugs (see #451). Those backends are reused for
new DIMM devices.
2. It allows for simultaneous addition/removal of multiple devices.
3. It adds symmetrical k8s event reporting for both memory backends
and DIMM devices.
Fixes #451
Old pr #704

qmp: unify up/down memory scaling

---

pkg/agent/runner.go

Part of #741, see there for more info. Basically, we generally want to avoid letting requests become synchronized across VMs, and this is one part of doing that.

agent: Add small random amount to plugin request tick

---

pkg/agent/runner.go
pkg/api/types.go
pkg/plugin/run.go

Related to moving the compute unit source of truth from the scheduler plugin to the autoscaler-agent (see #706).
We also particularly want to have this so that the plugin doesn't approve resources that aren't an integer multiple of the respective value in the compute unit. If we didn't we could e.g. approve 1.01 CPUs, leaving the autoscaler-agent with 0.01 CPUs that it'll never use. In practice, that's quite unlikely to happen, but it's still worth avoiding potential issues there.
~~**NB: This PR builds on #653 and must not be merged before it.**~~
~~**Before merging:** Still need to check that we're able to run with old autoscaler-agent + new scheduler, with this PR.~~ Done

agent: Send compute unit in requests to plugin

---

.github/actionlint.yml
.github/workflows/lint.yml
.github/workflows/release.yaml
.github/workflows/vm-kernel.yaml

This PR adds [`actionlint`](https://github.com/rhysd/actionlint), a linter for GitHub Workflow files.
It also checks inlined bash scripts with [`shellcheck`](https://www.shellcheck.net/).
I've disabled a couple of noisy `shellcheck` rules (`SC2046`, `SC2086`), which in most cases produce benign warnings.
The action itself copied from `neondatabase/neon` (https://github.com/neondatabase/neon/pull/5265).
Run it locally (you should have both `actionlint`, and `shellcheck` installed):
```bash
SHELLCHECK_OPTS=--exclude=SC2046,SC2086 actionlint
```

lint: add actionlint

---

neonvm/controllers/virtualmachine_controller.go

Extracted from #738. It was kind of weird before, because the annotation was added to the pod after-the-fact during creation, but then ignored later on. Makes more sense to fully include it as one of the expected annotations.

neonvm-controller: Refactor kubectl default container annotation

---

neonvm/controllers/metrics.go
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachinemigration_controller.go
neonvm/main.go

Providing custom metrics for reconciler objects.
- `reconcile_failing_objects` represents the number of objects that are failing to reconcile for each specific controller.
Fixes #247 (along with #739).

neonvm: Custom reconciler metrics

---

neonvm/controllers/virtualmachine_controller.go

Noticed while working on #738. In short, because the runner API version was part of `labelsForVirtualMachine`, any update to the runner version would be updated for *all* VM pods, not just new one.
This is (probably) not an issue in prod right now, but could be an issue for future changes. ~~Right now, #738 would trigger this bug, but remain unaffected (it doesn't have version-dependent logic *currently*).~~
This PR fixes the behavior by adding the runner API version as an explicit argument to `labelsForVirtualMachine` and ignoring the label in `updatePodMetadataIfNecessary`.
---
Notes for review: Planning to merge 48h after 1 approval, or 24h after 2 approvals. Want to give people a chance to take a look, but overall change is not too complex.

neonvm-controller: Fix overwriting runner version

---

neonvm/runner/main.go

This isn't the cause of any problems we're observing, but it should make things a bit clearer in the future.
Basically, the context only gets canceled here:
https://github.com/neondatabase/autoscaling/blob/e5248b0c27dfae55a5f648cad695dc84db2ffc13/neonvm/runner/main.go#L644-L650
i.e. after QEMU has already exited, so this should make it a little more clear when we get connection errors that it's not because the context was canceled.
cc @problame

neonvm/runner: Skip QEMU powerdown if already exited

---

.github/workflows/build-images.yaml
.github/workflows/build-test-vm.yaml
.github/workflows/e2e-test.yaml
.github/workflows/release.yaml
Makefile

Brief summary of changes:
1. Add new workflow `build-images.yaml` in that builds images and pushes them to dockerhub (e.g. neonvm-controller, autoscaler-agent, etc.)
2. Add new workflow `build-test-vm.yaml` that builds vm-builder and makes the postgres:15-bullseye VM image.
- Also uploads vm-builder as an artifact if requested
3. In `e2e-test.yaml`, use images from (1) and (2)
- Also uploads the rendered manifests as an artifact if requested
4. In `release.yaml`, use images from (1) and (2), run tests with (3), and use vm-builder and manifests from (1) and (3).
5. Adds `make load-example-vms` and equivalents, which load images without building
---
Pre-req for #580, should also help with #660 (+ unlocks ability to cache test VM image builds).
---
~~Absolutely no clue if this'll work, but …

CI: Use separate workflows for image builds 

---

.github/workflows/e2e-test.yaml

ref https://github.com/neondatabase/autoscaling/actions/runs/7673566092
`${{ github.event.pull_request }}` doesn't exist for 'push' events :facepalm:

CI: Fix e2e-tests failure from empty $SHA on main

---

neonvm/runner/main.go

Last minute logging change in
6addbdc (runner: pass logs through virtio-serial (#724), 2024-01-24)
Resulted in flooding logs with the following error message:
"msg":"failed to read from log serial",
"error":"read unix @->/vm/log.sock: i/o timeout",
Filtering for os.ErrDeadlineExceeded before logging fixes it.
Related to neondatabase/cloud#8602.

runner: don't log i/o timeout

---

neonvm/config/common/controller/manager.yaml
neonvm/config/default-vxlan/manager_config_patch.yaml
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachine_controller_test.go
neonvm/controllers/virtualmachinemigration_controller.go
neonvm/main.go

We noticed a couple prod regions are close to all capacity used w.r.t. the existing concurrency limits.
This PR intends to provide a low-risk way to allow tweaking the precise limit more quickly.
ref https://neondb.slack.com/archives/C03TN5G758R/p1706641824349959?thread_ts=1706160071.213319
ref https://neondb.slack.com/archives/C03TN5G758R/p1706646482943109

neonvm-controller: Make max concurrency configurable via CLI

---

pkg/plugin/plugin.go
pkg/plugin/state.go
pkg/plugin/watch.go

We had the same thing implemented in a few places, with some TODOs to unify them eventually - so, here it is.
Summary of changes:
- Merge all handling of pod/VM "start" / "reserve" logic to go through `(*AutoscaleEnforcer).reserveResources()`
- Combined `handlePodStarted`/`handleVMStarted` -> `handleStarted`
- Merge all handling of pod/VM "deletion" / "unreserve" logic to go through `(*AutoscaleEnforcer).unreserveResources()`
- Pass around `*corev1.Pod` objects 
TODO:

plugin: Unify reserve and unreserve logic

---

neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachinemigration_controller.go

Extracted from #738, which adds a second container to the runner pods. Because of that second container, if only one container exits, the pod will still have `.status.phase = Running`, so we need to proactively notice that one of the containers has stopped and propagate that status to the VM itself.
This also introduces some funky logic around how we handle restarts: Because the `Succeeded` and `Failed` phases no longer imply that QMEU itself has stopped, we need to explicitly wait until either the pod is gone or the neonvm-runner container has stopped; otherwise we could end up with >1 instance of the VM running at a time.
---
Tested locally as part of #738 and validated that it has the intended effect and works as expected when I `kubectl exec <pod> -c <container> -- kill 1`.
NB: Some …

neonvm: Use container statuses, not pod phase, to trigger restart

---

neonvm/config/default-vxlan/manager_config_patch.yaml

We noticed issues at at 8, then 16, then 32, and even 64 for some large regions.
128 appears to be stable in prod (even though it's overcommitting controller CPU limits 32:1).
ref https://neondb.slack.com/archives/C03TN5G758R/p1706725735037289?thread_ts=1706160071.213319

neonvm-controller: Use --concurrency-limit=128

---

Makefile
neonvm/apis/neonvm/v1/virtualmachine_webhook.go
neonvm/config/common/rbac/role.yaml
neonvm/controllers/config.go
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachine_controller_test.go
neonvm/controllers/virtualmachinemigration_controller.go
neonvm/main.go
neonvm/runner/Dockerfile
neonvm/runner/container-mgr/crictl.go
neonvm/runner/container-mgr/main.go
neonvm/runner/main.go

We recently realized[^1] that under cgroups v2, kubernetes uses cgroup namespaces which has a few effects:
1. The output of /proc/self/cgroup shows as if the container were at the root of the hierarchy
2. It's very difficult for us to determine the actual cgroup that the container corresponds to on the host
3. We still can't directly create a cgroup in the container's namespace because /sys/fs/cgroup is mounted read-only
So, neonvm-runner currently *does not* work as expected with cgroups v2; it creates a new cgroup for the VM, at the top of the hierarchy, and doesn't clean it up on exit.
How do we fix this? The aim of this PR is to remove the special cgroup handling entirely, and "just" go through the Container Runtime Interface (CRI) exposed by containerd to modify the existing …

neonvm: Use crictl to change container CPU, ditch cgroup

---

neonvm/runner/main.go

When testing on my laptop, launching the VM sometimes failed with:
dnsmasq: failed to create inotify: No file descriptors available
That can be fixed by raising the inotify limits, which are apparently quite low by default. We did that in commit a17be2b062 for e2e tests, although that was later removed because we changed the settings in the runners instead.
But to avoid having to change those settings, we can use the --no-resolv flag. When --no-resolv is given, and none of the dhcp-hostsdir dhcp-optsdir, hostsdir options are used, dnsmasq doesn't use inotify at all.
It's a bit silly that --no-resolv has that effect when DNS is disabled (--port=0), because dnsmasq doesn't actually read resolv.conf when DNS is disabled. I think that could be improved in dnsmasq. But in the meanwhile. See …

Avoid "dnsmasq: failed to create inotify .." errors.

---

pkg/agent/billing/prommetrics.go

While working on the "billing" section of the new autoscaler-agents dashboard [1], I noticed that this metric is recorded but never actually registered, hence not *actually* available.
See also #788.
We may also want to reorganize the way these metrics are defined, so we can use e.g. `util.RegisterMetric` while initializing the struct (to avoid having this issue in the first place).
[1]: https://neonprod.grafana.net/d/bdbt33ngwqc5cb

agent/billing: Fix unregistered metric lastSendDuration

---

pkg/util/metrics.go

Using the interface allows to use other implementations as well.

util: use prometheus.Registerer in RegisterMetrics

---

.github/workflows/build-images.yaml
.github/workflows/build-test-vm.yaml
.github/workflows/e2e-test.yaml
.github/workflows/release.yaml

After the changes by #748 (adding separate image build workflows), releasing [hit some issues](https://github.com/neondatabase/autoscaling/actions/runs/7818714553) because `true != 'true'` and [sometimes workflow inputs are the string](https://github.com/actions/runner/issues/1483) "true", whereas other times, they're the *value* `true`.
Hopefully this solution works. It's quite hacky though, so it'd be good to find a clean solution (e.g., maybe `fromJSON` works?)
---
Found the relevant occurrences with
```sh
rg "[!=]= 'true'" .github
```

CI: Use `format('{0}', x) == 'true')` to check truthiness

---

pkg/plugin/run.go

Closes #760.
AFAIK this hasn't been an issue in the past, but as we're trying to improve reliability, it's good to get this out of the way before it becomes an issue.
Note that this PR is quite minimal - expanding the existing tech debt we have around how the scheduler plugin handles HTTP requests. It's probably ok *enough* for now. I don't expect we'll be making too many changes to it in the near future. See also: #13.
Tested locally by forcing it to panic on every request:
```diff
diff --git a/pkg/plugin/run.go b/pkg/plugin/run.go index 007554a..6da7728 100644
--- a/pkg/plugin/run.go
+++ b/pkg/plugin/run.go
@@ -262,8 +262,10 @@ func (e *AutoscaleEnforcer) handleAgentRequest(
}
}
-	pod.vm.mostRecentComputeUnit = &e.state.conf.ComputeUnit
-	return &resp, 200, nil
+	panic(errors.New("test …
```

plugin: Handle panics from agent requests

---

pkg/plugin/plugin.go

Saw this when I did "kubectl describe pod compute-...", on a VM pod:
Events:
Type     Reason            Age    From                 Message
----     ------            ----   ----                 -------
Warning  FailedScheduling  4m53s  autoscale-scheduler  0/1 nodes are available: 1 Not enough resources for pod.
Warning  FailedScheduling  4m51s  autoscale-scheduler  running Reserve plugin "AutoscaleEnforcer": Not enough resources to reserve non-VM pod
That message is wrong, because this was a VM. Fix the message to not specify whether it's a VM or non-VM pod.

plugin: Fix k8s status message if pod scheduling fails

---

neonvm/config/default-vxlan/manager_config_patch.yaml

We noticed higher than desired reconcile latency in prod because of CPU throttling. Bumping CPU limits from 4 to 8 in larger regions significantly reduced latency, without increasing average CPU usage.
ref https://neondb.slack.com/archives/C03TN5G758R/p1707686417925039

neonvm-controller: Bump CPU limits 4 -> 8

---

neonvm/config/default-vxlan/manager_config_patch.yaml

We should have this for dev at least. We'll probably need to be careful not to prematurely enable it staging/prod, but that should be straightforward enough.

neonvm-controller: Enable container-mgr by default

---

.gitignore
Makefile

**Merge after 15th of February**
https://github.com/neondatabase/autoscaling/pull/715 has moved `vmlinuz` directory from `neonvm/hack` to `neonvm/hack/kernel`. This PR deletes the old path from the code. 
Let's give people some time and merge it in a month or so.
Ref https://github.com/neondatabase/autoscaling/pull/715#discussion_r1446239895

Remove old kernel path `neonvm/hack/vmlinuz`

---

neonvm/controllers/virtualmachine_controller.go

In an effort to reduce pressure on containerd, this reduces the number of init containers.
This might be a preliminary step on the path to get rid of init containers entirely.
Part of #747

neonvm: merge init-rootdisk and sysctl containers

---

neonvm/config/default-vxlan/manager_config_patch.yaml
neonvm/runner/main.go

Previously, if QEMU failed to startup, the log output contained either:
1. Panic, because of `reader==nil`
2. `"error":"dial unix /vm/log.sock: connect: no such file or directory","stacktrace":"main.forwardLogs.func1\n\t/workspace/neonvm/runner/main.go:897\nmain.forwardLogs\n\t/workspace/neonvm/runner/main.go:921"`
Which was confusing. Not it will have:
`{"level":"warn","ts":1707993260.548491,"logger":"neonvm-runner","caller":"runner/main.go:897","msg":"QEMU shut down too soon to start forwarding logs"}`
Panic was found by the Discord user @ido6668.
Fixes #791

runner: log forward: wait for QEMU startup and prevent panic

---

neonvm/controllers/metrics.go
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachinemigration_controller.go
neonvm/main.go

Similar in spirit to the "dump state" endpoints exposed by the autsocaler-agent and scheduler plugin.
This one is on port 7778 (+1 from the pprof server on 7777).
The state can be fetched with:
```sh
kubectl port-forward -n neonvm-system pod/<pod-name> 7778:7778 &
curl http://localhost:7778/
```
---
Part of the reason for this change is that the metrics reported by #757 indicate there's a VM in prod that has been failing to reconcile, even though the logs don't show per-VM error rates consistent with that. So hopefully this should allow us to debug issues like this in the future.

neonvm-controller: Add reconcile metrics debug endpoint

---

pkg/plugin/prommetrics.go
pkg/plugin/run.go

It's unnecessarily high-cardinality and never used.
Ref https://neondb.slack.com/archives/C03TN5G758R/p1708344983594829

plugin: Remove client_addr metrics label

---

Makefile

revert (unexpected?) changes introduced in https://github.com/neondatabase/autoscaling/pull/809

use user-independent cluster name

---

neonvm/config/common/controller/manager.yaml

Increase neonvm-controller replicas to have highly available deployment for neonvm controller.
We already have leader-election enabled for neonvm-controller: https://github.com/neondatabase/autoscaling/blob/9beedbd2624fc04dcfe4efd600ebc7dd771c355f/neonvm/config/common/controller/manager.yaml#L60
Because of leader election at any point in time, at most one controller can run the reconcile loop. No matter if we're in the middle of a deployment, rollback, or any other case. Increasing the number of replicas doesn't break this safety property. 
Leader election is enabled by default in kube-builder projects and turning it off is unsafe in our case (even with a single replica) since during deployments or rollbacks two replicas may run the reconcile loop.
Kubernetes implements leader-election in …

neonvm: increase neonvm-controller replicas

---

neonvm/apis/neonvm/v1/virtualmachine_webhook.go

Makes it easier to track a VM through logs.

neonvm: log VM name in the neonvm webhook manager

---

neonvm/controllers/catch_panic.go
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachinemigration_controller.go

In theory I think this could be done with some kind of middleware, similarly to our metrics collection. In practice, it's quite small, and probably more effort than it's worth to do the abstraction.
Resolves #827.
---
~~Haven't tested it yet, need to try that locally to check it works.~~

neonvm-controller: Catch Reconcile() panics

---

neonvm/runner/main.go

Must have missed it previously. We definitely want this parameterized by the disk cache settings, because characteristics around swap will have a big impact on lower bounds for performance.
ref https://neondb.slack.com/archives/C03TN5G758R/p1708630454044509?thread_ts=1707675595.221699

neonvm-runner: Use diskCacheSettings for swap disk

---

pkg/agent/dispatcher.go

Tested locally with pg16-disk-test and the allocate-loop (see the README for more on this).
Really silly bug, this one.
Fixes #807

agent/dispatcher: Fix inbound monitor msg metrics

---

neonvm/config/controller/deployment.yaml

This wasn't being used (not scraping metrics), and then when we started scraping metrics, we just exposed the port directly.
Maybe in the future we'll want to make these metrics more restrictive, but for now there's bigger fish to fry.
---
This is a second attempt at 31383df2209433d66233c0b5a10b80c44a962178 (from #779), built atop #824. A notable difference is that this time around, we're not touching the controller pod's affinity.
**NB: This PR builds on #824, and must not be merged before it.**

neonvm: Remove controller metrics auth proxy

---

deploy/scheduler/config_map.yaml
pkg/plugin/config.go
pkg/plugin/plugin.go

Each handler has its own queue, and we distribute events by hashing the name of the object we're sending through, so that pod start and stop event ordering is preserved by going in through the same queue.
This will help reduce the impact of any future issues where the event queue gets backed up.
Part of #851.
---
Like #853, I'll probably put this on staging for testing over the weekend, so we can (optimistically) do a hotfix early next week.

plugin: Use multiple event handler threads

---

.github/workflows/e2e-test.yaml
Makefile
neonvm/runner-image-loader/daemonset.yaml
neonvm/runner-image-loader/kustomization.yaml

When rolling out an update to neonvm, we currently don't pre-load the neonvm-runner images. This has a couple effects:
1. For a brief period, new VM runner pods are additionally blocked on pulling the runner image (which can take a while); and
2. If there's issues with pulling the runner image, we only detect that once we're actually attempting to use it.
This PR adds a new daemonset to just keep the neonvm-runner image around on each node. Before rolling out a neonvm update, we can update the runner image in the daemonset to make sure that the new image is loaded on all the nodes.
Part of neondatabase/cloud#11232

neonvm: Add neonvm-runner image loader

---

pkg/plugin/plugin.go
pkg/plugin/prommetrics.go
pkg/util/k8s.go

- Adds `util.PodPreferredAZIfPresent` to determine the AZ
- Adds the `desired_availability_zone` label to the plugin method metrics
- Passes the `*corev1.Pod` through to `IncMethodCall` and `IncFailIfNotSuccess` to inclulde the AZ
Closes #861.

plugin: Add pod desired AZ to plugin method metrics

---

deploy/scheduler/config_map.yaml
pkg/agent/core/state.go
pkg/agent/core/state_test.go
pkg/agent/core/testhelpers/construct.go
pkg/api/vminfo.go
pkg/api/vminfo_test.go
pkg/plugin/dumpstate.go
pkg/plugin/plugin.go
pkg/plugin/queue.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/plugin/watch.go

Resolves #756. Copying from that issue:
> When we enable automatic live migration in prod, we'll require enabling the overlay IP addresses on all existing VMs. This is not currently enabled, so enabling migration will either (a) have to wait until all VMs use the overlay IP addresses, or (b) be enabled
> gradually, on a case-by-case basis.
Now that it's opt-in, we can *also* set the global config setting to default to true. Still worth keeping for now, at the very least as a "break glass in case of emergency" button.
---
**Notes for review:** This is a lot of commits. Every commit except the last one is just laying the groundwork for this PR, so I figured I'd include it here.
Happy to split those out into a separate PR if that'd be easier.
I intend to merge this PR via rebase, so the …

plugin: Make auto- live migration opt-in

---

pkg/plugin/plugin.go
pkg/plugin/prommetrics.go
pkg/plugin/state.go

The only reason why it could fail in Reserve step, while not failing in
Filter step is due to an inconsitency, and we don't want to make any
decisions based on an inconsistent state.
Also, count cases where it would've failed before. This boosts observability even if it Reserve actually won't deny the
request
Fixes #869

plugin: don't fail in Reserve() 

---

neonvm/runner/main.go

Explanation taken from the added comment:
> `(*errgroup.Group).Wait()` returns at most 1 error, which means imprecise usage can hide errors. So, we log the errors before they would be returned, to make sure they're always visible.
In particular, this is required to make sure that #887 is sound.

neonvm-runner: Log parallel errors before returning

---

pkg/api/VERSIONING.md
pkg/plugin/run.go

Looked at rebasing #750 and realized:
1. The scheduler plugin's range of accepted versions in the code was wider than documented in VERSIONING.md
2. v0.27.0 was not present.
This commit fixes both of those.
To be clear: This commit DISALLOWS VERISONS <v3.0. This should have been done in #743 but must have been missed then.
---
This sort of thing is perhaps good motivation for #888.

Sync versioning in VERSIONING.md and plugin

---

pkg/plugin/eventqueueset.go
pkg/plugin/plugin.go
pkg/plugin/prommetrics.go

Scheduler plugin has a set of queue for events (eventqueue) it receives from k8s API server. This PR adds the following set of metrics related to  eventqueue:
- `autoscaling_plugin_eventqueue_depth`: Current depth of eventqueue.
- `autoscaling_plugin_eventqueue_adds_total`: Total number of events added to eventqueue.
- `autoscaling_plugin_eventqueue_duration_seconds`: How long in seconds an item stays in eventqueue before being processed.
Inspired by [controller-runtime workqueue metrics](https://book.kubebuilder.io/reference/metrics-reference).
This is a small PR but might be easier to review it commit by commit.
Fixes #862.

plugin: eventqueue metrics

---

pkg/agent/config.go
pkg/agent/core/dumpstate.go
pkg/agent/core/metrics.go
pkg/agent/core/state.go
pkg/agent/core/state_test.go
pkg/agent/executor/core.go
pkg/agent/runner.go
pkg/api/metrics.go
pkg/api/types.go

Mostly just extracted from #737, thought it would be useful for https://github.com/neondatabase/autoscaling/pull/878#issuecomment-2033387609, and in general nice to have.
We can also rebase #750 on top of this now.
---
Changes are separated into three commits, best reviewed separately. I think they're _probably_ best merged via rebase, but I also don't want to spam the repo history :sweat_smile:
LMK what you think.

agent: Refactor metrics definitions

---

pkg/agent/core/metrics.go
pkg/agent/core/state_test.go
pkg/agent/runner.go
pkg/api/VERSIONING.md
pkg/api/types.go
pkg/plugin/run.go

Ref https://github.com/neondatabase/autoscaling/pull/737#discussion_r1458396094
Basically, with the introduction of a secondary metrics type for internal use inside the autoscaler-agent, we can get rid of the other metrics that aren't used by the scheduler plugin.
This PR is the first step (making the fields pointers and omitempty); we'll have to do a follow-up to actually remove the fields.
---
~~NB: this PR builds on #892 and must not be merged before it.~~

agent,plugin: Remove unused metrics from api.Metrics

---

pkg/api/VERSIONING.md

Also, fixes the autoscaler-agent side of the agent<->plugin versioning so it correctly says that the single current supported version is v5.0.
Must have missed this in #750.

VERSIONING.md: Bump to v0.28.0

---

pkg/plugin/run.go

The autoscaler-agent <-> scheduler plugin protocol allows the autoscaler-agent to skip the metrics field if there aren't any, which typically occurs right after the VM is created.
With the changes from #750, we assumed that .Metrics will always be non-nil, meaning that it panics when .Metrics *is* actually nil.
---
Depending on the implementation, this could have been caught by #765.

plugin: Fix nil deref on nil metrics

---

pkg/api/types.go

Another failure from #750, probably because the version slipped as the PR was open for so long.
And... another thing that #580 could have caught.

plugin: Fix HTTP 400s for old agents

---

.github/workflows/lint.yml
Makefile
neonvm/controllers/virtualmachine_controller.go
neonvm/controllers/virtualmachinemigration_controller.go
neonvm/hack/generate.sh

We currently see issues with Go >1.21 and our current controller-gen version, so a reasonable workaround is to always run with Go 1.21 instead of using whatever the system happens to have install.
Easiest way to do that is by doing the manifest generation inside a container, and `make generate` already serves that purpose, so this commit changes the generation script to *also* generate the manifests.
This commit also removes all prior occurrences of `make manifests`.
Fixes #885.

Generate manifests via `make generate`, remove `make manifests`

---

tests/e2e/image-spec.yaml
vm-examples/pg16-disk-test/image-spec.yaml

Good to keep in sync with `neondatabase/neon` because we pull in vm-monitor.
Corresponding PR there was neondatabase/neon#7598.

Update Rust: 1.74 -> 1.78

---

neonvm/runner-image-loader/daemonset.yaml

Specifically, this PR sets `maxUnavailable = 3`, which allows updating up to 3 copies in parallel.
An issue we see during rollout is that it often takes 30+ seconds to create a new neonvm-runner-image-loader on a node, and doing this for many nodes takes an unreasonable amount of time. This improves that.

neonvm-runner-image-loader: Faster rollout

---

pkg/agent/execbridge.go

Fixes #926, a follow-up for the #770.
The defintion for the VM stuckness was changed to include denied downscale request in the following commit:
commit fdf01331d233985128ac9313ad77681162871bf0
Author: Shayan Hosseini <shayan@neon.tech>
Date:   Sat Apr 6 09:25:01 2024 -0400
agent: track more liveness in vm-stuck metrics (#855)
This resulted in the consistent firing of the alert.
We should actually treat the denied downscale as part of the normal operation. This can happen due to mismatching policy of what is an acceptable level memory usage in autoscaler-agent vs vm_monitor.

agent: don't treat downscale denies as failed request

---

neonvm/controllers/metrics.go
neonvm/controllers/virtualmachine_controller.go

The need for this appeared during the investigation of an elevated level of reconciliation failures after neonvm-controllers were moved to an another node group.
Adds a single metric `reconcile_duration_seconds` with an `outcome` label
\+ relevant log messages
Part of a #916 and #918. Easier to do together because of conflicts.

neonvm: metrics for failing reconcile

---

pkg/agent/billing/billing.go
pkg/agent/config.go
pkg/billing/client.go

We can actually use the default value in prod, it simplifies configuration.
Also, tiny changes for logs and error formatting.

agent: don't check S3.Endpoint for emptyness

---

neonvm/controllers/metrics.go

Before this, failing and conflicts were counted together, which resulted in a lot of false positive alert firings because of the ever-present background of conflicts.
Part of the #932.

neonvm: separate failing/conflict for the number of failing objects

---

.github/workflows/lint.yml
cluster-autoscaler/Dockerfile
neonvm/migration.md

Fixes some usage, fixes some typos, and adds a word to the exclude list.
For some reason, codespell recently started failing. Not sure why. For example, see:
* https://github.com/neondatabase/autoscaling/actions/runs/9223395913/job/25376518993?pr=944
* https://github.com/neondatabase/autoscaling/actions/runs/9218422507/job/25361935678?pr=936

Fix codespell

---

vm-examples/pg16-disk-test/image-spec.yaml

The virtio-serial interface can be opened only once.
Consider the following scenario:
1. Process A starts writing to the serial device.
2. Process A spawns a fork, Process B. It inherits the open file descriptor.
3. Process A dies; Process B survives and preserves the file descriptor.
4. Process A is restarted but cannot open the serial device again,
causing it to crash-loop.
To fix it, we are creating FIFO special file, which supports multiple
writers, and spawning cat to redirect it to the virtio-serial.
Part of the #939.

pg16-disk-test: add mkfifo

---

neonvm/config/controller/deployment.yaml
neonvm/main.go

By default, zap enables "log sampling" when not in development mode. Unsurprisingly, we're finding that neonvm-controller logs are being dropped in production as a result of this.
I couldn't find a clean way to disable sampling without entirely constructing the `zap.Logger` from scratch, so that's what I did.
Notable changes:
* neonvm-controller's `--zap-*` flags have been removed
* neonvm-controller now hard-codes the logger config we were using before -- info log level, stack traces on panic, and ISO8601 time
More context here: https://neondb.slack.com/archives/C03TN5G758R/p1716775758112349?thread_ts=1716765298.436929
See also: #475

neonvm-controller: Rework zap setup & disable sampling

---

pkg/agent/config.go
pkg/agent/core/state.go
pkg/agent/core/state_test.go
pkg/api/vminfo.go

In short: When ScalingConfig is used to define global defaults, all required fields should be required. But when it's used to define the configuration for a VM, the "required" fields should actually be optional!
This change should allow the control plane to granularly specify only some scaling settings, while using the defaults for all others. That will make it easier to add fields to ScalingConfig (and have them actually used, at least), and reduce "spooky action at a distance" in the system.
---
Extracted from #895, thought it might be simpler/easier to handle separately.

api,agent/core: Make required ScalingConfig fields optional per-VM

---

neonvm/README.md

When first reading it, it took me a moment to realize that it's easier if you start from neonvm/hack/kernel rather than the repo root. Also, remove some extra spaces.

neonvm: Tweak README's kernel upgrade steps

---

deploy/agent/config_map.yaml
go.mod
pkg/agent/config.go
pkg/agent/core/dumpstate.go
pkg/agent/core/metrics.go
pkg/agent/core/state.go
pkg/agent/core/state_test.go
pkg/agent/executor/core.go
pkg/agent/runner.go
pkg/api/vminfo.go

Probably best to review each commit separately.
Most of the commits here are just repositioning to make the final commit, which adds LFC metrics collection, as simple as possible.
~~Builds on #892, must not be merged before then.~~

agent: Support fetching LFC metrics (but don't use them yet)

---

neonvm/controllers/catch_panic.go

While working on #963, I spotted this in the logs:
```
{"level":"dpanic","ts":"2024-06-15T18:50:47.809Z","msg":"odd number of arguments passed as key-value pairs for logging",...,"ignored key":"goroutine 501 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 ..."}
```

neonvm-controller: Fix error in panic catching middleware

---

pkg/plugin/plugin.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/plugin/trans.go
pkg/util/xact/xact.go

Trying out this approach as a potential way to make implementing overcommit (#517) easier, to avoid dealing with rounding errors when responding to the autoscaler-agents.
I think this "speculative reserve" may be a reasonable change in isolation, and reducing the number of separate implementations of the same logic should also help with overcommit (because of how it affects every single resource calculation).
Not 100% sure we want to go this route, but it's my best guess so far.
---
Tested this locally and it seemed to be ok; already fixed a couple bugs based on suspicious logs. There might be more.

plugin: Transaction-based speculative reserve and logic unification

---

cmd/autoscaler-agent/main.go

Our current debug logs are largely not useful in production, and the volume is very high.
So, let's disable debug logs for now - can individually re-enable log lines by setting them to info later, when needed.
Ref https://neondb.slack.com/archives/C03TN5G758R/p1718652664673599?thread_ts=1718210683.556539

agent: Set log level to info

---

tests/e2e/image-spec.yaml
vm-examples/pg16-disk-test/image-spec.yaml

Good to keep in sync with `neondatabase/neon` because we pull in vm-monitor.
Corresponding PR there was neondatabase/neon#8048.

Update Rust: 1.78 -> 1.79

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/apis/neonvm/v1/virtualmachine_webhook.go
neonvm/apis/neonvm/v1/zz_generated.deepcopy.go
neonvm/config/controller/deployment.yaml
neonvm/config/crd/bases/vm.neon.tech_virtualmachines.yaml
neonvm/controllers/config.go
neonvm/controllers/functests/vm_controller_test.go
neonvm/controllers/vm_controller.go
neonvm/controllers/vm_controller_unit_test.go
neonvm/controllers/vm_qmp_queries.go
neonvm/controllers/vmmigration_controller.go
neonvm/main.go
neonvm/runner/main.go
neonvm/samples/vm-example.virtio-mem.yaml
tests/e2e/autoscaling.virtio-mem/00-assert.yaml
tests/e2e/autoscaling.virtio-mem/00-create-vm.yaml
tests/e2e/autoscaling.virtio-mem/01-assert.yaml
tests/e2e/autoscaling.virtio-mem/01-upscale.yaml
tests/e2e/autoscaling.virtio-mem/02-assert.yaml
tests/e2e/autoscaling.virtio-mem/02-downscale.yaml
tests/e2e/vm-migration.virtio-mem/00-assert.yaml
tests/e2e/vm-migration.virtio-mem/00-prepare.yaml
tests/e2e/vm-migration.virtio-mem/01-assert.yaml
tests/e2e/vm-migration.virtio-mem/01-migrate.yaml
tests/e2e/vm-migration/00-assert.yaml

Adapted from #705.
This implementation is focused on making virtio-mem a drop-in replacement for our existing DIMM hotplug -based memory scaling.
As such, the externally visible differences are:
1. VirtualMachines have a new optional field: `.spec.guest.memoryProvider`
2. VirtualMachines have a new optional field: `.status.memoryProvider`
3. VirtualMachine `.status.memorySize` changes in smaller increments if using virtio-mem.
This change introduces the concept of a "memory provider", which is either "DIMMSlots" or "VirtioMem".
If a VM is created without setting the memory provider in the spec, the controller will use the default one, which is specified by its `--default-memory-provider` flag.
This will only persist for the lifetime of the runner pod. If the VM is restarted, then it may …

neonvm: Add support for virtio-mem

---

neonvm/config/controller/deployment.yaml
neonvm/controllers/config.go
neonvm/controllers/functests/vm_controller_test.go
neonvm/controllers/vm_controller.go
neonvm/controllers/vm_controller_unit_test.go
neonvm/main.go
neonvm/runner/main.go

In short: Currently we hotplug all memory as ZONE_MOVABLE. This has known issues because there are theoretical and practical limits on the ratio between ZONE_MOVABLE and ZONE_NORMAL. With `memory_hotplug.online_policy=auto-movable`, we can use the config value `memory_hotplug.auto_movable_ratio` to set a ratio of MOVABLE:NORMAL to uphold during hotplug and the kernel will Do The Right Thing™.
This change adds a new flag to `neonvm-controller` and `neonvm-runner` to set the value of this ratio: `-memhp-auto-movable-ratio`.
However, please note: The new behavior is only available for VMs using virito-mem because `memory_hotplug.auto_movable_ratio` does not count hotplugged ZONE_NORMAL DIMM slots towards the ratio, so IMO it's not worth changing the existing behavior. [1] [2] [3]
This is the …

neonvm: Use memory_hotplug.online_policy=auto-movable for virtio-mem

---

pkg/plugin/plugin.go

For calls to `(*AutoscaleEnforcer).speculativeReserve()`, the callback given to it returns a boolean which should indicate whether to actually reserve the Pod.
When handling Score, we were returning true (which we should never do in Score) exactly when the placement would have been over-budget. This meant that pods would be recorded on an over-full node early in the scheduling flow, disagreeing with the core scheduler, which causes even more calls to Score that we'd think are over-budget, exacerbating the problem.
ref https://neondb.slack.com/archives/C0798QG4D0T/p1719016313787749?thread_ts=1719014348.041469

plugin: Fix Score reserving when over-budget

---

go.mod
go.sum
neonvm/hack/tools.go

It was originally added in neondatabase/neonvm#4 in order to track the controller-tools version in go.mod, but we switched away from that and started storing it as an env var in the makefile with neondatabase/neonvm#8 (i.e., it's been unused for _a while_).
Noticed while reviewing #928.

neonvm: Remove hack/tools.go

---

neonvm/Dockerfile
neonvm/config/controller/deployment.yaml
neonvm/config/kustomization.yaml
neonvm/runner-image-loader/daemonset.yaml

For neondatabase/cloud#10177, we want to be able to override the neonvm-runner image that the controller uses *after* it's built and the YAML is generated.
To do this, we need to actually define the runner image in the YAML somwhere.
This PR:
1. Moves VM_RUNNER_IMAGE env var from the neonvm-controller dockerfile into its Pod spec.
2. Adds neonvm-runner-image-loader to neonvm.yaml (required for 1)
---
Tested compared to previous main the difference in the YAMLs when using v0.32.0 as the tag, and the diff to neonvm.yaml (aside from adding the image loader) was just the env var in the expected place.

neonvm: Move runner image env var into YAML

---

Makefile
neonvm/tools/vxlan/controller/main.go

in reponse to https://github.com/neondatabase/autoscaling/pull/994#discussion_r1654771673 this explicitly specifies `GOOS=linux` and `//go:build linux` in places where I had IDE/golang complain on unsupported architecture.
https://github.com/neondatabase/cloud/issues/14786

infra/build: explicitly specify linux OS

---

neonvm/tools/vm-builder/files/inittab

It is not possible for all of the log collectors to correctly strip them out.
```
vector --help | grep '\-\-color' -A 5
--color <COLOR>
Control when ANSI terminal formatting is used.
By default `vector` will try and detect if `stdout` is a terminal, if it is ANSI will be enabled. Otherwise it will be disabled. By providing this flag with the `--color always` option will always enable
ANSI terminal formatting. `--color never` will disable all ANSI terminal formatting. `--color auto` will attempt to detect it automatically.
[env: VECTOR_COLOR=]
[default: auto]
[possible values: auto, always, never]
```

vm-builder: don't use ANSI terminal formatting in vector logs

---

neonvm/runner/main.go
neonvm/tools/vm-builder/files/vminit

The kernel prints a few lines like these to the kernel log at startup:
[    0.886717] ext3: Unknown parameter 'mode'
[    0.887279] ext2: Unknown parameter 'mode'
[    0.887595] ext4: Unknown parameter 'mode'
[    0.887906] squashfs: Unknown parameter 'mode'
It's because the runtime, ssh-authorized-keys image and any ConfigMaps or Secrets are iso9660 images, mounted with commands like this:
/neonvm/bin/mount -o ro,mode=0644 $(/neonvm/bin/blkid -L ssh-authorized-keys) /mnt/ssh
Because we don't specify the filesystem type, the command tries different filesystems until it finds one that recognizes it. You get the errors, because "mode" option is not supported by those other filesystems that the command tries first.
The messages are harmless, but add noise to the logs. To silence them, …

Silence "Unknown parameter 'mode'" messages at neonvm startup

---

.github/workflows/lint.yml
go.mod
neonvm/apis/neonvm/v1/virtualmachine_types.go
pkg/api/types.go

Bundled together to save time. To be merged as a rebase.
Part of the #921

Developer experience changes to make tooling work

---

neonvm/runner/Dockerfile
neonvm/samples/vm-example/Dockerfile
neonvm/tools/vm-builder/files/Dockerfile.img
neonvm/tools/vm-builder/files/helper.move-bins.sh
neonvm/tools/vm-builder/main.go
neonvm/tools/vxlan/Dockerfile
vm-examples/pg16-disk-test/image-spec.yaml

Part of #900; extracted from #1008.
This PR:
1. Replaces the shared library copying in vm-builder with a script to handle that for us, using the output from `ldd`
2. Bumps the alpine versions everywhere to 3.17
The two parts are in two separate commits. It probably makes sense to merge them via rebase-and-merge.
Notably, the bump to 3.17 includes bumping QEMU from 7.0.0 to 7.1.0.

Update alpine base images: 3.16 → 3.17

---

deploy/agent/config_map.yaml
pkg/agent/dispatcher.go
pkg/agent/executor/exec_plugin.go
pkg/agent/runner.go

Try to reduce some very common logs:
- Change interval for recurring scheduler requests (5s -> 15s)
- Log 1-2 log entries instead of 4 for each scheduler request
- Log successful healthchecks only once per 10 requests
- Do not log "Making metrics request to VM", same info as in "Updated metrics"
ref https://github.com/neondatabase/cloud/issues/15591
ref https://github.com/neondatabase/cloud/issues/15605

agent: Reduce logging

---

pkg/agent/core/state.go

Noticed while reviewing a new test in #983 that triggers this warning.

agent/core: Fix "but but" in warning message

---

neonvm/controllers/metrics.go
neonvm/controllers/vm_controller.go

Requeueing every second for every VM places a lot of load on our systems, and results in a lot of logs where nothing changed.
Currently we do it because there can be changes to QEMU that we won't pick up otherwise. Those shouldn't happen during the "Running" phase though, so we can reduce the requeue frequency from "every 1s" to "every 15s" for that.
There's a similar thing with Pending VMs -- either we're waiting on the pod to start (in which case we'll be notified anyways), or we're waiting on neonvm-runner/QEMU to start (in which case we'll retry from errors). So we can delay retrying there as well.
To compensate for these changes, we add a "requeueAfter" field to the "Successful reconciliation" log line so that we can still tell if a gap between reconciles is unusually long.
In the …

neonvm-controller: Requeue after 15s if Pending or Running

---

neonvm/apis/neonvm/v1/virtualmachine_webhook.go
neonvm/apis/neonvm/v1/virtualmachinemigration_webhook.go
neonvm/apis/neonvm/v1/webhook_suite_test.go
neonvm/config/controller/deployment.yaml
neonvm/controllers/config.go
neonvm/controllers/functests/vm_controller_test.go
neonvm/controllers/vm_controller_unit_test.go
neonvm/controllers/webhook.go
neonvm/main.go

Copying the second commit's message:
> This flag is a new escape hatch to allow arbitrary updates to an object, bypassing the webhook update validation (but still within the CRD).
>
> Sometimes when trialing things on staging, we end up with objects in a bad state that can't be deleted because update validation fails when removing the finalizer (e.g., due to destructive CRD changes).
This PR comes in two parts:
1. Refactoring — moving webhook setup in to the controller, so that it's easier to control from there
2. Feature — adding the `--skip-update-validation-for` flag to neonvm-controller, and using our newfound control over webhooks to skip the update webhook for objects named with the flag.
_Probably_ worth merging via rebase-and-merge.

neonvm-controller: Add '--skip-update-validation-for' 

---

neonvm/apis/neonvm/v1/virtualmachine_types.go

neonvm/api: Collapse metadata consts to single section

---

neonvm/hack/generate.sh

The rest of the file uses spaces - didn't notice the change in #919.
Extracted out from #905.

neonvm/hack/generate.sh: Replace tabs with 4 spaces

---

neonvm/apis/neonvm/v1/virtualmachine_webhook.go

In the original PR (#970), I'd intended to make this field mutable and added a comment about it, but forgot to actually remove it from the list of immutable fields.
*Probably* doesn't matter much, but IMO it's worth cleaning up.

neonvm-controller: Fix immutable `.spec.guest.memoryProvider`

---

neonvm/runner/Dockerfile
neonvm/samples/vm-example/Dockerfile
neonvm/tools/vm-builder/files/Dockerfile.img
neonvm/tools/vm-builder/main.go
neonvm/tools/vxlan/Dockerfile
vm-examples/pg16-disk-test/image-spec.yaml

Part of #900; extracted from #1008.
Notably, this PR also bumps QEMU in neonvm-runner: 7.1.0 -> 8.0.5
The QEMU 8.0 changelog is here: https://wiki.qemu.org/ChangeLog/8.0

Update alpine base images: 3.17 → 3.18

---

pkg/agent/runner.go

Currently, we sometimes get neonvm request failure metric labels like
[error: virtualmachines.vm.neon.tech "compute-rapid-wave-a45g5t85" not found]
Thankfully *in practice* the rates are very low, so it's not a big issue, but in theory we could accidentally blow up our metrics storage if some issue was causing our requests to fail for every object in a way that included the object name.
So this PR makes sure we filter out the name.

agent: Don't include VM name in neonvm request metric labels

---

.git-blame-ignore-revs

Keeps the blame nice in that area without much cost otherwise.

.git-blame-ignore-revs: Add commit from #1018

---

pkg/plugin/trans_test.go

Found myself wanting these as part of #517, and it's been on the todo list for a while from #764.
Some of the tests currently aren't working as expected. They are configured to pass, acting as if the undesired outcome is expected. The bugfix will be in a separate PR.
---
**Notes for review:** There's still other methods I'd like to get test coverage for, so I think this doesn't completely fulfill #764. But, IMO it's a good start, at least -- and should definitely be useful for #517 :)

plugin: Add basic unit tests for resourceTransitioner

---

.github/workflows/test.yaml

ci: save cover.out profile-file as run artifact to enable using it as input for the reporter
Related to https://github.com/neondatabase/cloud/issues/16669

ci: save cover.out profile as run artifact

---

.github/workflows/test.yaml

I need this PR to be merged to trigger test run on main branch to get the artifacts uploaded. After the https://github.com/neondatabase/cloud/issues/16669 is closed, those artifacts will be used as baseline for coverage reports.

ci: temporary trigger test run on all main merges

---

neonvm/Dockerfile
neonvm/hack/kernel/Dockerfile.kernel-builder
neonvm/runner/Dockerfile
neonvm/samples/vm-example/Dockerfile
neonvm/tools/vxlan/Dockerfile
tests/e2e/image-spec.yaml
vm-examples/pg16-disk-test/image-spec.yaml

Relatively recently, docker has introduced a "linter" for dockerfiles: https://docs.docker.com/reference/build-checks/
I went through all the files (using `for f in $(find . -name Dockerfile); do docker build --check -f $f . ; done`) and fixed found warnings. 
A newer version of ` docker/build-push-action` will report such warnings as build annotations (see https://github.com/neondatabase/autoscaling/pull/1041/files, scroll down to "Unchanged files with check annotations")

Fix warnings in dockerfiles

---

.github/workflows/test.yaml

`technote-space/get-diff-action` prevents from running tests if no changes in the code files were pushed. We need to bypass that behavior on main branch to store artifacts with baseline coverage.

ci: trigger test run on all main branch merges

---

.github/actions/set-docker-config-dir/action.yml
.github/workflows/build-images.yaml
.github/workflows/build-test-vm.yaml
.github/workflows/check-ca-builds.yaml
.github/workflows/e2e-test.yaml
.github/workflows/vm-kernel.yaml

In several workflows, we have repeating code, which is separated into 2 steps:
```bash
mkdir -p $(pwd)/.docker-custom
echo DOCKER_CONFIG=$(pwd)/.docker-custom >> $GITHUB_ENV
...
rm -rf $(pwd)/.docker-custom
```
Such copy-paste is prone to errors; for example, in `e2e-tests` job, we do not delete this file, which could potentially affect the following jobs on the runner.
Port changes from https://github.com/neondatabase/neon/pull/8676

CI: add `actions/set-docker-config-dir` to set DOCKER_CONFIG

---

README.md

The link was outdated. Also it was marked as "For Neon folks..." but external people tried to access it anyway. We have all the internal documentation in the Neon engineering book, now.

Removed link to release procedure

---

.github/workflows/approved-for-ci-run.yml

Currently, PRs from external contributors (or rather PRs created from forks, even from neondatabase members) will fail because they don't have access to secrets.
Use the same approach as we follow in `neondatabase/neon` repo ([link](https://github.com/neondatabase/neon/blob/2078dc827b0495703f9ddcb8ea944df3a4fe9c41/.github/workflows/approved-for-ci-run.yml)).
Here's the relevant README part:
---
_An instruction for maintainers_
- Review the PR
- If and only if it looks **safe** (i.e. it doesn't contain any malicious code which could expose secrets or harm the CI), then:
- Add `approved-for-ci-run` label to the PR
Repeat all steps after any change to the PR.
- When the changes are ready to get merged — merge the original PR (not the internal one)
GitHub Actions triggered by the …

CI: handle external PRs with `approved-for-ci-run` label

---

pkg/plugin/plugin.go
pkg/plugin/state.go

plugin: add warning log message for the pods with assigned scheduler, nodeName or nodeSelector
closes #93

plugin: add warning log message for the pods with assigned scheduler

---

neonvm/tools/vm-builder/files/sshd_config
tests/e2e/vm-ssh/00-assert.yaml

Change sshd_config to let scp command work outside of the box.
Add e2e test for scp command.
The root cause for non-working scp was config directive ```Subsystem	sftp	/usr/lib/ssh/sftp-server```
We don't have that binary in the guest vm. There are 2 ways to fix it - either add binary during the image build or change the configuration to use embedded realization of the sftp subsystem. I chose the second option since it is a bit easier.
More context: https://man.openbsd.org/sshd_config#Subsystem
Closes #930

vm-builder: change sshd config to use internal-sftp subsystem

---

pkg/plugin/trans.go
pkg/plugin/trans_test.go

Noticed as part of #1023.
The current (incorrect) behavior is that `forceApprovalMinimum` is relative to the current resources when it's actually intended (and documented as such) to be absolute. So in practice, we're approving autoscaler-agent requests that we shouldn't -- allowing resource increases above the node maximum when we don't need to.
`forceApprovalMinimum` was added as part of #936, and presumably we didn't catch this because of the lack of unit tests.

plugin/trans: Fix over-allowing from forceApprovalMinimum

---

Makefile
neonvm/hack/Dockerfile.generate
neonvm/hack/generate.sh
neonvm/hack/kube_codegen.patch

The new script is a completely different format :(
See e.g. kubernetes/kubernetes#117262 for examples.
Changes required here:
1. Passing through the git directory, even when using worktrees, because kube_codegen.sh directly uses git for things (git grep, git ls-files)
2. Patching kube_codegen.sh because it expects that our types files are exactly `types.go`, but we have `virtualmachine_types.go` and `virtualmachinemigration_types.go`.
There are further breaking changes in later kubernetes versions, but we don't need to deal with those quite yet.
Extracted from #1048.
---
**Notes for review:** Please check it runs locally.
**Do not approve this PR unless you have checked that `make generate` works for you.**

neonvm: Replace deprecated generate-groups.sh with kube_codegen.sh

---

neonvm/hack/kernel/Dockerfile.kernel-builder
neonvm/runner/Dockerfile
neonvm/samples/vm-example/Dockerfile
neonvm/tools/vm-builder/files/Dockerfile.img
neonvm/tools/vm-builder/main.go
neonvm/tools/vxlan/Dockerfile
vm-examples/pg16-disk-test/image-spec.yaml

Part of #900; extracted from #1008.
Notably, this PR also bumps QEMU in neonvm-runner: 8.0.5 -> 8.1.5
The QEMU 8.1 changelog is here: https://wiki.qemu.org/ChangeLog/8.1

Bump alpine base images: 3.18 -> 3.19

---

.github/workflows/lint.yml
.golangci.yml
neonvm/controllers/vm_controller.go
neonvm/controllers/vmmigration_controller.go
pkg/agent/dumpstate.go
pkg/api/versionutils.go
pkg/api/vminfo.go
pkg/util/time.go

Update `golangci-lint` to 1.60.3 and fix new warnings
A prerequisite for go 1.23[0]
- [0] https://github.com/neondatabase/autoscaling/pull/1065

CI(lint): golangci-lint 1.60.3

---

pkg/agent/billing/billing.go
pkg/agent/billing/queue.go
pkg/agent/core/state.go
pkg/api/types.go
pkg/api/versionutils.go
pkg/plugin/plugin.go
pkg/plugin/trans.go
pkg/util/arith.go

Go 1.22 added the standard min & max functions. Now that #1035 has been merged, we should switch to these instead of replicating the same functionality in pkg/util.
ref https://github.com/neondatabase/autoscaling/pull/1067#discussion_r1749364205
---
**Note:** This PR builds on #1067 and shouldn't be merged before it.

Replace util.{Min,Max} with stdlib {min,max}

---

.github/workflows/build-images.yaml
Dockerfile.go-base
Makefile
build/autoscale-scheduler/Dockerfile
build/autoscaler-agent/Dockerfile
neonvm/Dockerfile
neonvm/runner/Dockerfile
neonvm/tools/vxlan/Dockerfile

It *dramatically* reduces the amount of time it takes to re-run image building if the set of packages used hasn't changed. It's hard to get an objective measurement (because we do get *some* caching from being careful what we add), but:
On my machine, for a rebuild after a change in 'pkg/api', it reduces `make docker-build` time from 249s -> 22s.
And, it also slightly improves the time it takes to run a clean build. After `docker system prune -af`, it reduces `make docker-build` on my machine from 345s -> 126s.

Use go-chef for image builds

---

deploy/agent/config_map.yaml
pkg/agent/core/goalcu.go
pkg/agent/core/metrics.go
pkg/agent/core/state.go
pkg/agent/core/state_test.go
pkg/api/vminfo.go

In short: In addition to scaling when there's a lot of memory used by postgres, we should also scale up to make sure that enough of the LFC is able to fit into the page cache alongside it.
To answer "how much is enough of the LFC", this PR takes the minimum of the estimated LFC working set size (from window size) and the cached memory (from the `Cached` field of `/proc/meminfo`, via vector's host metrics).
This PR also adds the `memoryTotalFractionTarget` field to the scaling config, serving a similar purpose to `memoryUsageFractionTarget`, but applying to the total of memory usage and cached data.
This PR is part of #1030 and must be deployed before the vm-monitor changes in order to make sure we don't regress performance for workloads that are both memory-heavy and rely on LFC being in …

agent/core: Use cached LFC for memory scaling signal

---

neonvm/tools/vm-builder/files/Dockerfile.img

neonvm-runner does need qemu-img, but that's why the neonvm-runner Dockerfile does "apk add qemu-img". We don't need it in both images.

vm-builder: Remove qemu-img from built vm images

---

neonvm/tools/vm-builder/files/Dockerfile.img

The builder stage doesn't need anything from runtime, and previously only depended on 'vm-runtime' because of the installed disk-related binaries, but installing those has already been moved into 'builder' with #1077.

vm-builder: Use fresh base for 'builder' stage

---

neonvm/main.go

We currently aren't doing this, and it leads to 30s+ scaling operations when we deploy neonvm.
---
**Notes for review:** I want to also get rid of the `srv` stuff (I think that'll make this simpler), but that's probably best left for a follow-up PR :)

neonvm-controller: Release leader election lease on exit

---

.github/workflows/pr-format-verification.yml

Loosely adapted the workflow from what we have in neondatabase/cloud, but with the format changed to match what we've previously done in this repo.
As currently implemented, PR titles would _generally_ be required to look like:
```
component: Short message
```
or, at its most flexible:
```
component1/subsystem,component2/subsystem: Short message
```
There's two escape hatches:
1. If the PR title starts with `Revert: "`
2. If you include <code>\<!-- affects all --\></code> in the PR body — in case your PR is more broad
---
**Some context:**
1. When looking at recent commits, I find it very useful to be able to quickly determine the scope of previous changes.
3. Historically, the existing PR title format was maintained as a "best effort" sort of situation, with some exceptions slipping …

CI: Add PR title checker

---

.github/workflows/vm-kernel.yaml

This updates some comments from changes in #961 and #1073.

ci/vm-kernel: Fix outdated comments

---

.github/workflows/report-workflow-stats.yml

Move action repo from personal account to org, and bump to last version.

ci: gh-workflow-stats-action: bump version and move action repo

---

.github/workflows/vm-kernel.yaml

In PRs, it is incorrect to use the last commit sha as a cache tag for a docker kernel image.
By default, on `pull_request`, `actions/checkout` pulls a fake merge commit (PR into the default branch), and potentially an outdated kernel image from the cache might be used in a PR (if `main` has some changes in the kernel, and PR doesn't include it yet).
This PR changes the logic from using the last commit sha to using a hash from `neonvm-kernel` directory content and the workflow file itself.

ci/vm-kernel: change CACHE_TAG calculation

---

tests/e2e/vm-neonvmd/00-assert.yaml

Noticed in the #1111 e2e logs that vm-neonvmd always passes 🤦 Haven't noticed that before because I locally tried it in my ARM working branch with different builder image.

e2e-tests: fix ps path in vm-neonvmd test

---

neonvm-controller/cmd/main.go
pkg/neonvm/controllers/config.go
pkg/neonvm/controllers/functests/vm_controller_test.go
pkg/neonvm/controllers/vm_controller.go
pkg/neonvm/controllers/vm_controller_unit_test.go

Multiple commits, their descriptions:
- neonvm: recreate the pod for VM even if the older pod still exists
We have previously assumed running multiple pods for one VM is
dangerous.
We now believe it should be fine, even if the old pod still tries to
continue operating. What would happen is that the new pod would take
over the safekeepers quorum, leaving the old one to disconnect and
shutdown.
- neonvm: check if deletion timestamp is in the past
If we are passed the mark of the deletion timestamp, it means
the deletion is stuck, and we should consider the pod failed anyway.
Possible reasons for this are:
1. Node is down.
2. Pod is stuck pulling the image from the container registry.
- neonvm: add explicit "node not ready" tolerations with 30s grace period
By default they are 300s (5m), …

neonvm-controller: improve node failure reaction speed

---

.github/workflows/release.yaml

commit 5e48a1bb0c31953e077335e85419474f3067949c (HEAD -> oleg/fix-release, origin/oleg/fix-release)
Author: Oleg Vasilev <oleg@neon.tech>
Date:   Fri Oct 18 17:06:20 2024 +0200
ci/release: reflect moving of vmscrape.yaml from deploy/ (#1117)
This was done in the following commit:
a2f53e32 Flatten & unify component structure (#961)
Signed-off-by: Oleg Vasilev <oleg@neon.tech>
commit b319c0b8d2d59031b3407f53b69d65af3f562101
Author: Oleg Vasilev <oleg@neon.tech>
Date:   Fri Oct 18 16:09:08 2024 +0200
ci/release: don't put vm-builder binary into root dir (#1117)
Since last release, vm-builder directory was moved into root
of the repo. Because of this, we can't download vm-builder during
release pipeline, this name is already occupied by a dir.
This was caused by the following commit:
a2f53e32 …

Release pipeline fixes

---

.github/workflows/test.yaml

The action has some hardcoded event type filter which doesn't let us using base profile from non main

ci: call go-coverage-report only if base is the main branch

---

pkg/agent/core/revsource/revsource.go

Index equal to length should also result in an early return.

agent/revsource: fix out-of-bounds error

---

.github/workflows/vm-example.yaml

[`vm-example`](https://github.com/neondatabase/autoscaling/actions/workflows/vm-example.yaml) workflow is broken for some time due to the lack of `daemon:dev` image:
```
Step 3/39 : FROM daemon:dev AS neonvm-daemon-loader
2024/11/05 04:44:24 pull access denied for daemon, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
This PR fixes it by running `make docker-build-daemon` command in the job.

ci/vm-example: fix the workflow

---

Makefile
pkg/neonvm/controllers/vm_controller.go
pkg/neonvm/controllers/vmmigration_controller.go

Best viewed by-commit. 
Will be merged with rebase.
Part of the #733.

neonvm-controller: refactor doReconcile

---

autoscaler-agent/cmd/main.go
pkg/agent/billing/billing.go
pkg/agent/billing/indexedstore.go
pkg/agent/billing/prommetrics.go
pkg/agent/core/testhelpers/construct.go
pkg/agent/globalstate.go
pkg/agent/watch.go
pkg/api/types.go
pkg/api/vminfo.go
pkg/neonvm/ipam/ipam.go
pkg/plugin/ARCHITECTURE.md
pkg/plugin/config.go
pkg/plugin/dumpstate.go
pkg/plugin/plugin.go
pkg/plugin/run.go
pkg/plugin/state.go
pkg/plugin/watch.go
pkg/util/vmlogfield.go

Within neonvm-controller, we're consistently using `vmv1` to refer to the `.../apis/neonvm/v1` import, but elsewhere we're using `vmapi` instead.
`vmv1` is closer to the typical kubernetes imports like `corev1` and `metav1`, even if it doesn't exactly match the import path.
---
**Notes for review:** Low priority, been on my todo list for a while and I figured that #995 was a good enough excuse to do it. Also, this is probably a good candidate to add to `.git-blame-ignore-revs` after merging, because otherwise it's a lot of noise.

Use 'vmv1' for neonvm API import everywhere

---

autoscaler-agent/config_map.yaml
pkg/agent/core/goalcu.go
pkg/agent/core/goalcu_test.go
pkg/agent/core/metrics.go
pkg/agent/core/state_test.go
pkg/api/vminfo.go

ZoneLoadAverage compares abs(load1 - load5) against two thresholds, to determine if compute is in one of 3 zones:
- "stable zone", where load5 is used to inform the target CU value
- "scaling zone", where load1 is used to inform the target CU value
- "mixed zone", where load1 and load5 is blended to get an intermediate value
The thresholds are computed as a percentage of a load5, the percentage is set by two new values: `cpuStableZoneRatio` and `cpuMixedZoneRatio`. 
For example, for the `cpuStableZoneRatio = 0.25`,  `cpuMixedZoneRatio = 0.25` and `load5 = 8`, we'd get:
- stable zone when `abs(load5 - load1) < 2` <=> `6 < load1 < 10`
- mixed zone when `2 < abs(load5 - load1) < 4` <=> `4 < load1 < 6` or `10 < load1 < 12`.
- scaling zone otherwise
Similar algorithm is described in …

agent/goalcu: implement ZoneLoadAverage 

---

neonvm-kernel/Dockerfile.kernel-builder

Update ubuntu:23.10 to the LTS version ubuntu:24.04
Closes #1154

neonvm-kernel: update ubuntu builder image to LTS

---

tests/e2e/image-spec.yaml
vm-examples/pg16-disk-test/image-spec.yaml

We haven't updated in a while, 1.83 was recently released, and we should keep up-to-date with `neondatabase/neon` so that vm-monitor in CI continues to work as expected.
See also neondatabase/neon#9926
---
~~**Edit:** Seems like the 1.83 images aren't on dockerhub yet? Leaving this until then.~~

tests,examples: Bump Rust 1.79 -> 1.83

---

Makefile
neonvm-daemon/Dockerfile

Probably an inadvertent merge conflict between #1090 and #989 meaning we accidentally weren't using go-chef for neonvm-daemon.
Noticed this while working on #1163 locally and saw that it was re-downloading all of the dependencies for neonvm-daemon every time, even though I was making changes in the scheduler and the dependencies hadn't changed.

neonvm-daemon: Use go-chef in Dockerfile

---

.github/workflows/build-images.yaml
Makefile
neonvm-vxlan-controller/Dockerfile

Download target-specific binary to work as multiplatform image. Related to #850

vxlan-controller: fix hardcoded urls to use TARGET_ARCH

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/config/crd/bases/vm.neon.tech_virtualmachines.yaml

In practice this is limiting the maximum size of our computes, even though memory slots aren't physically used since we switched to virtio-mem.
ref neondatabase/cloud#18281

neonvm: Bump max mem slots to 512

---

.github/workflows/build-images.yaml

It's causing the release workflow to fail ([link](https://github.com/neondatabase/autoscaling/actions/runs/12207391166/job/34058771593)), and at this point it's not necessary because the neonvm-daemon image is only needed when running vm-builder to build VM images (rather than e.g., being required at runtime).
Follow-up to #1168.

ci/build-images: Don't push neonvm-daemon to ECR

---

neonvm-runner/Dockerfile
neonvm-runner/cmd/main.go
pkg/neonvm/controllers/vm_controller.go
tests/e2e/autoscaling.cpu-sys-fs-state-scaling/00-assert.yaml
tests/e2e/autoscaling.cpu-sys-fs-state-scaling/00-create-vm.yaml

Modify qemu arguments to run VM on arm machine
#1080

neonvm-runner: arm support

---

.github/workflows/lint.yml

Extracted from #1163, where `gci` incorrectly groups the `"iter"` import away from other stdlib pacakges, because it was only added in Go 1.23.

golangci-lint: Bump v1.60.3 -> v1.62.2

---

pkg/neonvm/controllers/vm_controller.go

This commit is relatively straightforward: In the neonvm-runner init container, switch from copying the root disk into `/vm/images` to *moving* it there.
Copying necessarily causes a lot of disk writes, but moving may not. If the init container's `disk.qcow2` is on the same underlying filesystem as the `/vm/images` volume, then the kernel MAY do the move very efficiently.
To be clear: I'm not totally sure whether this will help — it may be that moving files out of an overlayfs still requires copying. But if it helps, it could dramatically reduce our disk IO usage when many computes are started at once. And even if it doesn't help, it's probably a better default to move instead of copying.

neonvm: mv root disk from init container, not cp

---

neonvm/apis/neonvm/v1/pod_helpers.go
pkg/neonvm/controllers/vm_controller.go
pkg/neonvm/controllers/vmmigration_controller.go
pkg/util/k8s.go

Extracted out of #1163, as suggested by https://github.com/neondatabase/autoscaling/pull/1163#discussion_r1890406226 and https://github.com/neondatabase/autoscaling/pull/1163#issuecomment-2556855781.
These are _mostly_ three unrelated commits among the broader theme of making stronger guarantees about what the Pods look like.
I'm intending to merge via rebase-and-merge to keep these commits separate.

neonvm: Small changes for stateless scheduler

---

Makefile
neonvm-runner/cmd/cgroup.go
neonvm-runner/cmd/disks.go
neonvm-runner/cmd/httpserver.go
neonvm-runner/cmd/main.go
neonvm-runner/cmd/net.go

I was looking at trying to implement some changes to what neonvm-runner puts in the ISO 9660 filesystem, and quickly began hitting #1184, so decided to make some changes to fix that.
The commits are basically just what the subject messages say.
---
It's worth noting that these changes are kind of only surface-level; I think there's deeper structural changes that we should make so neonvm-runner can be easier to maintain and extend, but I'm not entirely sure what that should look like, and just breaking it up into separate files seemed less objectionable.

neonvm-runner: Small cleanups

---

neonvm/config/multus-aks/kustomization.yaml
neonvm/config/multus-aks/secret.yaml

TL;DR [uses this](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#create-token) to give multus a token that won't expire - therefore, preventing the issue with its token expiring. 
Essentially, we manually create a token, then mount it where the automatically created token would normally be, and everything works as expected (AFAICT, but pods are being scheduled and multus still works after an hour - so a win is a win)
Long story I'm writing up as to why this is needed and what we should really do about it.

Give multus a non expiring token

---

Makefile

Use KERNEL_TARGET_ARCH and TARGET_ARCH based on the `uname -r` instead of always relying on manually passed values. This should enable using current instruction for local development without any changes.

makefile: autodetect target arch for builds

---

neonvm/config/multus-aks/secret.yaml

Small fixup for https://github.com/neondatabase/autoscaling/pull/1201 - I realized that when testing I was in the `kube-system` namespace already, but when applying the patch normally with `kustomize` it would create the secret in the `default` namespace. 
It's fixed in production, but not in the repo.

Specify namespace so secret is applied in the right place

---

Makefile

Quick fix for a bug introduced by #1197.
Since TARGET_ARCH is defined as global variable in Makefile, no need to pass it as target variable.

makefile: fix target arch variable for example-vms

---

pkg/neonvm/controllers/vmmigration_controller.go

We need to sync CPUs only if we have QMP mode active. For sysfs scaling CPU state should sync automatically.
Related to #850 and #1111

neonvm: handle sysfs scaling mode in migrations

---

cluster-autoscaler/Dockerfile

Release workflow failed due to this issue, here: https://github.com/neondatabase/autoscaling/actions/runs/12998905924/job/36253091744#step:25:410
Missed it in #1161, per the [upgrade checklist](https://github.com/neondatabase/autoscaling/tree/main/cluster-autoscaler#version-upgrade-checklist).

cluster-autoscaler: Fix go image version in dockerfile

---

neonvm/config/multus-aks/secret.yaml

Follow-up to #1202, namespace should be under the metadata field. Without this, kubectl says `Warning: unknown field "namespace"` and tries to create the secret in the default namespace (not what we want)

neonvm/multus-aks: Fix ineffectual secret namespace

---

pkg/agent/config.go
pkg/agent/scalingevents/clients.go

Must have forgotten to include handling for azure blob storage clients as part of #1107; this change adds it.
While we're at it, unify the config checking for azure blob between billing and scaling events (like we have for S3), and also start checking `prefixInContainer` where we weren't before.

agent: Add azure blob support for scaling events

---

pkg/agent/core/goalcu_test.go

Use assert.InDelta to compare float values in tests. Using direct comparison fails due to different rounding-up behavior on arm and amd.

agent/goalcu: fix unit test on arm

---

pkg/agent/billing/prommetrics.go
pkg/agent/entrypoint.go
pkg/agent/globalstate.go
pkg/agent/scalingevents/prommetrics.go
pkg/plugin/plugin.go
pkg/reporting/sink.go
pkg/util/watch/metrics.go

This is a deeper fix for #1231: We wouldn't need to remember to register metrics if they were always registered during construction.
So this is a codebase-wide switch from patterns like:
```go
func NewMetrics() Metrics {
// ...
}
func (m Metrics) MustRegister(reg prometheus.Registerer) {
// ...
}
```
to patterns like:
```go
func NewMetrics(reg prometheus.Registerer) {
// ...
}
```
As it stands, this only really affects the autoscaler-agent.
---
~~**Note: This PR builds on #1231 and must not be merged before it.**~~

Always register metrics during construction

---

.github/workflows/build-images.yaml
.github/workflows/vm-kernel.yaml

Add sbom and provenance fields equal false to
docker/build-push-action calls to avoid
issues with copying images to ECR
#1251
More context in discussion https://github.com/neondatabase/autoscaling/pull/1138#discussion_r1945634996

ci: add sbom and provenance fields equal false

---

.github/workflows/e2e-test.yaml

Use 'failure' instead of 'failed'

ci: fix fail status in conclusion job

---

go.mod
neonvm-daemon/cmd/main.go
neonvm-runner/cmd/disks.go
neonvm-runner/cmd/main.go
neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/apis/neonvm/v1/zz_generated.deepcopy.go
neonvm/config/crd/bases/vm.neon.tech_virtualmachines.yaml
pkg/util/checksum.go
tests/e2e/vm-secret-sync/00-assert.yaml
tests/e2e/vm-secret-sync/00-create-vm.yaml
tests/e2e/vm-secret-sync/01-assert.yaml
tests/e2e/vm-secret-sync/01-update-secret.yaml

For #1213 I need the renewed certificate secret to be updated within the vm. 
It's ok if there's some lag on this synchronisation as certificates are renewed with generous amount of time left until expiry.
Design:
neonvm-runner will subscribe to inotify events for a specific list of secrets. If an event is detected, the secret contents are sent in a http request to neonvm-daemon.
The files will be owned by the daemon user, and read-only by postgres.
If there's an error when uploading, then there's a secondary loop every 5 minutes to catch up, using a checksum to compare.
We mirror kubernetes and use atomicwriter to atomically update multiple files in the secret.
Useful links:
https://ahmet.im/blog/kubernetes-secret-volumes-delay/
https://ahmet.im/blog/kubernetes-inotify/
Some discussion …

neonvm: continuous synchronisation of files in pod/vm

---

Makefile

More convenient for local dev.

Makefile: separate coverage-html into a separate step

---

neonvm-runner/cmd/main.go
neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/config/crd/bases/vm.neon.tech_virtualmachines.yaml
pkg/neonvm/controllers/vm_controller.go
tests/e2e/vm-tls/00-assert.yaml

While testing, I noticed that the certificates were not getting copied inside the VM, but they were available in the pod.
I remember thinking about it, but it seems like I forgot that the `mounts.sh` still needs to `mkdir -p ...` the directory for the secrets.
In the process, I decided to make the mount dir configurable and add an additional test to check the file exists in the VM.

neonvm: ensure the TLS mount directory is available in the VM

---

neonvm-runner/cmd/disks.go
neonvm-runner/cmd/main.go
neonvm-runner/cmd/net.go
vm-builder/files/set-disk-quota.sh
vm-builder/files/vminit

This PR disables verbose logging for repetitive startup logs, such as kernel debug boot logs.
It sets default kernel loglevel as INFO (https://docs.kernel.org/core-api/printk-basics.html) and vminit script sets loglevel back to DEBUG after booting has completed.
The full list of changes can be seen in commit messages.
Startup logs before this PR (559 lines): https://gist.github.com/petuhovskiy/cfa0e7654cd25b37247694a33a9d556b
Startup logs after this PR (123 lines): https://gist.github.com/petuhovskiy/a85a7dad7bb4015d2f1f33fcd6cce9fd
Closes https://github.com/neondatabase/cloud/issues/19678

neonvm-runner: Reduce startup logs

---

pkg/plugin/metrics/metrics.go
pkg/plugin/metrics/node.go

Fixes #1276.
Currently, the way we update these node metrics is by removing all the old ones, then adding back the current values. We do it that way so that the old values can be cleaned up when there's label changes.
However: if metrics are scraped in between removing the old and adding the new, we can end up with single-datapoint gaps for one node at a time.
So to fix this, we should avoid removing the old metrics if and only if the labels are unchanged -- which we can check just by storing the previous labels we used.

plugin/metrics: Update metrics in-place when possible

---

.github/actionlint.yml
.github/workflows/_push-to-acr.yaml
.github/workflows/build-images.yaml
.github/workflows/release.yaml

This PR begins pushing images to ACR (along with ECR) for releases.
- Added `.github/workflows/_push-to-acr.yaml` workflow to push images to ACR (copied from `cloud` repo)
- Renamed `inputs.upload-to-ecr` to `inputs.upload-to-ecr-acr`

CI: push images to ACR

---

cluster-autoscaler/ca.patch

Thought it was a little odd that the `virtualMachineUsage` type definition was so far away from everything else.

cluster-autoscaler: Consolidate added items in patch

---

pkg/agent/billing/hostname.go

Fixes #1257; the random hostname generation is a fallback that isn't ever used, so we should remove it to reduce confusion.

agent/billing: Require OS hostname

---

pkg/neonvm/controllers/certs.go

Looks like I copy-pasted the wrong logic for tmp secret clean up :D

neonvm-controller: fix the deletion logic for tmp secrets

---

autoscale-scheduler/Dockerfile
autoscaler-agent/Dockerfile
cluster-autoscaler/Dockerfile
go-base.Dockerfile
neonvm-controller/Dockerfile
neonvm-kernel/Dockerfile
neonvm-runner/Dockerfile
neonvm-vxlan-controller/Dockerfile
neonvm/hack/generate.Dockerfile
neonvm/samples/vm-example/Dockerfile
tests/e2e/image-spec.yaml
vm-builder/files/img.Dockerfile
vm-examples/pg16-disk-test/image-spec.yaml

This PR pins all docker images to their SHA checksums to prevent unintentional updates, improve build reproducibility, and improve their "cachability".
SHAs are generated using the following command:
```
docker buildx imagetools inspect --raw ${DOCKER_IMAGE} | openssl dgst -sha256
``` 
For example
```
$ docker buildx imagetools inspect --raw alpine:3.19 | openssl dgst -sha256
SHA2-256(stdin)= e5d0aea7f7d2954678a9a6269ca2d06e06591881161961ea59e974dff3f12377
$ docker buildx imagetools inspect --raw alpine:3.19@sha256:e5d0aea7f7d2954678a9a6269ca2d06e06591881161961ea59e974dff3f12377 | openssl dgst -sha256
SHA2-256(stdin)= e5d0aea7f7d2954678a9a6269ca2d06e06591881161961ea59e974dff3f12377
```
All changes are noop. Where possible, I've added a patch version to image tags.

CI: pin docker images to sha

---

pkg/agent/prommetrics.go
pkg/agent/watch.go

Plus a couple of refactorings.
To be merged with rebase.
Part of #1294.

agent: add ExtraIP per-VM metric 

---

.github/workflows/build-images.yaml

Basically, make there's the same set of images every time and they're in the same order. And if there's an image intentionally missing, comment why.
Also, align spacing in the places where that's feasible, because it makes it easier to see the set of images.
---
Noticed some painful merge conflicts trying to update #1247, figured this bit of cleanup would help (it does!).

ci/build-images: Standardize image sets

---

neonvm-controller/deployment.yaml
neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/config/crd/bases/vm.neon.tech_virtualmachines.yaml

We use kubebuilder:default annotation for scaling mode fields, which effiectively means we never allow it to be non set and that bypasses the logic with --default-cpu-scaling-mode controller argument

neonvm: drop generated default value in CRD

---

.github/workflows/build-images.yaml

Push to ECR started to fail after https://github.com/neondatabase/autoscaling/pull/1312 changes:
```
Copy neondatabase/neonvm-controller:testrelease-20250311.1c7bb48.13791913752 to dev ECR
ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
Spotted in [link](https://github.com/neondatabase/autoscaling/actions/runs/13791913752/job/38574226461?pr=1311#step:11:36)
It tries to push images to `<ECR>/neondatabase/<IMAGE_NAME>` instead of `<ECR>/<IMAGE_NAME>`

ci/build-images: fix push to ECR

---

.github/actionlint.yml
.github/workflows/_push-to-acr.yaml
.github/workflows/build-images.yaml
.github/workflows/release.yaml

This PR reintroduces changes from neondatabase/autoscaling#1285
And on top of it adds environments for the `push-to-acr` workflow to fix pushing to ACR for `tags` events cb2d2210d47d0124c6ffd4b758380e5f73272de8 (see details in https://github.com/neondatabase/infra/pull/3241)

CI: reintroduce push images to ACR

---

pkg/reporting/batch_jsonarray.go
pkg/reporting/batch_jsonarray_test.go

The sink we're sending it to reads input as JSONL, which means that it expects each line to have a complete JSON object. Breaking up the object across lines causes issues.
ref https://neondb.slack.com/archives/C08HDEK2WFL/p1741787069351919?thread_ts=1741786042.532179

reporting/batch: Remove newlines in JSONArrayBuilder

---

neonvm-runner/cmd/httpserver.go
neonvm-runner/cmd/main.go

Currently neonvm-runner returns HTTP 500 on any error with getting or setting CPU inside the VM. This could be more precise.
This PR adopts the following conventions:
1. HTTP 504 "Gateway Timeout" when the request from neonvm-runner to neonvm-daemon fails due to timeout.
2. HTTP 502 "Bad Gateway" for any issue that is plausibly due to an issue with neonvm-daemon. For example:
1. Any HTTP status from neonvm-daemon other than 200 "OK"
2. Any error reading the response body after we receive a 200 "OK"
3. Any errors parsing the resonse from neonvm-daemon
3. HTTP 500 "Internal Server Error" for everything else
For more, see: https://www.rfc-editor.org/rfc/rfc9110.html#section-15.6
Closes #1334, which is about the timeout case.

neonvm-runner: Use HTTP 502,504 for neonvm-daemon issues

---

go.mod
go.sum
neonvm-controller/cmd/main.go
pkg/neonvm/controllers/certs.go
pkg/neonvm/controllers/functests/vm_controller_test.go
pkg/neonvm/controllers/vm_controller.go
pkg/neonvm/controllers/vm_controller_cpu_scaling.go
pkg/neonvm/controllers/vm_controller_unit_test.go
pkg/neonvm/controllers/vmmigration_controller.go
pkg/neonvm/controllers/vmmigration_controller_test.go

On larger clusters with a lot of churn, we see substantial amounts of space in etcd taken up by events from neonvm-controller, even with a relatively short TTL.
So, let's completely remove event reporting in the short term to mitigate risks of running out of space in EKS.
In the meantime, all the relevant information should still be available in the neonvm-controller logs, and we can re-add select events if we think it's worthwhile.
Closes neondatabase/cloud#27262.
Ref https://neondb.slack.com/archives/C08N5D2CF7A/p1744224210018349
Ref https://neondb.slack.com/archives/C03TN5G758R/p1744225420614349
---
**Notes for review:** I haven't examined the logs yet, will do that with the output from e2e tests on CI. I think there's also a lot of cleanup we should to make our log lines more …

neonvm-controller: Don't emit k8s events

---

neonvm-vxlan-controller/daemonset.yaml

This causes virtual devices to be recreated on every restart, and everything what was attached to the old device stops being able to be reached over the overlay network.
The fact that we can't easily recreate vxlan device is concerning. I see a few ways forward:
1. Maybe that's fine, we don't ever need to recreate it.
2. Maybe we can fix multus to reattach device.
3. Do we need a kill switch to disable overlay network in the whole cluster?

vxlan-controller: don't delete bridge on stop

---

pkg/neonvm/controllers/metrics.go
pkg/neonvm/controllers/vm_controller.go

We currently use a lot of buckets < 10s for VM running, but our p50-p99 times are 15s-80s+. This PR updates the buckets for better observability around VM startup times.
Also, `vmCreationToRunnerCreationTime` can be slow in some cases, so it makes sense to log this duration as well.
ref https://neonprod.grafana.net/goto/UCugfLANR?orgId=1

neonvm-controller: Improve VM starts observability

---

Makefile

I tried running the e2e tests on macOS and... didn’t quite succeed 😄
But during the process, I found and fixed a couple of things to make the Makefile more macOS-friendly:
- Install a `yq` version compatible with the host system
- Build `vm-builder` for the host system (as it supposed to be run on the host)
- Update the find command to be compatible with BSD’s find (used in `make run-test`)

Makefile: make setup a bit more macOS-friendly

---

vm-deploy.yaml

Without the change the `vm-deploy.yaml` fails with 
```
Error from server (BadRequest): error when creating "vm-deploy.yaml": VirtualMachine in version "v1" cannot be handled as a VirtualMachine: strict decoding error: unknown field "spec.tlsCertificateIssuer", unknown field "spec.tlsExpiration", unknown field "spec.tlsRenewal"
```

vm-deploy.yaml: fix TLS fields in the example

---

.github/workflows/_push-to-container-registry.yml

Azure OICD is configured for GitHub environments to make it possible to push docker images on tag creation (otherwise we have to list all tags which is not possible to do — Azure doesn't support wildcards https://github.com/Azure/azure-workload-identity/issues/373).
`environment` was lost from the workflow in https://github.com/neondatabase/autoscaling/pull/1283
This PR adds `environment` back to `_push-to-container-registry.yml` workflow.

CI: set environment for Azure to push images on tags

---

autoscale-scheduler/config_map.yaml

Some default plugins can interfere with score calculated by our AutoscaleEnforcer plugin:
- ImageLocality returns score based on image presence
- NodeResourcesBalancedAllocation scores how balanced the resources are
- NodeResourcesFit scores to favor nodes with more free capacity
Let's disable these plugins. Other default plugins are either useful or shouldn't have any effect.
More info: https://neondb.slack.com/archives/C08T2CKLTE3/p1747937332728809

scheduler: Disable some plugins

---

neonvm/apis/neonvm/v1/virtualmachine_types.go
neonvm/config/crd/bases/vm.neon.tech_virtualmachines.yaml
pkg/neonvm/controllers/vm_controller.go
pkg/neonvm/controllers/vm_controller_unit_test.go
tests/e2e/default-values/00-assert.yaml

Do not add affinity if targetArchitecture is nil.
Should imrove quality of live with local development not on x86 and should simplify import jobs spec.
Issue https://github.com/neondatabase/cloud/issues/30328

neonvm: do not use targetArchitecture in affinity, if not set

---

pkg/agent/config.go
pkg/agent/scalingevents/clients.go

Remove the S3 prefix requirement and modify the S3 key. We will use regional buckets from now on and do not need the region prefix there, but we would like to partition data by hours instead of days.
Relates: https://github.com/neondatabase/cloud/issues/29993

billing: Remove S3 prefix check and modify S3 key

---

autoscale-scheduler/cmd/main.go
autoscaler-agent/cmd/main.go

In [LKB-2414](https://databricks.atlassian.net/browse/LKB-2414), we found that the autoscaler-agent can deadlock after a failure during startup. This is because the deferred call to `srv.GetOrchestrator().Wait()` is *before* the canceling of the context, which means that it just blocks forever.
To fix the immediate issue, move the `cancel()` into the same deferred function.
---
I reproduced the issue locally - and confirmed that this fixes it - by modifying the autoscaler-agent's main function to always panic.

agent,plugin: Cancel orca ctx before wait

---

pkg/neonvm/controllers/vm_controller.go

Currently, neonvm-controller is allowed to create a replacement pod without waiting for the old one to be fully deleted. This allows us to recover from node failure without waiting for 25+ minutes for the node to be removed from k8s and object garbage collection to take place.
Unfortunately, because we don't *also* un-link those old pods from the VM object, cascading deletion of the VM object can end up blocked on the deletion of those old pods.
So, after requesting deletion, let's also remove the owner references from the pod so that it doesn't block deletion of the VM object.
ref https://go/es-1529530

neonvm-controller: Cleanup owners while deleting pod

---

vm-builder/files/img.Dockerfile
vm-builder/main.go

In some cases, we need pull base images for `vm-builder` from different registries.
This PR adds `alpine-image` and `busybox-image` flags to make it possible to specify that.
Note: These new flags are a bit inconsistent with `daemon-image`, which allows a full image string (including tag/SHA). The new ones only take registry + image. We can unify this later

vm-builder: allow to set `alpine` and `busybox` from custom sources

---

.github/workflows/build-images.yaml
.github/workflows/vm-kernel.yaml

As part of LKB-2641, we're adding sbom and provenance attestations to all container images, to make them more auditable.

ci: include sbom and provenance attestations in container images

---

cluster-autoscaler/Dockerfile

The git reset command was not properly chained with the cd command, which caused version pinning not to work properly.

cluster-autoscaler: fix command chaining in Dockerfile RUN instruction
